import Link from "next/link";
import { PageHeader, StatusBadge } from "@/components/ui";
import { getAnalyticsAccess, queryValue, type AnalyticsSearchParams } from "@/components/analytics/access";
import { AnalyticsNavigation } from "@/components/analytics/navigation";
import { AnalyticsEmpty, AnalyticsFeedback, AnalyticsSection, AnalyticsTable, ScopeNote, reportTypeLabels, reportScopeLabel, formatAnalyticsDateTime } from "@/components/analytics/presentation";
import { ReportContent } from "@/components/analytics/report-content";
import { ScopeFields } from "@/components/analytics/filters";
import { getAnalyticsChoices } from "@/lib/analytics/read-model";
import { listAnalyticsReports, previewAnalyticsReport } from "@/lib/analytics/reports";
import { generateAnalyticsReportSchema, reportTypeSchema, type AnalyticsReportPayload } from "@/lib/analytics/report-schemas";
import { getAnalyticsSettings, listInstitutionPublicResults } from "@/lib/analytics/public-results";
import { generateReportAction, unpublishResultAction, updateAnalyticsSettingsAction } from "@/app/app/analytics/reports/actions";

export default async function AnalyticsReportsPage({ searchParams }: { searchParams: Promise<AnalyticsSearchParams> }) {
  const { access, canAnalyze, canManage } = await getAnalyticsAccess();
  const parameters = await searchParams;
  const parsedType = reportTypeSchema.safeParse(queryValue(parameters, "type") || "PORTFOLIO_EXECUTIVE");
  const type = parsedType.success ? parsedType.data : "PORTFOLIO_EXECUTIVE";
  const title = queryValue(parameters, "title") || reportTypeLabels[type];
  const programId = queryValue(parameters, "programId");
  const callId = queryValue(parameters, "callId");
  const cohortId = queryValue(parameters, "cohortId");
  const metricId = queryValue(parameters, "metricId");
  const year = queryValue(parameters, "year") ? Number(queryValue(parameters, "year")) : undefined;
  const supersedesId = queryValue(parameters, "supersedesId");
  const scopeParameters = Object.fromEntries(["programId", "callId", "cohortId", "metricId", "year"].map((key) => [key, queryValue(parameters, key)]).filter(([, value]) => value));
  const [reports, choices, publications, settings] = await Promise.all([listAnalyticsReports(access), canAnalyze ? getAnalyticsChoices(access) : null, listInstitutionPublicResults(access), canManage ? getAnalyticsSettings(access) : null]);
  const requestedPreview = canAnalyze && queryValue(parameters, "preview") === "1";
  const input = generateAnalyticsReportSchema.safeParse({ type, title, programId: programId || undefined, callId: callId || undefined, cohortId: cohortId || undefined, metricId: metricId || undefined, year, supersedesId: supersedesId || undefined });
  let preview: AnalyticsReportPayload | null = null;
  let previewError = "";
  if (requestedPreview && input.success) {
    try { preview = await previewAnalyticsReport(access, input.data); }
    catch (error) { previewError = error instanceof Error && error.message === "ANALYTICS_EXECUTIVE_METRIC_LIMIT" ? "executive" : error instanceof Error && error.message.includes("TOO_LARGE") ? "limit" : "scope"; }
  } else if (requestedPreview) previewError = "invalid";
  return <div className="min-w-0 space-y-6"><PageHeader title="Relatórios analíticos" description="Recortes imutáveis da evidência institucional, separados das entregas de execução." /><AnalyticsNavigation current="/app/analytics/reports" canConfigure={canAnalyze} /><AnalyticsFeedback error={queryValue(parameters, "error") || previewError} success={queryValue(parameters, "success")} />
    {canAnalyze && choices ? <AnalyticsSection title="Preparar relatório" description="Escolha um tipo, defina o escopo e confira a prévia antes de gerar o recorte."><div className="p-4 sm:p-6"><nav className="analytics-report-types" aria-label="Tipo de relatório">{Object.entries(reportTypeLabels).map(([value, label]) => <Link key={value} href={`/app/analytics/reports?${new URLSearchParams({ type: value, ...scopeParameters })}`} aria-current={type === value ? "page" : undefined}>{label}</Link>)}</nav><form method="get" action="/app/analytics/reports" className="analytics-filter-fields mt-5"><input type="hidden" name="type" value={type} /><input type="hidden" name="preview" value="1" />{supersedesId ? <input type="hidden" name="supersedesId" value={supersedesId} /> : null}<label className="sm:col-span-2">Título<input className="field-control" name="title" minLength={3} maxLength={160} defaultValue={title} required /></label><ScopeFields choices={choices} filters={{ programId: programId || undefined, callId: callId || undefined, cohortId: cohortId || undefined, metricId: metricId || undefined, year }} requireProgram={type === "PROGRAM_SUMMARY"} requireCohort={type === "COHORT_LONGITUDINAL"} includeMetric={type !== "EXECUTION_SUMMARY"} /><div className="flex items-end"><button type="submit" className="button-primary">Conferir prévia</button></div></form></div></AnalyticsSection> : <ScopeNote>Seu vínculo permite consultar relatórios. A geração de novos recortes exige permissão de analista ou superior.</ScopeNote>}
    {preview && input.success ? <section className="space-y-6" aria-labelledby="live-report-preview"><header className="flex flex-wrap items-start justify-between gap-4 border-y border-line py-5"><div><h2 id="live-report-preview" className="text-xl font-semibold">Prévia com dados atuais</h2><p className="mt-2 text-sm text-slate">{preview.title} · {reportScopeLabel(preview.scope)}</p><p className="mt-1 text-xs text-slate">O relatório será fixado com os dados disponíveis no momento da geração.</p></div><form action={generateReportAction}><input type="hidden" name="type" value={input.data.type} /><input type="hidden" name="title" value={input.data.title} />{input.data.programId ? <input type="hidden" name="programId" value={input.data.programId} /> : null}{input.data.cohortId ? <input type="hidden" name="cohortId" value={input.data.cohortId} /> : null}{input.data.metricId ? <input type="hidden" name="metricId" value={input.data.metricId} /> : null}{input.data.callId ? <input type="hidden" name="callId" value={input.data.callId} /> : null}{input.data.year !== undefined ? <input type="hidden" name="year" value={input.data.year} /> : null}{input.data.supersedesId ? <input type="hidden" name="supersedesId" value={input.data.supersedesId} /> : null}<button type="submit" className="button-primary">Gerar relatório imutável</button></form></header><ReportContent payload={preview} /></section> : null}
    <AnalyticsSection title="Relatórios preservados" description="Até 100 recortes recentes, incluindo o histórico arquivado.">{reports.length ? <AnalyticsTable caption="Relatórios gerados com a evidência disponível na data informada" headings={["Relatório", "Tipo / escopo", "Gerado em", "Situação"]} rows={reports.map((report) => [<Link key="report" className="analytics-link" href={`/app/analytics/reports/${report.id}`}>{report.title}</Link>, <>{reportTypeLabels[report.type]}<span className="mt-1 block text-xs text-slate">{reportScopeLabel(report.payload.scope)}</span></>, formatAnalyticsDateTime(report.generatedAt), <StatusBadge key="status" label={report.archivedAt ? "Arquivado" : "Preservado"} />])} /> : <AnalyticsEmpty title="Preserve um recorte da evidência" description="Gere um relatório a partir de dados existentes para preservar um recorte no tempo." />}</AnalyticsSection>
    <AnalyticsSection title="Publicações de resultados" description="Publicações intencionais a partir de relatórios gerados. A atualização dos dados exige um novo relatório.">{publications.length ? <AnalyticsTable caption="Histórico institucional de publicações; retirar o acesso público preserva o relatório interno." headings={["Publicação", "Publicada em", "Situação", "Ação"]} rows={publications.map((publication) => [publication.unpublishedAt ? publication.title : <Link href={`/results/${publication.slug}`} className="analytics-link">{publication.title}</Link>, formatAnalyticsDateTime(publication.publishedAt), <StatusBadge key="status" label={publication.unpublishedAt ? "Retirada" : "Publicada"} tone={publication.unpublishedAt ? "neutral" : "success"} />, canManage && !publication.unpublishedAt ? <form action={unpublishResultAction}><input type="hidden" name="publicationId" value={publication.id} /><button type="submit" className="button-secondary">Retirar do público</button></form> : <Link href={`/app/analytics/reports/${publication.reportSnapshotId}`} className="analytics-link">Ver relatório</Link>])} /> : <AnalyticsEmpty title="Nenhum resultado publicado" description="Um gestor pode abrir um relatório, conferir a prévia protegida e confirmar sua publicação." />}</AnalyticsSection>
    {canManage && settings ? <details className="analytics-filters"><summary>Proteção dos resultados públicos</summary><form action={updateAnalyticsSettingsAction} className="mt-4 max-w-xl space-y-4"><label className="block text-sm font-medium">Mínimo de registros por grupo<input className="field-control mt-2" type="number" name="publicMinimumCellSize" min={3} max={20} step={1} defaultValue={settings.publicMinimumCellSize} required /></label><p className="text-xs leading-5 text-slate">Use de 3 a 20 registros. O padrão é 5. A regra será aplicada às novas publicações; publicações existentes preservam a prévia aprovada. A supressão pode abranger células adicionais para evitar identificação por diferença.</p><button type="submit" className="button-secondary">Salvar regra de proteção</button></form></details> : null}
  </div>;
}
