"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useRef, useState, type FormEvent, type ChangeEvent } from "react";
import { MediaImage } from "@/components/media/media-image";
import { PostImagePicker, type PostImageDraft } from "@/components/media/post-image-picker";
import { discardImage, imageSelectionError, uploadImage } from "@/components/media/client";
import { personalRequest } from "@/components/personal/record-form";
import type { MediaDto } from "@/lib/media/types";
import type { SocialPostDto } from "@/lib/social/types";

type ProgramItem = { id: string; name: string; slug: string; status: string; publicPageEnabled: boolean; publishedAt: string | null };
type PageState = { id: string; name: string; slug: string; profile: { headline: string | null; description: string | null; city: string | null; state: string | null; country: string | null; websiteUrl: string | null; focusAreas: string[]; publishedAt: string | null; logoMedia: MediaDto | null; coverMedia: MediaDto | null } | null; followerCount: number; publicCallCount: number; publicResultCount: number; programs: ProgramItem[]; posts: SocialPostDto[]; permissions: { canManageProfile: boolean; canManagePosts: boolean } };

export function InstitutionPublicPageManagement({ organizationId, initial, storageEnabled }: { organizationId: string; initial: PageState; storageEnabled: boolean }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [uploading, setUploading] = useState<"ORGANIZATION_LOGO" | "ORGANIZATION_COVER" | null>(null);
  const logoInput = useRef<HTMLInputElement>(null); const coverInput = useRef<HTMLInputElement>(null); const profile = initial.profile;
  async function saveProfile(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (pending) return; const data = new FormData(event.currentTarget); setPending(true); setError(null); setNotice(null);
    const input = { headline: data.get("headline"), description: data.get("description"), city: data.get("city"), state: data.get("state"), country: data.get("country"), websiteUrl: data.get("websiteUrl"), focusAreas: String(data.get("focusAreas") ?? "").split(",").map((value) => value.trim()).filter(Boolean) };
    try { await personalRequest(`/api/organizations/${organizationId}/public-page`, "PATCH", input); setNotice("Informações institucionais salvas."); router.refresh(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível salvar as informações."); }
    finally { setPending(false); }
  }
  async function setPublished(published: boolean) {
    setPending(true); setError(null); setNotice(null);
    try { await personalRequest(`/api/organizations/${organizationId}/public-page/publication`, "PATCH", { published }); setNotice(published ? "Página institucional publicada." : "Página institucional despublicada."); router.refresh(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível alterar a publicação."); }
    finally { setPending(false); }
  }
  async function selectBranding(event: ChangeEvent<HTMLInputElement>, kind: "ORGANIZATION_LOGO" | "ORGANIZATION_COVER") {
    const file = event.target.files?.[0]; event.target.value = ""; if (!file || uploading || pending) return;
    const issue = imageSelectionError(file, kind); if (issue) { setError(issue); return; }
    setError(null); setNotice(null); setUploading(kind); let uploaded: MediaDto | null = null;
    try { uploaded = await uploadImage(file, kind, { organizationId }); await personalRequest(`/api/organizations/${organizationId}/public-page/media`, "PATCH", { kind, mediaId: uploaded.id }); setNotice(kind === "ORGANIZATION_LOGO" ? "Logotipo atualizado." : "Imagem de capa atualizada."); router.refresh(); }
    catch (cause) { if (uploaded) void discardImage(uploaded.id, organizationId); setError(cause instanceof Error ? cause.message : "Não foi possível atualizar a imagem."); }
    finally { setUploading(null); }
  }
  async function removeBranding(kind: "ORGANIZATION_LOGO" | "ORGANIZATION_COVER") {
    setPending(true); setError(null); setNotice(null);
    try { await personalRequest(`/api/organizations/${organizationId}/public-page/media`, "PATCH", { kind, mediaId: null }); setNotice(kind === "ORGANIZATION_LOGO" ? "Logotipo removido." : "Imagem de capa removida."); router.refresh(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível remover a imagem."); }
    finally { setPending(false); }
  }
  async function setProgramPublished(program: ProgramItem, published: boolean) {
    setPending(true); setError(null); setNotice(null);
    try { await personalRequest(`/api/organizations/${organizationId}/programs/${program.id}/publication`, "PATCH", { published }); setNotice(published ? `Programa “${program.name}” publicado.` : `Programa “${program.name}” removido da página pública.`); router.refresh(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível alterar o programa."); }
    finally { setPending(false); }
  }
  return <div className="space-y-7">
    <header className="flex flex-col gap-4 border-b border-line pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-accent-hover">Presença pública</p><h1 className="mt-2 break-words text-2xl font-semibold">Página institucional</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate">Apresente a instituição, seus programas e atualizações oficiais. A publicação é sempre uma escolha explícita.</p><p className="mt-2 text-sm text-slate">{initial.followerCount} {initial.followerCount === 1 ? "seguidor" : "seguidores"} · {initial.publicCallCount} {initial.publicCallCount === 1 ? "chamada marcada como pública" : "chamadas marcadas como públicas"} · {initial.publicResultCount} {initial.publicResultCount === 1 ? "resultado publicado" : "resultados publicados"} · {profile?.publishedAt ? "Página publicada" : "Página não publicada"}</p></div><div className="flex flex-wrap gap-2"><Link className="button-secondary" href={`/institutions/${initial.slug}${profile?.publishedAt ? "" : "?preview=1"}`} target="_blank">{profile?.publishedAt ? "Visualizar página" : "Prévia interna"}</Link>{initial.permissions.canManageProfile ? <button className={profile?.publishedAt ? "button-secondary" : "button-primary"} disabled={pending} aria-busy={pending} onClick={() => void setPublished(!profile?.publishedAt)}>{profile?.publishedAt ? "Despublicar página" : "Publicar página"}</button> : null}</div></header>
    {error ? <p className="rounded-lg border border-danger/30 bg-danger-soft p-3 text-sm text-danger" role="alert">{error}</p> : null}{notice ? <p className="text-sm text-success" role="status">{notice}</p> : null}
    <section className="panel"><div className="panel-header"><h2>Identidade pública</h2><p>O nome e o endereço são os dados atuais da organização.</p></div><form onSubmit={(event) => void saveProfile(event)} className="grid gap-5 p-5 sm:grid-cols-2 sm:p-6">
      <label className="block space-y-2 text-sm font-medium sm:col-span-2"><span>Apresentação curta</span><input className="field-control" name="headline" defaultValue={profile?.headline ?? ""} maxLength={180} disabled={!initial.permissions.canManageProfile} placeholder="O que a instituição apoia ou realiza?" /></label>
      <label className="block space-y-2 text-sm font-medium sm:col-span-2"><span>Sobre a instituição</span><textarea className="field-control" name="description" rows={6} defaultValue={profile?.description ?? ""} maxLength={5000} disabled={!initial.permissions.canManageProfile} placeholder="Descreva a atuação institucional e seu papel no ecossistema de inovação." /></label>
      <label className="block space-y-2 text-sm font-medium"><span>Cidade</span><input className="field-control" name="city" defaultValue={profile?.city ?? ""} maxLength={100} disabled={!initial.permissions.canManageProfile} /></label><label className="block space-y-2 text-sm font-medium"><span>Estado</span><input className="field-control" name="state" defaultValue={profile?.state ?? ""} maxLength={100} disabled={!initial.permissions.canManageProfile} /></label>
      <label className="block space-y-2 text-sm font-medium"><span>País</span><input className="field-control" name="country" defaultValue={profile?.country ?? "Brasil"} maxLength={100} disabled={!initial.permissions.canManageProfile} /></label><label className="block space-y-2 text-sm font-medium"><span>Site institucional</span><input className="field-control" name="websiteUrl" type="url" pattern="https://.*" defaultValue={profile?.websiteUrl ?? ""} maxLength={2000} placeholder="https://" disabled={!initial.permissions.canManageProfile} /></label>
      <label className="block space-y-2 text-sm font-medium sm:col-span-2"><span>Áreas de atuação</span><input className="field-control" name="focusAreas" defaultValue={profile?.focusAreas.join(", ") ?? ""} maxLength={800} disabled={!initial.permissions.canManageProfile} placeholder="Tecnologia, empreendedorismo, pesquisa" /><span className="block text-xs font-normal text-slate">Separe até doze áreas por vírgula.</span></label>
      {initial.permissions.canManageProfile ? <div className="sm:col-span-2"><button className="button-primary" disabled={pending}>{pending ? "Salvando…" : "Salvar informações"}</button></div> : <p className="text-sm text-slate sm:col-span-2">Apenas OWNER, ADMIN ou pessoa com permissão de administração pode editar a identidade e publicação.</p>}
    </form></section>
    <section className="panel"><div className="panel-header"><h2>Imagens institucionais</h2><p>As imagens pertencem à organização e só ficam públicas enquanto a página estiver publicada.</p></div><div className="grid gap-6 p-5 sm:grid-cols-2 sm:p-6">
      <div className="space-y-3"><h3 className="text-sm font-semibold">Logotipo</h3><div className="flex min-h-28 items-center justify-center rounded-lg border border-line bg-surface-subtle p-4">{profile?.logoMedia ? <MediaImage media={profile.logoMedia} alt={`${initial.name} — logotipo`} className="max-h-24 max-w-full object-contain" sizes="300px" /> : <span className="text-sm text-slate">Prévia com monograma</span>}</div><input ref={logoInput} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" aria-label="Selecionar logotipo" disabled={!initial.permissions.canManageProfile || !storageEnabled || Boolean(uploading)} onChange={(event) => void selectBranding(event, "ORGANIZATION_LOGO")} /><div className="flex flex-wrap gap-2"><button className="button-secondary" type="button" disabled={!initial.permissions.canManageProfile || !storageEnabled || Boolean(uploading)} onClick={() => logoInput.current?.click()}>{uploading === "ORGANIZATION_LOGO" ? "Enviando…" : profile?.logoMedia ? "Alterar logotipo" : "Adicionar logotipo"}</button>{profile?.logoMedia && initial.permissions.canManageProfile ? <button className="button-tertiary" type="button" disabled={pending} onClick={() => void removeBranding("ORGANIZATION_LOGO")}>Remover</button> : null}</div><p className="text-xs leading-5 text-slate">JPEG, PNG ou WebP · Até 5 MB · O nome da instituição é usado quando não há logotipo.</p></div>
      <div className="space-y-3"><h3 className="text-sm font-semibold">Capa</h3><div className="aspect-[3/1] overflow-hidden rounded-lg border border-line bg-surface-subtle">{profile?.coverMedia ? <MediaImage media={profile.coverMedia} alt="Prévia da capa institucional" className="h-full w-full object-cover" sizes="500px" /> : <div className="institution-cover-fallback"><span>Atlas Innove</span></div>}</div><input ref={coverInput} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" aria-label="Selecionar imagem de capa" disabled={!initial.permissions.canManageProfile || !storageEnabled || Boolean(uploading)} onChange={(event) => void selectBranding(event, "ORGANIZATION_COVER")} /><div className="flex flex-wrap gap-2"><button className="button-secondary" type="button" disabled={!initial.permissions.canManageProfile || !storageEnabled || Boolean(uploading)} onClick={() => coverInput.current?.click()}>{uploading === "ORGANIZATION_COVER" ? "Enviando…" : profile?.coverMedia ? "Alterar capa" : "Adicionar capa"}</button>{profile?.coverMedia && initial.permissions.canManageProfile ? <button className="button-tertiary" type="button" disabled={pending} onClick={() => void removeBranding("ORGANIZATION_COVER")}>Remover</button> : null}</div><p className="text-xs leading-5 text-slate">JPEG, PNG ou WebP · Até 8 MB · As imagens são processadas sem metadados de localização.</p></div>
      {!storageEnabled ? <p className="text-sm leading-6 text-slate sm:col-span-2">O armazenamento de imagens não está configurado. A página continua disponível com o monograma e a capa padrão.</p> : null}
    </div></section>
    <section className="panel"><div className="panel-header"><h2>Programas na página pública</h2><p>Somente programas explicitamente publicados aparecem para visitantes.</p></div><ul className="divide-y divide-line px-5 sm:px-6">{initial.programs.length ? initial.programs.map((program) => <li key={program.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><h3 className="break-words font-medium">{program.name}</h3><p className="mt-1 text-xs text-slate">{program.status === "DRAFT" ? "Rascunho" : program.status === "ACTIVE" ? "Ativo" : program.status === "CLOSED" ? "Encerrado" : "Arquivado"}</p></div><button className={program.publicPageEnabled ? "button-secondary" : "button-tertiary"} type="button" disabled={!initial.permissions.canManagePosts || pending || program.status === "DRAFT" || !profile?.publishedAt} aria-pressed={program.publicPageEnabled} onClick={() => void setProgramPublished(program, !program.publicPageEnabled)}>{program.publicPageEnabled ? "Remover da página" : "Publicar programa"}</button></li>) : <li className="py-5 text-sm text-slate">Nenhum programa cadastrado.</li>}</ul>{!profile?.publishedAt ? <p className="px-5 pb-5 text-xs text-slate sm:px-6">Publique primeiro a página institucional para liberar a publicação de programas.</p> : null}</section>
    {initial.permissions.canManagePosts ? <InstitutionPostManagement organizationId={organizationId} organizationName={initial.name} published={Boolean(profile?.publishedAt)} programs={initial.programs} posts={initial.posts} /> : null}
  </div>;
}

function InstitutionPostManagement({ organizationId, organizationName, published, programs, posts }: { organizationId: string; organizationName: string; published: boolean; programs: ProgramItem[]; posts: SocialPostDto[] }) {
  const router = useRouter(); const [composerOpen, setComposerOpen] = useState(false); const [editing, setEditing] = useState<SocialPostDto | null>(null); const [body, setBody] = useState(""); const [url, setUrl] = useState(""); const [visibility, setVisibility] = useState<"PUBLIC" | "PLATFORM">("PUBLIC"); const [commentPolicy, setCommentPolicy] = useState<"EVERYONE" | "OFF">("EVERYONE"); const [allowReposts, setAllowReposts] = useState(true); const [programId, setProgramId] = useState(""); const [images, setImages] = useState<PostImageDraft[]>([]); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null);
  function start(post?: SocialPostDto) { setError(null); setComposerOpen(true); setEditing(post ?? null); setBody(post?.body ?? ""); setUrl(post?.externalUrl ?? ""); setVisibility(post?.visibility === "PLATFORM" ? "PLATFORM" : "PUBLIC"); setCommentPolicy(post?.commentPolicy === "OFF" ? "OFF" : "EVERYONE"); setAllowReposts(post?.allowReposts ?? true); setProgramId(post?.fundingProgramId ?? ""); setImages(post?.media.map((media) => ({ mediaId: media.mediaId ?? media.id, altText: media.altText ?? "", media })) ?? []); }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (pending) return; setError(null); const cleanBody = body.trim(); const cleanUrl = url.trim();
    if (!cleanBody && !cleanUrl && !images.length) { setError("Escreva uma atualização, adicione um link ou uma imagem."); return; }
    if (cleanUrl) { try { const target = new URL(cleanUrl); if (target.protocol !== "https:" || target.username || target.password) throw new Error(); } catch { setError("Informe um endereço HTTPS válido, sem credenciais."); return; } }
    setPending(true);
    try {
      const payload = { body: cleanBody || null, externalUrl: cleanUrl || null, media: images.map(({ mediaId, altText }) => ({ mediaId, altText: altText.trim() || null })), visibility, commentPolicy, allowReposts, fundingProgramId: programId || null, ...(editing ? { revision: editing.revision } : {}) };
      await personalRequest(editing ? `/api/organizations/${organizationId}/public-page/posts/${editing.id}` : `/api/organizations/${organizationId}/public-page/posts`, editing ? "PATCH" : "POST", payload);
      setComposerOpen(false); setEditing(null); setBody(""); setUrl(""); setImages([]); setProgramId(""); router.refresh();
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível publicar. Os campos preenchidos foram preservados."); }
    finally { setPending(false); }
  }
  async function remove(post: SocialPostDto) {
    if (!window.confirm("Remover esta publicação institucional? O histórico de auditoria será preservado.")) return;
    setPending(true); setError(null);
    try { await personalRequest(`/api/organizations/${organizationId}/public-page/posts/${post.id}`, "DELETE"); router.refresh(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível remover a publicação."); }
    finally { setPending(false); }
  }
  return <section className="panel"><div className="panel-header"><h2>Publicações oficiais</h2><p>Publicações feitas em nome de {organizationName}, com histórico do responsável pela alteração.</p></div><div className="space-y-5 p-5 sm:p-6">
    <button type="button" className="button-primary" disabled={composerOpen || pending} onClick={() => start()}>Criar publicação oficial</button>
    {!published ? <p className="text-sm leading-6 text-slate">Publicações em “Pessoas na plataforma” podem ser preparadas. Para publicar para todos, publique a página institucional primeiro.</p> : null}
    {composerOpen ? <form onSubmit={(event) => void submit(event)} className="space-y-4 rounded-lg border border-line p-4" aria-label={editing ? "Editar publicação institucional" : "Criar publicação institucional"}>
      <div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-lg border border-line bg-surface-subtle font-semibold text-ink" aria-hidden="true">{organizationName.slice(0, 2).toLocaleUpperCase("pt-BR")}</div><div><p className="text-sm font-semibold">{organizationName}</p><p className="text-xs text-slate">Publicação oficial da instituição</p></div></div>
      <label className="block space-y-2 text-sm font-medium"><span>Atualização</span><textarea className="field-control" rows={5} maxLength={3000} value={body} onChange={(event) => setBody(event.target.value)} placeholder="Compartilhe uma atualização institucional." /><span className="block text-right text-xs font-normal text-slate">{body.length}/3.000</span></label>
      <PostImagePicker value={images} onChange={setImages} organizationId={organizationId} disabled={pending} />
      <label className="block space-y-2 text-sm font-medium"><span>Link HTTPS (opcional)</span><input className="field-control" type="url" pattern="https://.*" value={url} onChange={(event) => setUrl(event.target.value)} maxLength={2000} placeholder="https://" /></label>
      <div className="grid gap-4 sm:grid-cols-2"><label className="block space-y-2 text-sm font-medium"><span>Visibilidade</span><select className="field-control" value={visibility} onChange={(event) => setVisibility(event.target.value as "PUBLIC" | "PLATFORM")}><option value="PUBLIC" disabled={!published}>Público</option><option value="PLATFORM">Pessoas na plataforma</option></select></label><label className="block space-y-2 text-sm font-medium"><span>Programa relacionado (opcional)</span><select className="field-control" value={programId} onChange={(event) => setProgramId(event.target.value)}><option value="">Sem programa específico</option>{programs.map((program) => <option key={program.id} value={program.id}>{program.name}{program.publicPageEnabled ? " · público" : " · interno"}</option>)}</select></label></div>
      <div className="flex flex-wrap items-center gap-5"><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={commentPolicy === "EVERYONE"} onChange={(event) => setCommentPolicy(event.target.checked ? "EVERYONE" : "OFF")} />Permitir comentários</label><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={allowReposts} onChange={(event) => setAllowReposts(event.target.checked)} />Permitir repostagens</label></div>
      {error ? <p role="alert" className="text-sm text-danger">{error}</p> : null}<div className="flex flex-wrap gap-2"><button className="button-primary" disabled={pending}>{pending ? "Salvando…" : editing ? "Salvar alterações" : "Publicar"}</button><button className="button-secondary" type="button" disabled={pending} onClick={() => { for (const image of images) if (!editing?.media.some((attached) => attached.id === image.mediaId)) void discardImage(image.mediaId, organizationId); setComposerOpen(false); setEditing(null); setBody(""); setUrl(""); setImages([]); setProgramId(""); setError(null); }}>Cancelar</button></div>
    </form> : null}
    {posts.length ? <ul className="space-y-3">{posts.map((post) => <li key={post.id} className="rounded-lg border border-line p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><p className="text-xs text-slate">{post.visibility === "PUBLIC" ? "Público" : "Pessoas na plataforma"} · {new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium", timeZone: "UTC" }).format(new Date(post.createdAt))}{post.editedAt ? " · Editado" : ""}</p><p className="mt-2 whitespace-pre-line break-words text-sm leading-6">{post.body || post.externalUrl || `${post.media.length} ${post.media.length === 1 ? "imagem" : "imagens"}`}</p></div><div className="flex gap-2"><button type="button" className="button-tertiary" disabled={pending} onClick={() => start(post)}>Editar</button><button type="button" className="button-tertiary text-danger" disabled={pending} onClick={() => void remove(post)}>Remover</button></div></div><p className="mt-2 text-xs text-slate">Revisão {post.revision} · O histórico de alterações é preservado.</p></li>)}</ul> : <p className="text-sm text-slate">Nenhuma publicação oficial ainda.</p>}
  </div></section>;
}
