import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test from "node:test";
import { db } from "@/lib/db";
import { createProject } from "@/lib/participants/service";
import { createAward, createAwardDocument, createDisbursement, createObligation, getInstitutionAward, getPersonalAward, listCallExecution, listOrganizationExecution, rescheduleObligation, reviewSubmission, saveSubmissionDraft, submitSubmission, transitionAward, updateAward, updateDisbursement, updateObligation, waiveObligation, type OrganizationAccess } from "@/lib/awards/service";

test("formal awards enforce tenant eligibility, immutable execution history and participant privacy", async (context) => {
  if (!process.env.DATABASE_URL) { assert.notEqual(process.env.CI, "true", "CI requires PostgreSQL award tests"); assert.notEqual(process.env.REQUIRE_DOMAIN_DATABASE, "true"); context.skip("Disposable PostgreSQL is required"); return; }
  context.after(() => db.$disconnect());
  const suffix = randomUUID();
  const users = await Promise.all(["manager", "analyst", "viewer", "participant", "member", "outsider", "manager-b"].map((label) => db.user.create({ data: { email: `award-${label}-${suffix}@example.test`, passwordHash: "test-only", profile: { create: { fullName: `Award ${label}` } } }, include: { profile: true } })));
  const [manager, analyst, viewer, participant, member, outsider, managerB] = users;
  const org = await db.organization.create({ data: { name: "Award institution", slug: `award-${suffix}` } });
  const otherOrg = await db.organization.create({ data: { name: "Other award institution", slug: `award-b-${suffix}` } });
  const memberships = await Promise.all([[manager, org, "MANAGER"], [analyst, org, "ANALYST"], [viewer, org, "VIEWER"], [managerB, otherOrg, "MANAGER"]].map(([user, organization, role]) => db.organizationMembership.create({ data: { userId: (user as typeof manager).id, organizationId: (organization as typeof org).id, role: role as "MANAGER" | "ANALYST" | "VIEWER" }, include: { organization: true } })));
  const accessFor = (index: number): OrganizationAccess => ({ auth: { user: [manager, analyst, viewer, managerB][index], session: { id: "test-session", activeOrganizationId: memberships[index].organizationId }, memberships: [memberships[index]] }, organization: memberships[index].organization, membership: memberships[index] });
  const access = accessFor(0); const analystAccess = accessFor(1); const viewerAccess = accessFor(2); const otherAccess = accessFor(3);
  const program = await db.fundingProgram.create({ data: { organizationId: org.id, name: "Award program", slug: `award-${suffix}`, createdByUserId: manager.id } });
  const otherProgram = await db.fundingProgram.create({ data: { organizationId: otherOrg.id, name: "Other program", slug: `award-${suffix}`, createdByUserId: managerB.id } });
  const call = await db.fundingCall.create({ data: { organizationId: org.id, fundingProgramId: program.id, title: "Published results", callNumber: "award", status: "RESULT_PUBLISHED", resultsPublishedAt: new Date() } });
  const unpublishedCall = await db.fundingCall.create({ data: { organizationId: org.id, fundingProgramId: program.id, title: "Unpublished results", callNumber: "unpublished", status: "IN_REVIEW" } });
  const otherCall = await db.fundingCall.create({ data: { organizationId: otherOrg.id, fundingProgramId: otherProgram.id, title: "Other published results", callNumber: "award", status: "RESULT_PUBLISHED", resultsPublishedAt: new Date() } });
  const applications = [];
  const projectIds: string[] = [];
  for (const label of ["selected", "second", "cancel", "terminate", "not-selected", "withdrawn", "unpublished", "concurrent"]) {
    const project = await createProject(participant.id, { name: `Award ${label}`, summary: "Stable initiative submitted to an institutional program." }); projectIds.push(project.id);
    applications.push(await db.application.create({ data: { organizationId: org.id, fundingCallId: label === "unpublished" ? unpublishedCall.id : call.id, projectId: project.id, submittedByUserId: participant.id, submittedAt: new Date(), status: label === "withdrawn" ? "WITHDRAWN" : "DECIDED", withdrawnAt: label === "withdrawn" ? new Date() : null, decision: label === "not-selected" ? "NOT_SELECTED" : "SELECTED", projectNameSnapshot: project.name, projectSummarySnapshot: project.summary, decisionNote: "PRIVATE_SELECTION_NOTE" } }));
  }
  const [selected, second, cancellation, termination, notSelected, withdrawn, unpublished, concurrent] = applications;
  await db.projectMembership.create({ data: { projectId: selected.projectId, userId: member.id, role: "MEMBER" } });
  let award = await createAward(access, program.id, call.id, { applicationId: selected.id });
  await context.test("only published selected applications can receive unique support within their organization and call", async () => {
    assert.equal(award.status, "PREPARING"); assert.equal(award.approvedAmount, null); assert.equal(award.statusHistory.length, 1);
    assert.equal(award.statusHistory[0].fromStatus, null); assert.equal(award.statusHistory[0].changedBy.id, manager.id);
    await assert.rejects(() => createAward(access, program.id, call.id, { applicationId: selected.id }), /AWARD_ALREADY_EXISTS/);
    await assert.rejects(() => createAward(access, program.id, call.id, { applicationId: notSelected.id }), /AWARD_APPLICATION_NOT_ELIGIBLE/);
    await assert.rejects(() => createAward(access, program.id, call.id, { applicationId: withdrawn.id }), /AWARD_APPLICATION_NOT_ELIGIBLE/);
    await assert.rejects(() => createAward(access, program.id, unpublishedCall.id, { applicationId: unpublished.id }), /AWARD_RESULTS_NOT_PUBLISHED/);
    await assert.rejects(() => createAward(otherAccess, otherProgram.id, otherCall.id, { applicationId: selected.id }), /AWARD_APPLICATION_NOT_ELIGIBLE/);
    await assert.rejects(() => getInstitutionAward(otherAccess, award.id), /AWARD_NOT_FOUND/);
    await assert.rejects(() => createAward(analystAccess, program.id, call.id, { applicationId: second.id }), /ROLE_FORBIDDEN/);
    const results = await Promise.allSettled([createAward(access, program.id, call.id, { applicationId: concurrent.id }), createAward(access, program.id, call.id, { applicationId: concurrent.id })]);
    assert.equal(results.filter((result) => result.status === "fulfilled").length, 1);
    await assert.rejects(() => db.award.create({ data: { organizationId: otherOrg.id, fundingCallId: otherCall.id, applicationId: selected.id, createdByUserId: managerB.id } }));
    await assert.rejects(() => db.award.create({ data: { organizationId: org.id, fundingCallId: call.id, applicationId: second.id, createdByUserId: manager.id } }), /AWARD_STATUS_HISTORY_REQUIRED/);
  });
  await context.test("activation confirms the date-only execution period and every transition appends history", async () => {
    await assert.rejects(() => transitionAward(access, award.id, { revision: award.revision, status: "ACTIVE", confirmed: true }), /AWARD_START_REQUIRED/);
    award = await updateAward(access, award.id, { revision: award.revision, startsAt: "2026-10-06", endsAt: "2027-10-06", approvedAmount: "1234.56" });
    assert.equal(award.startsAt, "2026-10-06"); assert.equal(award.approvedAmount, "1234.56");
    await assert.rejects(() => db.awardStatusHistory.create({ data: { organizationId: org.id, awardId: award.id, fromStatus: "ACTIVE", toStatus: "PREPARING", awardRevision: award.revision, changedByUserId: manager.id } }), /AWARD_STATUS_HISTORY_INVALID/);
    award = await transitionAward(access, award.id, { revision: award.revision, status: "ACTIVE", confirmed: true });
    const activatedAt = award.activatedAt;
    await assert.rejects(() => updateAward(access, award.id, { revision: award.revision, approvedAmount: "900" }), /AWARD_TERMS_FROZEN/);
    award = await transitionAward(access, award.id, { revision: award.revision, status: "SUSPENDED", reason: "Execution temporarily paused" });
    assert.equal(award.statusHistory[0].toStatus, "SUSPENDED");
    award = await transitionAward(access, award.id, { revision: award.revision, status: "ACTIVE", confirmed: true });
    assert.equal(award.activatedAt, activatedAt); assert.equal(award.statusHistory.length, 4);
    await assert.rejects(() => db.awardStatusHistory.update({ where: { id: award.statusHistory[0].id }, data: { reason: "Overwrite" } }), /AWARD_HISTORY_IMMUTABLE/);
    await assert.rejects(() => db.award.update({ where: { id: award.id }, data: { status: "SUSPENDED", revision: { increment: 1 } } }), /AWARD_STATUS_HISTORY_REQUIRED/);
  });
  award = await createObligation(access, award.id, { type: "PROGRESS_REPORT", title: "Technical progress report", description: "Document institutional execution.", dueAt: "2026-10-10", periodStartsAt: "2026-10-06", periodEndsAt: "2026-10-10" });
  let obligation = award.obligations[0];
  await context.test("obligations can be edited before submission and participant-only drafts never enter institutional DTOs", async () => {
    award = await updateObligation(access, award.id, obligation.id, { revision: obligation.revision, type: obligation.type, title: "Updated progress report", dueAt: "2026-10-15", required: true }); obligation = award.obligations[0];
    await assert.rejects(() => saveSubmissionDraft(member.id, award.id, obligation.id, { revision: 0, summary: "Member cannot submit" }), /PARTICIPANT_ROLE_FORBIDDEN/);
    await assert.rejects(() => getPersonalAward(outsider.id, award.id), /AWARD_NOT_FOUND/);
    const draft = await saveSubmissionDraft(participant.id, award.id, obligation.id, { revision: 0, summary: "PRIVATE_DRAFT_SUMMARY", details: "PRIVATE_DRAFT_DETAILS", evidence: [{ label: "PRIVATE_DRAFT_EVIDENCE", url: "https://example.test/private-draft" }] });
    assert.equal(draft.version, 1);
    const institution = await getInstitutionAward(access, award.id);
    assert.equal(institution.obligations[0].draftExists, true); assert.equal(institution.obligations[0].submissions.length, 0);
    assert.equal(JSON.stringify(institution).includes("PRIVATE_DRAFT"), false);
    const callExecution = await listCallExecution(access, program.id, call.id);
    assert.equal(JSON.stringify(callExecution).includes("PRIVATE_DRAFT"), false);
    assert.equal(JSON.stringify(await listOrganizationExecution(access)).includes("PRIVATE_DRAFT"), false);
    const races = await Promise.allSettled([saveSubmissionDraft(participant.id, award.id, obligation.id, { draftId: draft.id, revision: draft.revision, summary: "Concurrency protected first content" }), saveSubmissionDraft(participant.id, award.id, obligation.id, { draftId: draft.id, revision: draft.revision, summary: "Concurrency protected second content" })]);
    assert.equal(races.filter((result) => result.status === "fulfilled").length, 1);
    await assert.rejects(() => submitSubmission(participant.id, award.id, draft.id, { revision: draft.revision, confirmed: true }), /EXECUTION_REVISION_CONFLICT/);
    const personal = await getPersonalAward(participant.id, award.id); const saved = personal.obligations[0].submissions[0];
    await submitSubmission(participant.id, award.id, saved.id, { revision: saved.revision, confirmed: true });
    const listSummary = (await listCallExecution(access, program.id, call.id)).applications.find((entry) => entry.id === selected.id)!.award!;
    assert.deepEqual(Object.keys(listSummary.obligations[0].submissions[0]).sort(), ["reviewStatus", "status"]);
    await assert.rejects(() => saveSubmissionDraft(participant.id, award.id, obligation.id, { revision: 0, summary: "Unrequested new version" }), /AWARD_NEW_REVISION_NOT_ALLOWED/);
    await assert.rejects(() => db.awardSubmission.update({ where: { id: saved.id }, data: { summary: "Overwrite submitted content" } }), /AWARD_SUBMISSION_FROZEN/);
    await assert.rejects(() => updateObligation(access, award.id, obligation.id, { revision: obligation.revision, type: "OTHER", title: "Changed meaning", dueAt: null }), /AWARD_OBLIGATION_FROZEN/);
  });
  await context.test("rescheduling is explicit and immutable shared feedback leads to a new submitted revision", async () => {
    await assert.rejects(() => db.awardObligation.update({ where: { id: obligation.id }, data: { dueAt: new Date("2026-10-20T00:00:00Z") } }), /AWARD_DEADLINE_HISTORY_REQUIRED/);
    award = await rescheduleObligation(access, award.id, obligation.id, { revision: obligation.revision, dueAt: "2026-10-20", reason: "Institution extended the reporting period" }); obligation = award.obligations[0];
    assert.equal(obligation.dueDateHistory[0].oldDueAt, "2026-10-15"); assert.equal(obligation.dueDateHistory[0].newDueAt, "2026-10-20");
    const first = obligation.submissions[0];
    await assert.rejects(() => reviewSubmission(viewerAccess, award.id, first.id, { decision: "APPROVED" }), /ROLE_FORBIDDEN/);
    const races = await Promise.allSettled([reviewSubmission(analystAccess, award.id, first.id, { decision: "CHANGES_REQUESTED", feedback: "Include the technical validation evidence", internalNote: "PRIVATE_REVIEW_NOTE" }), reviewSubmission(analystAccess, award.id, first.id, { decision: "CHANGES_REQUESTED", feedback: "Include the technical validation evidence", internalNote: "PRIVATE_REVIEW_NOTE" })]);
    assert.equal(races.filter((result) => result.status === "fulfilled").length, 1);
    await assert.rejects(() => reviewSubmission(access, award.id, first.id, { decision: "APPROVED" }), /AWARD_REVIEW_FROZEN/);
    const shared = await getPersonalAward(participant.id, award.id);
    assert.equal(shared.obligations[0].submissions[0].feedback, "Include the technical validation evidence");
    assert.equal(JSON.stringify(shared).includes("PRIVATE_REVIEW_NOTE"), false); assert.equal(JSON.stringify(shared).includes("PRIVATE_SELECTION_NOTE"), false);
    assert.equal("internalNotes" in shared, false);
    const revisionTwo = await saveSubmissionDraft(participant.id, award.id, obligation.id, { revision: 0, summary: "Revised technical report with authoritative evidence", evidence: [{ label: "Validation report", url: "https://example.test/report" }] });
    assert.equal(revisionTwo.version, 2);
    await submitSubmission(participant.id, award.id, revisionTwo.id, { revision: revisionTwo.revision, confirmed: true });
    award = await reviewSubmission(analystAccess, award.id, revisionTwo.id, { decision: "APPROVED", feedback: "Technical report approved" }); obligation = award.obligations[0];
    assert.equal(obligation.submissions.length, 2); assert.equal(obligation.submissions[1].reviewStatus, "CHANGES_REQUESTED");
    assert.equal(obligation.state, "APPROVED");
    await assert.rejects(() => saveSubmissionDraft(participant.id, award.id, obligation.id, { revision: 0, summary: "Overwrite approval" }), /AWARD_NEW_REVISION_NOT_ALLOWED/);
    await assert.rejects(() => waiveObligation(access, award.id, obligation.id, { revision: obligation.revision, reason: "Already resolved" }), /AWARD_OBLIGATION_RESOLVED/);
    await assert.rejects(() => db.awardSubmissionEvidence.updateMany({ where: { submissionId: revisionTwo.id }, data: { label: "Overwrite evidence" } }), /AWARD_SUBMISSION_FROZEN/);
  });
  await context.test("required work blocks normal completion while explicit waiver preserves meaning", async () => {
    award = await createObligation(access, award.id, { type: "FINAL_REPORT", title: "Required final report", dueAt: "2026-12-01" });
    const final = award.obligations.find((entry) => entry.title === "Required final report")!;
    await assert.rejects(() => transitionAward(access, award.id, { revision: award.revision, status: "COMPLETED" }), /AWARD_REQUIRED_OBLIGATIONS_UNRESOLVED/);
    await assert.rejects(() => waiveObligation(access, award.id, final.id, { revision: final.revision, reason: "" }));
    const preservedDraft = await saveSubmissionDraft(participant.id, award.id, final.id, { revision: 0, summary: "Preserved private draft before institutional waiver" });
    award = await waiveObligation(access, award.id, final.id, { revision: final.revision, reason: "Equivalent authoritative reporting already received" });
    assert.equal(award.obligations.find((entry) => entry.id === final.id)?.state, "WAIVED");
    assert.equal((await db.awardSubmission.findUniqueOrThrow({ where: { id: preservedDraft.id } })).summary, preservedDraft.summary);
    await assert.rejects(() => submitSubmission(participant.id, award.id, preservedDraft.id, { revision: preservedDraft.revision, confirmed: true }), /AWARD_OBLIGATION_RESOLVED/);
  });
  await context.test("documents and financial execution are shared deliberately and paid records preserve actor and value", async () => {
    award = await createAwardDocument(access, award.id, { type: "AGREEMENT", title: "Shared support agreement", url: "https://example.test/agreement", visibleToParticipant: true });
    award = await createAwardDocument(access, award.id, { type: "TECHNICAL", title: "PRIVATE_INSTITUTION_DOCUMENT", url: "https://example.test/internal", visibleToParticipant: false });
    assert.equal((await getPersonalAward(member.id, award.id)).documents.length, 1);
    assert.equal(JSON.stringify(await getPersonalAward(participant.id, award.id)).includes("PRIVATE_INSTITUTION_DOCUMENT"), false);
    award = await createDisbursement(access, award.id, { label: "First support parcel", amount: "100.25", plannedFor: "2026-10-06" });
    const parcel = award.disbursements[0];
    await assert.rejects(() => updateDisbursement(otherAccess, award.id, parcel.id, { revision: parcel.revision, label: parcel.label, amount: parcel.amount, status: "PAID", paidAt: "2026-10-06" }), /AWARD_NOT_FOUND/);
    award = await updateDisbursement(access, award.id, parcel.id, { revision: parcel.revision, label: parcel.label, amount: parcel.amount, status: "PAID", paidAt: "2026-10-06", externalReference: "OFFICIAL-100" });
    assert.equal(award.disbursements[0].paidBy?.id, manager.id); assert.ok(award.disbursements[0].paidRecordedAt); assert.equal(award.financial.paid, "100.25");
    await assert.rejects(() => db.awardDisbursement.update({ where: { id: parcel.id }, data: { amount: "200" } }), /AWARD_DISBURSEMENT_FROZEN/);
    award = await createDisbursement(access, award.id, { label: "Cancelled parcel", amount: "50" });
    const cancel = award.disbursements.find((entry) => entry.label === "Cancelled parcel")!;
    await updateDisbursement(access, award.id, cancel.id, { revision: cancel.revision, label: cancel.label, amount: cancel.amount, status: "CANCELLED" });
    await assert.rejects(() => db.awardDisbursement.update({ where: { id: cancel.id }, data: { status: "PAID", paidAt: new Date("2026-10-06"), paidByUserId: manager.id, paidRecordedAt: new Date() } }), /AWARD_DISBURSEMENT_FROZEN/);
  });
  await context.test("terminal lifecycle is irreversible and current participation and organization membership govern operations", async () => {
    award = await transitionAward(access, award.id, { revision: award.revision, status: "COMPLETED" }); assert.ok(award.completedAt);
    await assert.rejects(() => transitionAward(access, award.id, { revision: award.revision, status: "ACTIVE", confirmed: true }), /AWARD_STATUS_TRANSITION_INVALID/);
    await assert.rejects(() => db.award.update({ where: { id: award.id }, data: { status: "ACTIVE", completedAt: null } }), /AWARD_TERMINAL/);
    const cancelling = await createAward(access, program.id, call.id, { applicationId: cancellation.id });
    const cancelled = await transitionAward(access, cancelling.id, { revision: cancelling.revision, status: "CANCELLED", reason: "Support instrument did not proceed" }); assert.equal(cancelled.status, "CANCELLED");
    let ending = await createAward(access, program.id, call.id, { applicationId: termination.id, startsAt: "2026-10-06" });
    ending = await transitionAward(access, ending.id, { revision: ending.revision, status: "ACTIVE", confirmed: true });
    ending = await transitionAward(access, ending.id, { revision: ending.revision, status: "TERMINATED", reason: "Execution concluded before the planned period" }); assert.ok(ending.terminatedAt);
    await db.projectMembership.updateMany({ where: { projectId: selected.projectId, userId: member.id, leftAt: null }, data: { leftAt: new Date() } });
    await assert.rejects(() => getPersonalAward(member.id, award.id), /AWARD_NOT_FOUND/);
    await db.organizationMembership.update({ where: { id: memberships[0].id }, data: { status: "DISABLED" } });
    await assert.rejects(() => getInstitutionAward(access, award.id), /MEMBERSHIP_DISABLED/);
    await db.organizationMembership.update({ where: { id: memberships[0].id }, data: { status: "ACTIVE" } });
    await db.organization.update({ where: { id: org.id }, data: { status: "INACTIVE" } });
    await assert.rejects(() => getPersonalAward(participant.id, award.id), /AWARD_NOT_FOUND/);
    await assert.rejects(() => getInstitutionAward(access, award.id), /ORGANIZATION_INACTIVE/);
    await db.organization.update({ where: { id: org.id }, data: { status: "ACTIVE" } });
  });
});
