import { z } from "zod";
import { dateOnlySchema, safeProfileUrlSchema } from "@/lib/profiles/schemas";

const text = (max: number) => z.string().trim().min(2, "Informe ao menos dois caracteres.").max(max, `Use até ${max} caracteres.`);
const optionalText = (max: number) => z.string().trim().max(max).nullable().optional().transform((value) => value || null);
const optionalDate = dateOnlySchema.nullable().optional().transform((value) => value ?? null);
const money = z.string().trim().regex(/^\d{1,12}(\.\d{1,2})?$/, "Informe um valor positivo com até duas casas decimais.");
const optionalMoney = money.nullable().optional().transform((value) => value ?? null);
const revision = z.number().int().min(1);
const termFields = { agreementNumber: optionalText(120), approvedAmount: optionalMoney, counterpartAmount: optionalMoney, signedAt: optionalDate, startsAt: optionalDate, endsAt: optionalDate };
const validPeriod = (input: { startsAt?: string | null; endsAt?: string | null }) => !input.startsAt || !input.endsAt || input.endsAt >= input.startsAt;
export const awardStatusSchema = z.enum(["PREPARING", "ACTIVE", "SUSPENDED", "COMPLETED", "TERMINATED", "CANCELLED"]);
export const createAwardSchema = z.object({ applicationId: z.string().cuid(), ...termFields }).strict().refine(validPeriod, { path: ["endsAt"], message: "A data final deve ser igual ou posterior à inicial." });
export const updateAwardSchema = z.object({ revision, ...termFields }).strict().refine(validPeriod, { path: ["endsAt"], message: "A data final deve ser igual ou posterior à inicial." });
export const transitionAwardSchema = z.object({ revision, status: awardStatusSchema, reason: optionalText(2000), confirmed: z.boolean().optional() }).strict().superRefine((input, ctx) => {
  if (["TERMINATED", "CANCELLED", "SUSPENDED"].includes(input.status) && !input.reason) ctx.addIssue({ code: "custom", path: ["reason"], message: "Explique o motivo desta mudança." });
  if (input.status === "ACTIVE" && input.confirmed !== true) ctx.addIssue({ code: "custom", path: ["confirmed"], message: "Confirme o início da execução." });
});
export const obligationTypeSchema = z.enum(["DELIVERABLE", "PROGRESS_REPORT", "FINAL_REPORT", "FINANCIAL_REPORT", "OTHER"]);
const obligationFields = { type: obligationTypeSchema, title: text(200), description: optionalText(6000), periodStartsAt: optionalDate, periodEndsAt: optionalDate, dueAt: optionalDate, position: z.number().int().min(0).max(199).default(0), required: z.boolean().default(true) };
const validObligationPeriod = (input: { periodStartsAt: string | null; periodEndsAt: string | null }) => !input.periodStartsAt || !input.periodEndsAt || input.periodEndsAt >= input.periodStartsAt;
export const createObligationSchema = z.object(obligationFields).strict().refine(validObligationPeriod, { path: ["periodEndsAt"], message: "O fim do período deve ser igual ou posterior ao início." });
export const updateObligationSchema = z.object({ revision, ...obligationFields }).strict().refine(validObligationPeriod, { path: ["periodEndsAt"], message: "O fim do período deve ser igual ou posterior ao início." });
export const rescheduleObligationSchema = z.object({ revision, dueAt: optionalDate, reason: text(2000) }).strict();
export const waiveObligationSchema = z.object({ revision, reason: text(2000) }).strict();
export const submissionEvidenceSchema = z.object({ label: text(160), url: safeProfileUrlSchema }).strict();
export const saveSubmissionSchema = z.object({ draftId: z.string().cuid().optional(), revision: z.number().int().min(0), summary: z.string().trim().max(6000), details: optionalText(20000), evidence: z.array(submissionEvidenceSchema).max(20, "Use até 20 evidências.").default([]) }).strict();
export const submitSubmissionSchema = z.object({ revision, confirmed: z.literal(true, { errorMap: () => ({ message: "Confirme o envio definitivo desta versão." }) }) }).strict();
export const reviewSubmissionSchema = z.object({ decision: z.enum(["APPROVED", "CHANGES_REQUESTED", "REJECTED"]), feedback: optionalText(6000), internalNote: optionalText(6000) }).strict().refine((input) => input.decision === "APPROVED" || Boolean(input.feedback), { path: ["feedback"], message: "Informe a orientação que será compartilhada com o participante." });
const disbursementFields = { label: text(200), amount: money.refine((value) => Number(value) > 0, "Informe um valor maior que zero."), plannedFor: optionalDate, externalReference: optionalText(200), note: optionalText(4000) };
export const createDisbursementSchema = z.object(disbursementFields).strict();
export const updateDisbursementSchema = z.object({ revision, ...disbursementFields, status: z.enum(["PLANNED", "PAID", "CANCELLED"]), paidAt: optionalDate }).strict().refine((input) => input.status !== "PAID" || Boolean(input.paidAt), { path: ["paidAt"], message: "Informe a data do desembolso realizado." });
export const createAwardDocumentSchema = z.object({ type: z.enum(["AGREEMENT", "AMENDMENT", "TECHNICAL", "FINANCIAL", "OTHER"]), title: text(200), url: safeProfileUrlSchema, visibleToParticipant: z.boolean().default(false) }).strict();
export type CreateAwardInput = z.input<typeof createAwardSchema>;
export type UpdateAwardInput = z.input<typeof updateAwardSchema>;
export type TransitionAwardInput = z.input<typeof transitionAwardSchema>;
export type CreateObligationInput = z.input<typeof createObligationSchema>;
export type UpdateObligationInput = z.input<typeof updateObligationSchema>;
export type SaveSubmissionInput = z.input<typeof saveSubmissionSchema>;
export type ReviewSubmissionInput = z.input<typeof reviewSubmissionSchema>;
