import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs, PageHeader, Panel, StatusBadge } from "@/components/ui";
import { DiscussionActions } from "@/components/communication/discussion-actions";
import { MessageComposer, RefreshCommunication } from "@/components/communication/actions";
import { requireAuthenticatedSession } from "@/lib/auth/session";
import { getProjectDiscussion } from "@/lib/communication/discussions";
import { communicationDate, communicationTime } from "@/lib/communication/presentation";
import { ResourceNotFoundError } from "@/lib/errors";

export default async function DiscussionPage({ params, searchParams }: { params: Promise<{ projectId: string; discussionId: string }>; searchParams: Promise<{ before?: string }> }) {
  const { user } = await requireAuthenticatedSession(); const { projectId, discussionId } = await params; const query = await searchParams;
  const discussion = await getProjectDiscussion(user.id, projectId, discussionId, query.before).catch((error: unknown) => { if (error instanceof ResourceNotFoundError) notFound(); throw error; });
  const href = `/app/personal/projects/${projectId}/discussions/${discussionId}`;
  return <div className="min-w-0 space-y-6"><PageHeader title={discussion.title} description={`${discussion.projectName} · Discussão entre colaboradores`} breadcrumbs={<Breadcrumbs items={[{ label: "Projetos", href: "/app/personal/projects" }, { label: discussion.projectName, href: `/app/personal/projects/${projectId}` }, { label: "Discussões", href: `/app/personal/projects/${projectId}/discussions` }, { label: "Discussão" }]} />} action={<RefreshCommunication />} /><div className="flex flex-wrap items-start justify-between gap-3"><StatusBadge label={discussion.status === "OPEN" ? "Aberta" : "Encerrada"} tone={discussion.status === "OPEN" ? "success" : "neutral"} /><DiscussionActions projectId={projectId} discussionId={discussionId} subscribed={discussion.subscribed} status={discussion.status} canManage={discussion.canManage} canSubscribe={discussion.canSubscribe} /></div><Panel className="p-4 sm:p-6">{discussion.olderCursor ? <Link className="button-secondary mb-5" href={`${href}?before=${discussion.olderCursor}`}>Mensagens anteriores</Link> : null}{query.before ? <Link className="button-secondary mb-5 ml-2" href={href}>Mensagens recentes</Link> : null}<ol className="space-y-5" aria-label="Mensagens da discussão">{discussion.messages.map((message) => <li key={message.id}><article className="border-l-2 border-line pl-4"><header className="flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-slate"><span className="break-words font-medium text-ink">{message.authorUserId === user.id ? "Você" : message.authorName}</span><time dateTime={message.createdAt}>{communicationDate(message.createdAt)} · {communicationTime(message.createdAt)}</time></header><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-7">{message.body ?? "Mensagem removida."}</p></article></li>)}</ol><div className="mt-6">{discussion.canReply ? <MessageComposer endpoint={`/api/personal/projects/${projectId}/discussions/${discussionId}/messages`} label="Resposta" /> : <p className="border-t border-line pt-5 text-sm leading-7 text-slate">Esta discussão está disponível para consulta e não recebe novas respostas neste momento.</p>}</div></Panel></div>;
}
