import { notFound } from "next/navigation";
import { ArrowUpRight } from "lucide-react";
import { Breadcrumbs, PageHeader, Panel, PanelHeader, StatusBadge } from "@/components/ui";
import { CreateApplication } from "@/components/personal/application-actions";
import { requireAuthenticatedSession } from "@/lib/auth/session";
import { getPersonalOpportunity } from "@/lib/selection/service";
import { listProjects, listTeams } from "@/lib/participants/service";
import { formatMonitoringDate } from "@/lib/monitoring/format";

export default async function PersonalOpportunity({ params }: { params: Promise<{ callId: string }> }) {
  const { callId } = await params; const { user } = await requireAuthenticatedSession(); const [call, projects, teams] = await Promise.all([getPersonalOpportunity(user.id, callId), listProjects(user.id), listTeams(user.id)]); if (!call) notFound();
  return <div className="min-w-0 space-y-6"><PageHeader title={call.title} description={`${call.institution} · ${call.callNumber}`} breadcrumbs={<Breadcrumbs items={[{ label: "Oportunidades", href: "/app/personal/opportunities" }, { label: "Edital" }]} />} /><StatusBadge label={call.canApply ? "Candidaturas abertas no Innove" : "Consulte a situação do edital"} tone={call.canApply ? "success" : "neutral"} /><Panel className="p-5"><h2 className="font-semibold">Sobre o edital</h2>{call.objective ? <p className="mt-3 whitespace-pre-wrap break-words text-sm leading-7 text-slate">{call.objective}</p> : <p className="mt-3 text-sm text-slate">Consulte os documentos e a publicação oficial para conferir as regras de participação.</p>}<dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-xs text-slate">Abertura das inscrições</dt><dd className="mt-1">{formatMonitoringDate(call.applicationStartsAt)}</dd></div><div><dt className="text-xs text-slate">Encerramento das inscrições</dt><dd className="mt-1">{formatMonitoringDate(call.applicationEndsAt)}</dd></div></dl>{call.sourceUrl ? <a className="button-secondary mt-5" href={call.sourceUrl} target="_blank" rel="noopener noreferrer">Abrir publicação oficial<ArrowUpRight size={16} aria-hidden="true" /></a> : null}</Panel>{call.documents.length ? <Panel><PanelHeader title="Documentos" /><ul className="divide-y divide-line">{call.documents.map((document) => <li key={document.id}><a className="flex min-h-14 items-center justify-between gap-3 px-5 py-4 text-sm font-medium hover:bg-surface-subtle" href={document.externalUrl} target="_blank" rel="noopener noreferrer"><span className="break-words">{document.title}</span><ArrowUpRight size={16} className="shrink-0" aria-hidden="true" /></a></li>)}</ul></Panel> : null}<Panel className="p-5"><h2 className="mb-2 font-semibold">Sua participação</h2><p className="mb-5 text-sm leading-6 text-slate">Escolha um projeto existente. A candidatura será criada como rascunho para revisão antes do envio.</p><CreateApplication callId={callId} projects={projects} teams={teams} canApply={call.canApply} /></Panel></div>;
}
