"use client";

import Link from "next/link";
import { Search } from "lucide-react";
import { useMemo, useState } from "react";
import { Panel, PanelHeader, StatusBadge } from "@/components/ui";
import { applicationStatusLabels, auditDateLabel, decisionLabels, scoreLabel, type SelectionApplication } from "@/components/selection/types";

export function ApplicationsList({ applications, baseHref, evaluation = false, canEvaluate = false }: { applications: SelectionApplication[]; baseHref: string; evaluation?: boolean; canEvaluate?: boolean }) {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("");
  const [decision, setDecision] = useState("");
  const filtered = useMemo(() => applications.filter((application) => (!status || application.status === status) && (!decision || application.decision === decision) && `${application.projectNameSnapshot} ${application.teamNameSnapshot ?? ""} ${application.submittedBy.name}`.toLocaleLowerCase("pt-BR").includes(query.trim().toLocaleLowerCase("pt-BR"))), [applications, query, status, decision]);
  const filtering = Boolean(query || status || decision);
  function canEvaluateApplication(application: SelectionApplication) { return evaluation && canEvaluate && ["SUBMITTED", "IN_REVIEW"].includes(application.status); }

  return <Panel>
    <PanelHeader title={evaluation ? "Candidaturas para avaliação" : "Candidaturas recebidas"} description={evaluation ? "Somente avaliações enviadas contribuem para a nota agregada do edital." : "O conteúdo enviado é preservado, mesmo quando o projeto ou a equipe mudam."} />
    {applications.length ? <div className="grid gap-3 border-b border-line p-4 sm:px-6 lg:grid-cols-[minmax(14rem,1fr)_12rem_13rem]">
      <label className="block space-y-2 text-xs font-medium text-slate"><span>Buscar projeto, equipe ou participante</span><span className="relative block"><Search size={17} aria-hidden="true" className="pointer-events-none absolute left-3 top-3.5" /><input className="field-control pl-10" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Nome do projeto ou participante" type="search" /></span></label>
      <label className="block space-y-2 text-xs font-medium text-slate"><span>Status</span><select className="field-control" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Todos</option>{Object.entries(applicationStatusLabels).filter(([value]) => value !== "DRAFT").map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
      <label className="block space-y-2 text-xs font-medium text-slate"><span>Decisão</span><select className="field-control" value={decision} onChange={(event) => setDecision(event.target.value)}><option value="">Todas</option>{Object.entries(decisionLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
    </div> : null}
    {applications.length ? <div className="flex flex-wrap items-center justify-between gap-3 border-b border-line px-4 py-3 text-sm text-slate sm:px-6"><p role="status">{filtered.length} {filtered.length === 1 ? "candidatura" : "candidaturas"}</p>{filtering ? <button type="button" className="min-h-11 font-medium text-accent-hover" onClick={() => { setQuery(""); setStatus(""); setDecision(""); }}>Limpar filtros</button> : null}</div> : null}
    {filtered.length ? <>
      <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[48rem] text-left text-sm"><caption className="sr-only">{evaluation ? "Avaliação das candidaturas" : "Candidaturas do edital"}</caption><thead className="bg-surface-subtle text-xs text-slate"><tr>{["Projeto / equipe", "Participante / envio", "Status", "Decisão", "Avaliações", ""].map((label, index) => <th scope="col" key={index} className="px-5 py-3 font-medium">{label || <span className="sr-only">Ação</span>}</th>)}</tr></thead><tbody className="divide-y divide-line">{filtered.map((application) => <tr key={application.id}><td className="max-w-[20rem] px-5 py-4"><Link className="break-words font-medium text-ink hover:text-accent-hover" href={`${baseHref}/${application.id}`}>{application.projectNameSnapshot}</Link><p className="mt-1 break-words text-xs text-slate">{application.teamNameSnapshot ?? "Participação individual"}</p></td><td className="px-5 py-4"><p>{application.submittedBy.name}</p><p className="mt-1 text-xs text-slate">{auditDateLabel(application.submittedAt)}</p></td><td className="px-5 py-4"><StatusBadge label={applicationStatusLabels[application.status] ?? application.status} tone={application.status === "WITHDRAWN" ? "neutral" : "accent"} /></td><td className="px-5 py-4 text-slate">{decisionLabels[application.decision] ?? application.decision}</td><td className="px-5 py-4"><p className="tabular-nums">{scoreLabel(application.score)}{application.score !== null ? " / 100" : ""}</p><p className="mt-1 text-xs text-slate">{application.evaluationCount} enviada(s)</p></td><td className="px-5 py-4"><Link className="button-secondary whitespace-nowrap" href={`${baseHref}/${application.id}${canEvaluateApplication(application) ? "#evaluation" : ""}`}>{canEvaluateApplication(application) ? "Avaliar" : "Abrir"}</Link></td></tr>)}</tbody></table></div>
      <ul className="divide-y divide-line md:hidden">{filtered.map((application) => <li key={application.id} className="space-y-4 p-4"><div><Link className="break-words font-medium text-ink hover:text-accent-hover" href={`${baseHref}/${application.id}`}>{application.projectNameSnapshot}</Link><p className="mt-1 break-words text-sm text-slate">{application.teamNameSnapshot ?? "Participação individual"}</p></div><div className="flex flex-wrap gap-2"><StatusBadge label={applicationStatusLabels[application.status] ?? application.status} tone="accent" /><StatusBadge label={decisionLabels[application.decision] ?? application.decision} tone={application.decision === "SELECTED" ? "success" : "neutral"} /></div><dl className="grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs text-slate">Participante</dt><dd className="mt-1 break-words">{application.submittedBy.name}</dd></div><div><dt className="text-xs text-slate">Nota agregada</dt><dd className="mt-1 tabular-nums">{scoreLabel(application.score)}<p className="text-xs text-slate">{application.evaluationCount} avaliação(ões) enviada(s)</p></dd></div><div className="col-span-2"><dt className="text-xs text-slate">Envio · horário de Brasília</dt><dd className="mt-1">{auditDateLabel(application.submittedAt)}</dd></div></dl><Link className="button-secondary w-full" href={`${baseHref}/${application.id}${canEvaluateApplication(application) ? "#evaluation" : ""}`}>{canEvaluateApplication(application) ? "Avaliar candidatura" : "Abrir candidatura"}</Link></li>)}</ul>
    </> : <div className="px-5 py-9 sm:px-6"><h3 className="font-medium text-ink">{filtering ? "Nenhuma candidatura corresponde aos filtros" : "As candidaturas aparecerão aqui"}</h3><p className="mt-2 max-w-xl text-sm leading-6 text-slate">{filtering ? "Altere a busca ou remova os filtros para consultar os demais registros." : "Quando um participante enviar uma candidatura, a instituição poderá consultar o conteúdo enviado e acompanhar a seleção neste edital."}</p></div>}
  </Panel>;
}
