import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs, PageHeader, Panel } from "@/components/ui";
import { ConversationRead, MessageComposer, RefreshCommunication } from "@/components/communication/actions";
import { ReportContact } from "@/components/communication/safety-report";
import { BlockContact } from "@/components/network/person-actions";
import { requireAuthenticatedSession } from "@/lib/auth/session";
import { getConversation } from "@/lib/communication/messages";
import { communicationDate, communicationTime } from "@/lib/communication/presentation";
import { ResourceNotFoundError } from "@/lib/errors";

export default async function ConversationPage({ params, searchParams }: { params: Promise<{ conversationId: string }>; searchParams: Promise<{ before?: string }> }) {
  const { user } = await requireAuthenticatedSession(); const { conversationId } = await params; const query = await searchParams;
  const conversation = await getConversation(user.id, conversationId, query.before).catch((error: unknown) => { if (error instanceof ResourceNotFoundError) notFound(); throw error; });
  return <div className="min-w-0 space-y-6"><PageHeader title={conversation.person.fullName} description={conversation.person.headline ?? "Conversa privada de colaboração"} breadcrumbs={<Breadcrumbs items={[{ label: "Mensagens", href: "/app/messages" }, { label: "Conversa" }]} />} action={<RefreshCommunication />} /><div className="flex flex-wrap items-center gap-2">{conversation.person.handle ? <Link className="button-secondary" href={`/app/personal/network/people/${conversation.person.handle}`}>Ver perfil</Link> : null}<BlockContact userId={conversation.person.userId} /><ReportContact reportedUserId={conversation.person.userId} conversationId={conversationId} /></div><ConversationRead conversationId={conversationId} lastMessageId={conversation.messages.at(-1)?.id} /><Panel className="p-4 sm:p-6">{conversation.olderCursor ? <Link className="button-secondary mb-5" href={`/app/messages/${conversationId}?before=${conversation.olderCursor}`}>Mensagens anteriores</Link> : null}{query.before ? <Link className="button-secondary mb-5 ml-2" href={`/app/messages/${conversationId}`}>Mensagens recentes</Link> : null}<ol className="space-y-5" aria-label="Mensagens da conversa">{conversation.messages.map((message, index) => { const date = communicationDate(message.createdAt); const previousDate = index ? communicationDate(conversation.messages[index - 1].createdAt) : null; return <li key={message.id}>{date !== previousDate ? <p className="mb-4 border-b border-line pb-2 text-xs font-medium text-slate">{date}</p> : null}<article className={`border-l-2 pl-4 ${message.senderUserId === user.id ? "border-accent" : "border-line"}`}><header className="flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-slate"><span className="break-words font-medium text-ink">{message.senderUserId === user.id ? "Você" : conversation.person.fullName}</span><time dateTime={message.createdAt}>{communicationTime(message.createdAt)}</time></header><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-7">{message.body ?? "Mensagem removida."}</p>{message.senderUserId !== user.id ? <ReportContact reportedUserId={conversation.person.userId} conversationId={conversationId} messageId={message.id} /> : null}</article></li>; })}</ol>{!conversation.messages.length ? <p className="pb-6 text-sm leading-7 text-slate">Use esta conversa para combinar uma colaboração.</p> : null}<div className="mt-6">{conversation.canSend ? <MessageComposer endpoint={`/api/messages/${conversationId}/messages`} /> : <p className="border-t border-line pt-5 text-sm leading-7 text-slate">O histórico está preservado. Uma conexão ativa é necessária para enviar novas mensagens.</p>}</div></Panel></div>;
}
