import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs, PageHeader, Panel, PanelHeader } from "@/components/ui";
import { SubmissionHistory } from "@/components/execution/award-detail";
import { SubmissionEditor } from "@/components/execution/submission-editor";
import { requireAuthenticatedSession } from "@/lib/auth/session";
import { getPersonalAward } from "@/lib/awards/service";
import { ResourceNotFoundError } from "@/lib/errors";
import { formatMonitoringDate } from "@/lib/monitoring/format";

export default async function PersonalSubmissionPage({ params }: { params: Promise<{ awardId: string; obligationId: string }> }) { const { user } = await requireAuthenticatedSession(); const { awardId, obligationId } = await params; const award = await getPersonalAward(user.id, awardId).catch((error: unknown) => { if (error instanceof ResourceNotFoundError) notFound(); throw error; }); const obligation = award.obligations.find((entry) => entry.id === obligationId); if (!obligation || !award.canManage) notFound(); const latest = obligation.submissions[0]; const draft = latest?.status === "DRAFT" ? latest : null; const canAuthor = award.status === "ACTIVE" && !obligation.waivedAt && (!latest || latest.status === "DRAFT" || latest.reviewStatus === "CHANGES_REQUESTED"); const prior = obligation.submissions.filter((entry) => entry.status === "SUBMITTED"); const previousFeedback = prior[0]?.reviewStatus === "CHANGES_REQUESTED" ? prior[0].feedback : null; const detailHref = `/app/personal/awards/${awardId}`; return <div className="min-w-0 space-y-6"><PageHeader title={obligation.title} description={`${award.application.projectNameSnapshot} · ${award.fundingCall.fundingProgram.name}`} breadcrumbs={<Breadcrumbs items={[{ label: "Meus programas", href: "/app/personal/programs" }, { label: "Execução do apoio", href: detailHref }, { label: "Preparar entrega" }]} />} /><section className="space-y-2 border-b border-line pb-5"><p className="text-sm leading-6 text-slate">Prazo: {formatMonitoringDate(obligation.dueAt)} · {obligation.deadline.label}</p>{obligation.description ? <p className="whitespace-pre-wrap break-words text-sm leading-7 text-slate">{obligation.description}</p> : null}</section>{canAuthor ? <SubmissionEditor key={obligation.id} awardId={awardId} obligationId={obligationId} title={obligation.title} draft={draft} nextVersion={(latest?.version ?? 0) + (draft ? 0 : 1)} previousFeedback={previousFeedback} /> : <p className="border-l-2 border-warning pl-4 text-sm leading-7 text-slate">{award.status !== "ACTIVE" ? "A execução precisa estar ativa para preparar ou enviar uma entrega." : obligation.waivedAt ? "Esta obrigação foi dispensada pela instituição." : "Esta entrega já foi enviada. Uma nova versão pode ser preparada após uma solicitação de ajustes."}</p>}{prior.length ? <Panel><PanelHeader title="Versões anteriores" description="Os envios e pareceres anteriores permanecem preservados." /><div className="px-4 pb-5 sm:px-6"><SubmissionHistory submissions={prior} /></div></Panel> : null}<Link className="button-secondary" href={detailHref}>Voltar à execução do apoio</Link></div>; }
