import { ArrowUpRight } from "lucide-react";
import { Panel, PanelHeader, StatusBadge } from "@/components/ui";
import { deadlineLabel, supportTypeLabels, territoryScopeLabels } from "@/lib/opportunities/presentation";
import { formatMonitoringDate } from "@/lib/monitoring/format";
import type { getPublicOpportunity } from "@/lib/opportunities/service";
export function OpportunityCallDetail({ call }: { call: NonNullable<Awaited<ReturnType<typeof getPublicOpportunity>>> }) {
  return <><StatusBadge label={deadlineLabel(call.status, call.applicationStartsAt, call.applicationEndsAt)} tone={call.canApply ? "success" : "neutral"} /><p className="text-xs text-slate">Dados publicados pela instituição no Innove · {call.fundingProgram.name}</p><section className="space-y-5 border-y border-line py-6"><h2 className="text-lg font-semibold">Sobre o edital</h2>{call.objective ? <p className="max-w-4xl whitespace-pre-wrap break-words text-sm leading-7 text-slate">{call.objective}</p> : <p className="text-sm text-slate">Consulte a fonte oficial para conhecer as regras.</p>}<dl className="grid gap-5 text-sm sm:grid-cols-2 lg:grid-cols-3"><Metadata label="Tipo de apoio" value={supportTypeLabels[call.supportType]} /><Metadata label="Abrangência" value={call.territoryLabel || territoryScopeLabels[call.territoryScope]} /><Metadata label="UFs informadas" value={call.eligibleStates.join(", ") || "Consulte o edital"} /><Metadata label="Abertura das inscrições" value={formatMonitoringDate(call.applicationStartsAt)} /><Metadata label="Encerramento das inscrições" value={formatMonitoringDate(call.applicationEndsAt)} /><Metadata label="Público" value={call.audienceTags.join(" · ") || "Consulte o edital"} />{call.thematicAreas.length ? <Metadata label="Áreas temáticas" value={call.thematicAreas.join(" · ")} /> : null}{call.maximumSupport ? <Metadata label="Apoio máximo por projeto" value={new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(call.maximumSupport))} /> : null}</dl>{call.sourceUrl ? <div><a className="button-secondary" href={call.sourceUrl} target="_blank" rel="noopener noreferrer">Fonte oficial externa<ArrowUpRight size={16} aria-hidden="true" /></a>{call.sourceCheckedAt ? <p className="mt-2 text-xs text-slate">Fonte consultada em {formatMonitoringDate(call.sourceCheckedAt)}</p> : null}</div> : null}</section>{call.documents.length ? <Panel><PanelHeader title="Documentos públicos" /><ul className="divide-y divide-line">{call.documents.map((document) => <li key={document.id}><a className="flex min-h-14 items-center justify-between gap-3 px-5 py-4 text-sm font-medium hover:bg-surface-subtle" href={document.externalUrl} target="_blank" rel="noopener noreferrer"><span className="break-words">{document.title}</span><ArrowUpRight size={16} className="shrink-0" aria-hidden="true" /></a></li>)}</ul></Panel> : null}<p className="text-xs leading-5 text-slate">Consulte o edital e a fonte oficial para confirmar regras e prazos.</p></>;
}
function Metadata({ label, value }: { label: string; value: string }) { return <div className="min-w-0"><dt className="text-xs text-slate">{label}</dt><dd className="mt-1 break-words">{value}</dd></div>; }
