"use client";
import { useState } from "react";
import { supportTypeLabels, territoryScopeLabels } from "@/lib/opportunities/presentation";
export type DiscoveryFieldValues = { publicListingEnabled: boolean; supportType: string; territoryScope: string; territoryLabel: string | null; eligibleStates: string[]; audienceTags: string[]; thematicAreas: string[] };
export function DiscoveryFields({ values }: { values?: DiscoveryFieldValues }) {
  const [publicListing, setPublicListing] = useState(values?.publicListingEnabled ?? false);
  return <><fieldset className="space-y-4"><legend className="mb-3 text-sm font-semibold">Apoio e território</legend><div className="grid gap-4 sm:grid-cols-2"><Select name="supportType" label="Tipo de apoio" options={supportTypeLabels} value={values?.supportType ?? "OTHER"} /><Select name="territoryScope" label="Abrangência" options={territoryScopeLabels} value={values?.territoryScope ?? "UNSPECIFIED"} /></div><Field name="territoryLabel" label="Descrição do território (opcional)" value={values?.territoryLabel} maxLength={120} /><Field name="eligibleStates" label="UFs contempladas (separadas por vírgula)" value={values?.eligibleStates.join(", ")} maxLength={110} /></fieldset><fieldset className="space-y-4 border-t border-line pt-4"><legend className="pr-2 text-sm font-semibold">Público e áreas temáticas</legend><Field name="audienceTags" label="Público (separe por vírgula)" value={values?.audienceTags.join(", ")} maxLength={1620} /><Field name="thematicAreas" label="Áreas temáticas (separe por vírgula)" value={values?.thematicAreas.join(", ")} maxLength={1620} /><p className="text-xs leading-5 text-slate">Até 20 temas por campo. Use os termos da publicação oficial; estas informações ajudam na descoberta e não substituem os critérios de elegibilidade.</p></fieldset><fieldset className="space-y-3 border-t border-line pt-4"><legend className="pr-2 text-sm font-semibold">Publicação</legend><label className="flex min-h-11 items-start gap-3 text-sm"><input className="mt-1 h-5 w-5 shrink-0" type="checkbox" name="publicListingEnabled" checked={publicListing} onChange={(event) => setPublicListing(event.target.checked)} /><span><span className="font-medium">Listar publicamente nas oportunidades</span><span className="mt-1 block leading-6 text-slate">Qualquer pessoa poderá visualizar os dados do edital. Candidaturas pela plataforma são configuradas separadamente.</span></span></label>{publicListing ? <label className="flex min-h-11 items-start gap-3 text-sm"><input className="mt-1 h-5 w-5 shrink-0" name="publicationConfirmed" type="checkbox" required /><span className="leading-6">Confirmo que os dados desta chamada podem ser publicados para qualquer pessoa.</span></label> : null}</fieldset></>;
}
export function readDiscoveryForm(values: FormData) {
  const list = (key: string) => String(values.get(key) ?? "").split(",").map((value) => value.trim()).filter(Boolean);
  return { publicListingEnabled: values.get("publicListingEnabled") === "on", publicationConfirmed: values.get("publicationConfirmed") === "on", supportType: values.get("supportType"), territoryScope: values.get("territoryScope"), territoryLabel: String(values.get("territoryLabel") ?? "").trim() || null, eligibleStates: list("eligibleStates"), audienceTags: list("audienceTags"), thematicAreas: list("thematicAreas") };
}
function Field({ name, label, value, maxLength }: { name: string; label: string; value?: string | null; maxLength: number }) { return <label className="block space-y-2 text-sm font-medium"><span>{label}</span><input className="field-control" name={name} defaultValue={value ?? ""} maxLength={maxLength} /></label>; }
function Select({ name, label, options, value }: { name: string; label: string; options: Record<string, string>; value: string }) { return <label className="block space-y-2 text-sm font-medium"><span>{label}</span><select className="field-control" name={name} defaultValue={value}>{Object.entries(options).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>; }
