"use client";
import { type FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { Pencil, Plus } from "lucide-react";
import { Dialog } from "@/components/dialog";
import { DiscoveryFields, readDiscoveryForm } from "@/components/opportunities/discovery-fields";
import type { InstitutionOpportunity } from "@/lib/opportunities/service";
import { opportunityStatusLabels } from "@/lib/opportunities/presentation";
export type ExternalEditorRecord = Omit<InstitutionOpportunity, "publishedAt" | "applicationEndsAt" | "sourceCheckedAt"> & { publishedAt: string | null; applicationEndsAt: string | null; sourceCheckedAt: string };
export function ExternalOpportunityEditor({ organizationId, record }: { organizationId: string; record?: ExternalEditorRecord }) {
  const [open, setOpen] = useState(false); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const router = useRouter();
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const values = new FormData(event.currentTarget); const text = (key: string) => String(values.get(key) ?? "").trim(); setPending(true); setError(null);
    try { const response = await fetch(`/api/organizations/${organizationId}/opportunities${record ? `/${record.id}` : ""}`, { method: record ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ institution: text("institution"), callNumber: text("callNumber"), title: text("title"), objective: text("objective"), territory: text("territory"), audience: text("audience") || null, status: text("status"), publishedAt: text("publishedAt") || null, applicationEndsAt: text("applicationEndsAt") || null, sourceUrl: text("sourceUrl"), sourceCheckedAt: text("sourceCheckedAt"), ...readDiscoveryForm(values) }) }); const payload = await response.json() as { error?: string; issues?: Record<string, string[]> }; if (!response.ok) { setError(Object.values(payload.issues ?? {}).flat().join(" ") || payload.error || "Não foi possível salvar a oportunidade."); return; } setOpen(false); router.refresh(); }
    catch { setError("Não foi possível conectar ao servidor."); } finally { setPending(false); }
  }
  return <><button type="button" className="button-secondary" onClick={() => { setError(null); setOpen(true); }}>{record ? <Pencil size={16} aria-hidden="true" /> : <Plus size={16} aria-hidden="true" />}{record ? "Editar" : "Registrar oportunidade"}</button><Dialog open={open} onClose={() => { if (!pending) setOpen(false); }} mode="sheet" title={record ? "Editar oportunidade externa" : "Registrar oportunidade externa"} description="Preserve o contexto da publicação e a referência à fonte oficial."><form onSubmit={submit} className="space-y-5"><fieldset className="space-y-4"><legend className="mb-3 text-sm font-semibold">Publicação original</legend><Field name="institution" label="Instituição responsável" value={record?.institution} required maxLength={200} /><Field name="title" label="Título" value={record?.title} required maxLength={200} /><Field name="callNumber" label="Número ou referência da chamada" value={record?.callNumber} required maxLength={80} /><label className="block space-y-2 text-sm font-medium"><span>Objetivo</span><textarea className="field-control" name="objective" defaultValue={record?.objective ?? ""} required minLength={2} maxLength={4000} rows={3} /></label><Field name="territory" label="Território conforme a fonte" value={record?.territory} required maxLength={300} /><Field name="audience" label="Público conforme a fonte (opcional)" value={record?.audience} maxLength={500} /><label className="block space-y-2 text-sm font-medium"><span>Situação</span><select name="status" className="field-control" defaultValue={record?.status ?? "OPEN"}>{Object.entries(opportunityStatusLabels).filter(([key]) => key !== "DRAFT").map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></fieldset><fieldset className="space-y-4 border-t border-line pt-4"><legend className="pr-2 text-sm font-semibold">Fonte e datas</legend><Field name="sourceUrl" label="Link da fonte oficial" value={record?.sourceUrl} required maxLength={2048} type="url" /><Field name="sourceCheckedAt" label="Data de consulta da fonte" value={record?.sourceCheckedAt.slice(0, 10)} type="date" required /><div className="grid gap-4 sm:grid-cols-2"><Field name="publishedAt" label="Publicação (opcional)" value={record?.publishedAt?.slice(0, 10)} type="date" /><Field name="applicationEndsAt" label="Encerramento (opcional)" value={record?.applicationEndsAt?.slice(0, 10)} type="date" /></div></fieldset><DiscoveryFields values={record} />{error ? <p role="alert" className="text-sm text-danger">{error}</p> : null}<button className="button-primary w-full" disabled={pending}>{pending ? "Salvando…" : "Salvar oportunidade"}</button></form></Dialog></>;
}
function Field({ name, label, value, required, maxLength, type = "text" }: { name: string; label: string; value?: string | null; required?: boolean; maxLength?: number; type?: string }) { return <label className="block space-y-2 text-sm font-medium"><span>{label}</span><input className="field-control" name={name} defaultValue={value ?? ""} required={required} maxLength={maxLength} type={type} /></label>; }
