import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { StatusBadge } from "@/components/ui";
import { SaveOpportunityButton } from "@/components/opportunities/save-button";
import { deadlineLabel, relevanceLabels, supportTypeLabels, territoryScopeLabels } from "@/lib/opportunities/presentation";
import { formatMonitoringDate } from "@/lib/monitoring/format";
import type { PersonalOpportunityDto } from "@/lib/opportunities/service";

export function OpportunityList({ opportunities, personal = false }: { opportunities: PersonalOpportunityDto[]; personal?: boolean }) {
  if (!opportunities.length) return <div className="border-y border-line py-10"><h2 className="text-lg font-semibold">Nenhuma oportunidade encontrada</h2><p className="mt-2 max-w-xl text-sm leading-6 text-slate">Altere os filtros ou volte depois. As chamadas aparecem aqui quando sua publicação é autorizada pela instituição.</p></div>;
  return <ul className="divide-y divide-line border-y border-line">{opportunities.map((entry) => <li key={`${entry.kind}-${entry.id}`} className="py-6"><article className="flex min-w-0 gap-3 sm:gap-5"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg border border-line bg-surface-subtle text-xs font-semibold text-slate" aria-hidden="true">{entry.institution.trim().split(/\s+/).slice(0, 2).map((word) => word[0]).join("")}</div><div className="min-w-0 flex-1"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><p className="text-xs leading-5 text-slate">{entry.institution} · {entry.callNumber}</p><h2 className="mt-1 break-words text-lg font-semibold tracking-tight">{entry.title}</h2></div><StatusBadge label={deadlineLabel(entry.status, entry.applicationStartsAt, entry.applicationEndsAt)} tone={entry.canApply ? "success" : "neutral"} /></div>{entry.objective ? <p className="mt-3 line-clamp-3 max-w-4xl whitespace-pre-wrap break-words text-sm leading-6 text-slate">{entry.objective}</p> : null}<p className="mt-3 text-xs leading-5 text-slate">{supportTypeLabels[entry.supportType]} · {entry.territoryLabel || entry.territory || territoryScopeLabels[entry.territoryScope]}{entry.eligibleStates.length ? ` · ${entry.eligibleStates.join(", ")}` : ""}</p>{entry.thematicAreas.length ? <p className="mt-2 break-words text-xs leading-5 text-slate">Áreas: {entry.thematicAreas.join(" · ")}</p> : null}<div className="mt-4 flex flex-wrap items-end justify-between gap-3"><p className="text-xs leading-5 text-slate">{entry.applicationEndsAt ? `Inscrições até ${formatMonitoringDate(entry.applicationEndsAt)}` : "Consulte o prazo na fonte oficial"}<span className="block">{entry.kind === "INTERNAL" ? "Dados publicados pela instituição no Innove" : "Fonte oficial externa"}</span></p><div className="flex flex-wrap gap-2">{personal ? <SaveOpportunityButton id={entry.id} kind={entry.kind} saved={entry.saved} /> : null}{entry.kind === "INTERNAL" ? <Link className={entry.canApply ? "button-primary" : "button-secondary"} href={personal ? `/app/personal/opportunities/${entry.id}` : `/opportunities/calls/${entry.id}`}>Ver edital<ArrowUpRight size={16} aria-hidden="true" /></Link> : entry.sourceUrl ? <a className="button-secondary" href={entry.sourceUrl} target="_blank" rel="noopener noreferrer">Fonte oficial<ArrowUpRight size={16} aria-hidden="true" /></a> : null}</div></div>{personal && entry.relevance ? <details className="mt-4 text-xs leading-5 text-slate"><summary className="min-h-11 cursor-pointer py-3 font-medium text-ink">{relevanceLabels[entry.relevance.level]} · Por quê?</summary><ul className="mt-2 list-disc space-y-1 pl-4">{entry.relevance.reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul><p className="mt-2">A relação temática e territorial não confirma elegibilidade.</p></details> : null}</div></article></li>)}</ul>;
}
