"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useId, useRef, useState, type FormEvent } from "react";
import { MoreHorizontal, UserRound } from "lucide-react";
import { Dialog } from "@/components/dialog";
import { Avatar } from "@/components/media/avatar";
import { personalRequest } from "@/components/personal/record-form";
import { ReactionPicker } from "@/components/social/reaction-picker";
import { SocialReport } from "@/components/social/report";
import { socialDate } from "@/components/social/presentation";
import type { SocialCommentDto, SocialIdentity, SocialPage } from "@/lib/social/types";

type ViewerIdentity = Pick<SocialIdentity, "fullName" | "avatarMedia">;
function CommentForm({ postId, parentCommentId, comment, viewer, focus = false, onDone }: { postId: string; parentCommentId?: string; comment?: SocialCommentDto; viewer?: ViewerIdentity; focus?: boolean; onDone: () => void }) {
  const router = useRouter(); const countId = useId(); const input = useRef<HTMLTextAreaElement>(null);
  const [body, setBody] = useState(comment?.body ?? ""); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (focus) input.current?.focus({ preventScroll: true }); }, [focus]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (pending) return; if (!body.trim()) { setError("Escreva seu comentário antes de enviar."); input.current?.focus(); return; } setPending(true); setError(null); try { await personalRequest(comment ? `/api/personal/social/comments/${comment.id}` : `/api/personal/social/posts/${postId}/comments`, comment ? "PATCH" : "POST", { body, ...(!comment && parentCommentId ? { parentCommentId } : {}) }); setBody(""); onDone(); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível enviar. Seu texto foi preservado."); } finally { setPending(false); } }
  return <form noValidate onSubmit={submit} className="social-comment-form">{viewer ? <Avatar name={viewer.fullName} media={viewer.avatarMedia} size="small" /> : <span className="social-comment-self" aria-hidden="true"><UserRound size={18} /></span>}<div className="min-w-0 space-y-2"><label className="block space-y-2 text-sm font-medium"><span>{comment ? "Editar comentário" : parentCommentId ? "Resposta" : "Comentário"}</span><textarea ref={input} className="field-control social-comment-input resize-none" value={body} onChange={(event) => setBody(event.target.value)} rows={3} maxLength={1500} disabled={pending} placeholder={parentCommentId ? "Continue a conversa…" : "Contribua com uma pergunta ou aprendizado…"} aria-describedby={countId} /></label><div className="flex flex-wrap items-center justify-between gap-2"><span id={countId} className="text-sm tabular-nums text-slate">{body.length}/1.500</span><button className="button-secondary" disabled={pending} aria-busy={pending}>{comment ? "Salvar comentário" : parentCommentId ? "Responder" : "Comentar"}</button></div>{error ? <p role="alert" className="text-sm text-danger">{error}</p> : null}</div></form>;
}

function Comment({ comment, viewerUserId, viewer, canComment, refresh, reply = false }: { comment: SocialCommentDto; viewerUserId?: string | null; viewer?: ViewerIdentity; canComment: boolean; refresh: () => void; reply?: boolean }) {
  const router = useRouter(); const [editing, setEditing] = useState(false); const [responding, setResponding] = useState(false); const [remove, setRemove] = useState(false); const [hide, setHide] = useState(false); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const [replies, setReplies] = useState<SocialPage<SocialCommentDto> | null>(null);
  async function act(url: string, method: string, input?: unknown) { if (pending) return; setPending(true); setError(null); try { await personalRequest(url, method, input); setRemove(false); setHide(false); refresh(); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível concluir a ação."); } finally { setPending(false); } }
  async function loadReplies(page = 1) { setPending(true); setError(null); try { setReplies(await personalRequest(`/api/personal/social/posts/${comment.postId}/comments?parentCommentId=${comment.id}&page=${page}`, "GET")); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível carregar respostas."); } finally { setPending(false); } }
  const available = !comment.deleted && !comment.hidden;
  const authorHref = comment.author.handle ? viewerUserId === comment.author.userId ? "/app/personal/profile" : viewerUserId ? `/app/personal/network/people/${comment.author.handle}` : `/people/${comment.author.handle}` : null;
  return <li><article className="social-comment">
    <div className="social-comment-identity"><Avatar name={comment.author.fullName} media={comment.author.avatarMedia} size="small" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-x-2 gap-y-1"><span className="text-sm font-semibold text-ink">{authorHref ? <Link href={authorHref} className="hover:underline">{comment.author.fullName}</Link> : comment.author.fullName}</span>{comment.isPostAuthor ? <span className="social-comment-author-badge">Autor</span> : null}</div>{comment.author.headline && !reply ? <p className="mt-0.5 text-sm leading-5 text-slate">{comment.author.headline}</p> : null}<div className="mt-1 flex flex-wrap gap-2 text-sm text-slate"><time dateTime={comment.createdAt}>{socialDate(comment.createdAt)}</time>{comment.editedAt ? <span>Editado</span> : null}</div></div>{viewerUserId && available ? <details className="social-overflow"><summary className="social-action" aria-label={`Mais ações no comentário de ${comment.author.fullName}`}><MoreHorizontal size={18} aria-hidden="true" /></summary><div className="social-overflow-panel">{comment.canEdit ? <><button className="button-tertiary" type="button" onClick={() => setEditing(true)}>Editar comentário</button><button className="button-tertiary" type="button" onClick={() => setRemove(true)}>Remover comentário</button></> : null}{comment.canHide ? <button className="button-tertiary" type="button" onClick={() => setHide(true)}>Ocultar comentário</button> : null}{!comment.canEdit ? <SocialReport commentId={comment.id} /> : null}</div></details> : null}</div>
    <div className="social-comment-content">{editing ? <div className="mt-3"><CommentForm comment={comment} postId={comment.postId} viewer={viewer} focus onDone={() => { setEditing(false); refresh(); }} /><button type="button" className="button-tertiary" onClick={() => setEditing(false)}>Cancelar edição</button></div> : <p className="social-comment-body">{comment.body ?? (comment.hidden ? "Comentário ocultado pelo autor da publicação." : "Comentário removido.")}</p>}
      {viewerUserId && available ? <div className="social-comment-actions"><ReactionPicker small value={comment.viewerReaction} disabled={pending} onChange={(type) => void act(`/api/personal/social/comments/${comment.id}/reaction`, "POST", { type })} />{comment.reactionCount > 0 ? <span className="text-sm text-slate">{comment.reactionCount} {comment.reactionCount === 1 ? "reação" : "reações"}</span> : null}{canComment ? <button type="button" className="social-action" aria-expanded={responding} onClick={() => setResponding(!responding)}>Responder</button> : null}</div> : null}
      {error ? <p role="alert" className="mt-2 text-sm text-danger">{error}</p> : null}
      {responding ? <div className="mt-3"><CommentForm postId={comment.postId} viewer={viewer} focus parentCommentId={comment.parentCommentId ?? comment.id} onDone={() => { setResponding(false); refresh(); if (!reply) void loadReplies(); }} /></div> : null}
      {!reply && !viewerUserId ? <Link className="button-tertiary mt-1" href={`/posts/${comment.postId}?parentCommentId=${comment.id}`}>Ver respostas</Link> : null}
      {!reply && viewerUserId ? <button type="button" className="button-tertiary mt-1" disabled={pending} aria-expanded={Boolean(replies)} onClick={() => replies ? setReplies(null) : void loadReplies()}>{replies ? "Fechar respostas" : "Ver respostas"}</button> : null}
    </div>
    {replies ? <div className="social-comment-replies"><ol className="space-y-5">{replies.items.map((item) => <Comment key={item.id} comment={item} viewerUserId={viewerUserId} viewer={viewer} canComment={canComment} reply refresh={() => void loadReplies(replies.page)} />)}</ol>{!replies.items.length ? <p className="text-sm text-slate">Nenhuma resposta.</p> : null}<div className="mt-2 flex flex-wrap gap-2">{replies.page > 1 ? <button className="button-tertiary" disabled={pending} onClick={() => void loadReplies(replies.page - 1)}>Respostas anteriores</button> : null}{replies.hasNext ? <button className="button-tertiary" disabled={pending} onClick={() => void loadReplies(replies.page + 1)}>Próximas respostas</button> : null}</div></div> : null}
  </article><Dialog open={remove || hide} title={hide ? "Ocultar comentário" : "Remover comentário"} description={hide ? "O texto deixará de aparecer para outros leitores. O histórico será preservado." : "O texto será removido. As respostas e o histórico da conversa serão preservados."} onClose={() => { if (!pending) { setRemove(false); setHide(false); } }}><div className="flex flex-wrap gap-2"><button type="button" className="button-secondary" disabled={pending} data-autofocus onClick={() => { setRemove(false); setHide(false); }}>Cancelar</button><button type="button" className="button-danger" disabled={pending} onClick={() => void act(`/api/personal/social/comments/${comment.id}${hide ? "/hide" : ""}`, hide ? "POST" : "DELETE", hide ? {} : undefined)}>{hide ? "Ocultar comentário" : "Remover comentário"}</button></div>{error ? <p role="alert" className="mt-3 text-sm text-danger">{error}</p> : null}</Dialog></li>;
}

export function Comments({ postId, viewerUserId, viewer, focusComposer = false, canComment, initial, publicParentCommentId }: { postId: string; viewerUserId?: string | null; viewer?: ViewerIdentity; focusComposer?: boolean; canComment: boolean; initial?: SocialPage<SocialCommentDto>; publicParentCommentId?: string }) {
  const [result, setResult] = useState<SocialPage<SocialCommentDto> | null>(initial ?? null); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const sequence = useRef(0);
  const query = `/api/personal/social/posts/${postId}/comments?${publicParentCommentId ? `parentCommentId=${encodeURIComponent(publicParentCommentId)}&` : ""}`;
  useEffect(() => {
    if (initial || !viewerUserId) return;
    let active = true; const request = ++sequence.current; setPending(true);
    void personalRequest(`${query}page=1`, "GET").then((value) => { if (active && sequence.current === request) setResult(value); }).catch((cause) => { if (active && sequence.current === request) setError(cause instanceof Error ? cause.message : "Não foi possível carregar comentários."); }).finally(() => { if (active && sequence.current === request) setPending(false); });
    return () => { active = false; };
  }, [initial, query, viewerUserId]);
  async function load(page = 1) { const request = ++sequence.current; setPending(true); setError(null); try { const value = await personalRequest(`${query}page=${page}`, "GET"); if (sequence.current === request) setResult(value); } catch (cause) { if (sequence.current === request) setError(cause instanceof Error ? cause.message : "Não foi possível carregar comentários."); } finally { if (sequence.current === request) setPending(false); } }
  return <section className="social-comments" aria-label="Comentários da publicação">{publicParentCommentId ? <Link className="button-tertiary" href={`/posts/${postId}`}>Voltar aos comentários</Link> : null}{viewerUserId && canComment ? <CommentForm postId={postId} viewer={viewer} focus={focusComposer} parentCommentId={publicParentCommentId} onDone={() => void load()} /> : viewerUserId ? <p className="text-sm leading-6 text-slate">Esta publicação não recebe seus comentários neste momento.</p> : null}{pending ? <p className="mt-3 text-sm text-slate" role="status">Carregando comentários…</p> : null}{error ? <div className="mt-3"><p className="text-sm text-danger" role="alert">{error}</p><button className="button-tertiary" disabled={pending} onClick={() => void load()}>Tentar novamente</button></div> : null}{result?.items.length ? <ol className="mt-6 space-y-6">{result.items.map((comment) => <Comment key={comment.id} comment={comment} viewerUserId={viewerUserId} viewer={viewer} canComment={canComment} reply={Boolean(publicParentCommentId)} refresh={() => void load(result.page)} />)}</ol> : result && !pending ? <p className="mt-4 text-sm leading-6 text-slate">{canComment ? "Ainda não há comentários. Comece a conversa." : "Ainda não há comentários visíveis."}</p> : null}{result && viewerUserId ? <nav className="mt-3 flex flex-wrap gap-2" aria-label="Páginas de comentários">{result.page > 1 ? <button className="button-tertiary" disabled={pending} onClick={() => void load(result.page - 1)}>Comentários anteriores</button> : null}{result.hasNext ? <button className="button-tertiary" disabled={pending} onClick={() => void load(result.page + 1)}>Próximos comentários</button> : null}</nav> : null}</section>;
}
