import Link from "next/link";
import { PageHeader } from "@/components/ui";
import { Avatar } from "@/components/media/avatar";
import { FollowButton } from "@/components/social/follow-button";
import { getFollowStates, listFollows } from "@/lib/social/read-model";

export async function FollowList({ userId, direction, page }: { userId: string; direction: "followers" | "following"; page?: string }) {
  const result = await listFollows(userId, direction, page);
  const states = await getFollowStates(userId, result.items.map((person) => person.userId));
  const title = direction === "followers" ? "Seguidores" : "Seguindo";
  return <div className="social-surface social-people-page"><PageHeader title={title} description={direction === "followers" ? "Pessoas que acompanham suas publicações." : "Acompanhe as atualizações e os aprendizados da sua rede."} action={<Link href="/app/personal/profile" className="button-secondary">Meu perfil</Link>} /><nav className="social-tabs" aria-label="Acompanhamentos"><Link aria-current={direction === "followers" ? "page" : undefined} href="/app/personal/profile/followers">Seguidores</Link><Link aria-current={direction === "following" ? "page" : undefined} href="/app/personal/profile/following">Seguindo</Link></nav>{result.items.length ? <ul className="social-people-list">{result.items.map((person) => <li key={person.userId}><Avatar name={person.fullName} media={person.avatarMedia} /><div className="social-person-copy"><p className="break-words font-semibold">{person.handle ? <Link className="hover:underline" href={`/app/personal/network/people/${person.handle}`}>{person.fullName}</Link> : person.fullName}</p>{person.headline ? <p className="mt-1 break-words text-sm leading-6 text-slate">{person.headline}</p> : null}</div>{states[person.userId] ? <FollowButton userId={person.userId} {...states[person.userId]} /> : null}</li>)}</ul> : <div className="social-feed-empty"><h2 className="font-semibold">{direction === "followers" ? "Sua conversa está começando" : "Encontre pessoas para acompanhar"}</h2><p className="mt-2 text-sm leading-6 text-slate">{direction === "followers" ? "Quem seguir seu perfil aparecerá aqui. Compartilhe sua atuação para abrir novas conversas." : "Explore a Rede e siga pessoas com interesses próximos aos seus."}</p><Link className="button-secondary mt-4" href={direction === "followers" ? "/app/personal/feed" : "/app/personal/network/people"}>{direction === "followers" ? "Abrir início" : "Explorar a Rede"}</Link></div>}<nav className="mt-5 flex gap-2" aria-label={`Páginas de ${title.toLocaleLowerCase("pt-BR")}`}>{result.page > 1 ? <Link className="button-secondary" href={`?page=${result.page - 1}`}>Anterior</Link> : null}{result.hasNext ? <Link className="button-secondary" href={`?page=${result.page + 1}`}>Próxima</Link> : null}</nav></div>;
}
