import Link from "next/link";
import { PageHeader } from "@/components/ui";
import { profileMonogram } from "@/components/profiles/profile-renderer";
import { FollowButton } from "@/components/social/follow-button";
import { listFollows } from "@/lib/social/read-model";
export async function FollowList({ userId, direction, page }: { userId: string; direction: "followers" | "following"; page?: string }) {
  const result = await listFollows(userId, direction, page); const title = direction === "followers" ? "Seguidores" : "Seguindo";
  return <div className="mx-auto w-full max-w-3xl space-y-6"><PageHeader title={title} description={direction === "followers" ? "Pessoas que acompanham suas publicações." : "Publicações dessas pessoas podem aparecer no seu início, conforme a visibilidade."} action={<Link href="/app/personal/profile" className="button-secondary">Meu perfil</Link>} /><nav className="flex gap-2" aria-label="Acompanhamentos"><Link className={direction === "followers" ? "button-secondary" : "button-tertiary"} href="/app/personal/profile/followers">Seguidores</Link><Link className={direction === "following" ? "button-secondary" : "button-tertiary"} href="/app/personal/profile/following">Seguindo</Link></nav>{result.items.length ? <ul className="divide-y divide-line border-y border-line">{result.items.map((person) => <li key={person.userId} className="flex flex-wrap items-start gap-3 py-5"><span className="social-avatar" aria-hidden="true">{profileMonogram(person.fullName)}</span><div className="min-w-0 flex-1 basis-40"><p className="break-words font-semibold">{person.handle ? <Link href={`/app/personal/network/people/${person.handle}`}>{person.fullName}</Link> : person.fullName}</p>{person.headline ? <p className="mt-1 break-words text-sm text-slate">{person.headline}</p> : null}</div>{direction === "following" ? <FollowButton userId={person.userId} following /> : null}</li>)}</ul> : <p className="py-7 text-sm text-slate">Nenhuma pessoa nesta página.</p>}<nav className="flex gap-2" aria-label={`Páginas de ${title.toLocaleLowerCase("pt-BR")}`}>{result.page > 1 ? <Link className="button-secondary" href={`?page=${result.page - 1}`}>Anterior</Link> : null}{result.hasNext ? <Link className="button-secondary" href={`?page=${result.page + 1}`}>Próxima</Link> : null}</nav></div>;
}
