"use client";

import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowUpRight, Globe2, LockKeyhole, MessageCircle, MoreHorizontal, Repeat2, Share2, Users } from "lucide-react";
import type { ReactionType } from "@prisma/client";
import { Dialog } from "@/components/dialog";
import { Avatar } from "@/components/media/avatar";
import { PostImages } from "@/components/media/post-images";
import { personalRequest } from "@/components/personal/record-form";
import { Comments } from "@/components/social/comments";
import { PostComposer } from "@/components/social/post-composer";
import { ReactionPicker } from "@/components/social/reaction-picker";
import { SocialReport } from "@/components/social/report";
import { postVisibilityLabels, reactionLabels, socialDate } from "@/components/social/presentation";
import type { SocialCommentDto, SocialPage, SocialPersonIdentity, SocialPostDto } from "@/lib/social/types";

type ViewerIdentity = Pick<SocialPersonIdentity, "fullName" | "avatarMedia">;

function PostContent({ post, compact = false, expandedByDefault = false }: { post: SocialPostDto; compact?: boolean; expandedByDefault?: boolean }) {
  const [expanded, setExpanded] = useState(expandedByDefault);
  const limit = compact ? 280 : 650;
  const long = (post.body?.length ?? 0) > limit;
  return <>
    {post.body ? <div><p className="social-post-body">{long && !expanded ? `${post.body.slice(0, limit).trimEnd()}…` : post.body}</p>{long ? compact ? <Link href={`/posts/${post.id}`} className="social-action mt-1">Ler publicação completa</Link> : <button className="social-action mt-1" type="button" aria-expanded={expanded} onClick={() => setExpanded(!expanded)}>{expanded ? "Ver menos" : "Ler publicação completa"}</button> : null}</div> : null}
    {post.media?.length ? <PostImages images={post.media} compact={compact} /> : null}
    {post.externalUrl ? <a className={`social-external-link${compact ? " social-external-link-compact" : ""}`} href={post.externalUrl} target="_blank" rel="noopener noreferrer nofollow ugc"><span className="min-w-0"><strong className="block break-all text-sm">{new URL(post.externalUrl).hostname}</strong>{!compact ? <span className="mt-1 block break-all text-sm text-slate">{post.externalUrl}</span> : null}</span><ArrowUpRight className="shrink-0" size={18} aria-hidden="true" /></a> : null}
  </>;
}

export function PostCard({ post, viewerUserId, viewer, detail = false, initialComments, publicProfile = false, publicParentCommentId, variant = "feed" }: { post: SocialPostDto; viewerUserId?: string | null; viewer?: ViewerIdentity; detail?: boolean; initialComments?: SocialPage<SocialCommentDto>; publicProfile?: boolean; publicParentCommentId?: string; variant?: "feed" | "profile" }) {
  const router = useRouter();
  const [comments, setComments] = useState(detail); const [focusComment, setFocusComment] = useState(false); const [pending, setPending] = useState(false);
  const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [remove, setRemove] = useState(false); const [share, setShare] = useState(false);
  const [reactions, setReactions] = useState<SocialPage<SocialPersonIdentity & { type: ReactionType }> | null>(null); const [reactionsOpen, setReactionsOpen] = useState(false);
  const compact = variant === "profile";
  const VisibilityIcon = post.visibility === "PUBLIC" ? Globe2 : post.visibility === "CONNECTIONS" ? Users : LockKeyhole;
  async function act(path: string, method = "POST", input?: unknown) { if (pending) return; setPending(true); setError(null); setNotice(null); try { await personalRequest(`/api/personal/social/posts/${post.id}${path}`, method, input); setRemove(false); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível concluir a ação."); } finally { setPending(false); } }
  async function loadReactions(page = 1) { setPending(true); setError(null); setReactionsOpen(true); try { setReactions(await personalRequest(`/api/personal/social/posts/${post.id}/reactions?page=${page}`, "GET")); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível carregar reações."); } finally { setPending(false); } }
  async function copy() { const url = `${window.location.origin}/posts/${post.id}`; try { await navigator.clipboard.writeText(url); setNotice("Link da publicação copiado."); } catch { setShare(true); } }
  function openComments(focus: boolean) { setFocusComment(focus); setComments((value) => focus ? true : !value); }
  const authorHref = post.author.kind === "ORGANIZATION" ? `/institutions/${post.author.slug}`
    : post.author.handle ? viewerUserId ? post.author.userId === viewerUserId ? "/app/personal/profile" : `/app/personal/network/people/${post.author.handle}` : `/people/${post.author.handle}` : null;
  const viewerIdentity = viewer ?? (post.author.userId === viewerUserId ? post.author : undefined);
  return <article className={`social-post social-surface${compact ? " social-post-profile" : ""}`} aria-label={`Publicação de ${post.author.fullName}`}>
    {post.activityComment ? <div className="social-activity-context"><p className="text-sm font-medium text-slate">Comentou em uma publicação</p><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-6">{post.activityComment.body}</p></div> : null}
    <header className="social-post-header"><Avatar name={post.author.fullName} media={post.author.avatarMedia} size={compact ? "small" : "medium"} /><div className="social-post-identity min-w-0 flex-1"><p className="social-post-author">{authorHref ? <Link href={authorHref} className="hover:underline">{post.author.fullName}</Link> : post.author.fullName}{post.author.kind === "ORGANIZATION" ? <span className="ml-2 rounded-full bg-surface-subtle px-2 py-0.5 text-[0.6875rem] font-medium text-slate">Instituição</span> : null}</p>{post.author.headline && !compact ? <p className="social-post-headline">{post.author.headline}</p> : null}<div className="social-post-meta"><Link href={`/posts/${post.id}`} className="hover:underline"><time dateTime={post.createdAt}>{socialDate(post.createdAt)}</time></Link><span className="inline-flex items-center gap-1"><VisibilityIcon size={14} aria-hidden="true" />{postVisibilityLabels[post.visibility]}</span>{post.editedAt ? <span>Editado</span> : null}</div></div><details className="social-overflow"><summary className="social-action px-2" aria-label={`Mais ações na publicação de ${post.author.fullName}`}><MoreHorizontal size={20} aria-hidden="true" /></summary><div className="social-overflow-panel"><button className="button-tertiary" type="button" onClick={() => void copy()}>Copiar link da publicação</button>{viewerUserId ? <><button className="button-tertiary" disabled={pending} type="button" onClick={() => void act("/save", "POST", { saved: !post.saved })}>{post.saved ? "Remover dos salvos" : "Salvar publicação"}</button>{post.canEdit ? <><PostComposer fullName={post.author.fullName} avatarMedia={post.author.avatarMedia} post={post} /><button className="button-tertiary" type="button" disabled={pending} onClick={() => void act("/feature", "POST", { featured: !post.featured })}>{post.featured ? "Retirar do destaque" : "Destacar no perfil"}</button><button className="button-tertiary" type="button" onClick={() => setRemove(true)}>Remover publicação</button></> : <SocialReport postId={post.id} />}</> : null}</div></details></header>
    <div className="social-post-content"><PostContent post={post} compact={compact} expandedByDefault={detail} />{post.repostOfPostId ? post.original ? <div className="social-repost"><div className="social-repost-header"><Avatar name={post.original.author.fullName} media={post.original.author.avatarMedia} size="small" /><p className="min-w-0 text-sm text-slate"><Repeat2 size={14} className="mr-1 inline" aria-hidden="true" />Repostagem de <Link className="font-semibold text-ink hover:underline" href={`/posts/${post.original.id}`}>{post.original.author.fullName}</Link></p></div><PostContent post={post.original} compact /></div> : <div className="social-repost text-sm text-slate">Publicação original indisponível.</div> : null}</div>
    {post.reactionCount || post.commentCount || post.repostCount ? <div className="social-engagement">{post.reactionCount ? viewerUserId ? <button type="button" disabled={pending} onClick={() => void loadReactions()}>{post.reactionCount} {post.reactionCount === 1 ? "reação" : "reações"}</button> : <span>{post.reactionCount} {post.reactionCount === 1 ? "reação" : "reações"}</span> : null}{post.commentCount ? compact ? <Link href={`/posts/${post.id}`}>{post.commentCount} {post.commentCount === 1 ? "comentário" : "comentários"}</Link> : <button type="button" onClick={() => openComments(false)} aria-expanded={comments}>{post.commentCount} {post.commentCount === 1 ? "comentário" : "comentários"}</button> : null}{post.repostCount ? <span>{post.repostCount} {post.repostCount === 1 ? "repostagem" : "repostagens"}</span> : null}</div> : null}
    {compact ? <Link className="social-post-open" href={`/posts/${post.id}`}>Abrir publicação<ArrowUpRight size={15} aria-hidden="true" /></Link> : viewerUserId ? <div className="social-post-actions"><ReactionPicker value={post.viewerReaction} disabled={pending} onChange={(type) => void act("/reaction", "POST", { type })} /><button className="social-action" type="button" onClick={() => openComments(true)} aria-expanded={comments}><MessageCircle size={17} aria-hidden="true" /><span>Comentar</span></button>{post.canRepost ? <PostComposer fullName={viewerIdentity?.fullName ?? "Você"} avatarMedia={viewerIdentity?.avatarMedia} repost={post} publicProfile={publicProfile} /> : null}<button className="social-action" type="button" onClick={() => void copy()}><Share2 size={17} aria-hidden="true" /><span>Compartilhar</span></button></div> : <div className="social-public-actions"><Link className="button-primary" href="/login">Entrar para interagir</Link><button type="button" className="button-tertiary" onClick={() => void copy()}>Copiar link da publicação</button></div>}
    {notice ? <p className="mt-2 text-sm text-success" role="status">{notice}</p> : null}{error && !remove && !reactionsOpen ? <p className="mt-2 text-sm text-danger" role="alert">{error}</p> : null}{comments && !compact ? <Comments postId={post.id} viewerUserId={viewerUserId} viewer={viewerIdentity} focusComposer={focusComment} canComment={post.canComment} initial={initialComments} publicParentCommentId={publicParentCommentId} /> : null}
    <Dialog open={remove} title="Remover publicação" description="A publicação deixará de aparecer. O histórico será preservado e repostagens não mostrarão seu conteúdo." onClose={() => { if (!pending) setRemove(false); }}><div className="flex flex-wrap gap-2"><button type="button" className="button-secondary" disabled={pending} data-autofocus onClick={() => setRemove(false)}>Cancelar</button><button type="button" className="button-danger" disabled={pending} onClick={() => void act("", "DELETE")}>Remover publicação</button></div>{error ? <p role="alert" className="mt-3 text-sm text-danger">{error}</p> : null}</Dialog>
    <Dialog open={share} title="Copiar link da publicação" description="Selecione e copie o endereço. A visibilidade da publicação continua sendo respeitada." onClose={() => setShare(false)}><label className="block space-y-2 text-sm"><span>Link da publicação</span><input readOnly className="field-control" value={typeof window === "undefined" ? `/posts/${post.id}` : `${window.location.origin}/posts/${post.id}`} onFocus={(event) => event.target.select()} /></label></Dialog>
    <Dialog open={reactionsOpen} title="Reações" onClose={() => setReactionsOpen(false)}>{pending ? <p role="status" className="text-sm text-slate">Carregando reações…</p> : null}{error ? <p role="alert" className="text-sm text-danger">{error}</p> : null}<ul className="divide-y divide-line">{reactions?.items.map((person) => <li className="flex items-center gap-3 py-3" key={person.userId}><Avatar name={person.fullName} media={person.avatarMedia} /><div className="min-w-0 flex-1"><p className="break-words text-sm font-semibold">{person.handle ? <Link href={`/app/personal/network/people/${person.handle}`}>{person.fullName}</Link> : person.fullName}</p>{person.headline ? <p className="mt-1 break-words text-sm text-slate">{person.headline}</p> : null}</div><span className="text-sm text-slate">{reactionLabels[person.type]}</span></li>)}</ul><div className="mt-3 flex gap-2">{reactions && reactions.page > 1 ? <button className="button-secondary" disabled={pending} onClick={() => void loadReactions(reactions.page - 1)}>Anterior</button> : null}{reactions?.hasNext ? <button className="button-secondary" disabled={pending} onClick={() => void loadReactions(reactions.page + 1)}>Próxima</button> : null}</div></Dialog>
  </article>;
}
