"use client";

import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowUpRight, Globe2, LockKeyhole, MessageCircle, MoreHorizontal, Share2, Users } from "lucide-react";
import type { ReactionType } from "@prisma/client";
import { Dialog } from "@/components/dialog";
import { personalRequest } from "@/components/personal/record-form";
import { profileMonogram } from "@/components/profiles/profile-renderer";
import { Comments } from "@/components/social/comments";
import { PostComposer } from "@/components/social/post-composer";
import { ReactionPicker } from "@/components/social/reaction-picker";
import { SocialReport } from "@/components/social/report";
import { postVisibilityLabels, reactionLabels, socialDate } from "@/components/social/presentation";
import type { SocialCommentDto, SocialIdentity, SocialPage, SocialPostDto } from "@/lib/social/types";

function PostContent({ post }: { post: SocialPostDto }) {
  const [expanded, setExpanded] = useState(false); const long = (post.body?.length ?? 0) > 650;
  return <>{post.body ? <div><p className="whitespace-pre-wrap break-words text-sm leading-7">{long && !expanded ? `${post.body.slice(0, 650)}…` : post.body}</p>{long ? <button className="social-action mt-1" type="button" aria-expanded={expanded} onClick={() => setExpanded(!expanded)}>{expanded ? "Ver menos" : "Ler publicação completa"}</button> : null}</div> : null}{post.externalUrl ? <a className="social-external-link" href={post.externalUrl} target="_blank" rel="noopener noreferrer nofollow ugc"><span className="min-w-0"><strong className="block break-all text-sm">{new URL(post.externalUrl).hostname}</strong><span className="mt-1 block break-all text-xs text-slate">{post.externalUrl}</span></span><ArrowUpRight className="shrink-0" size={18} aria-hidden="true" /></a> : null}</>;
}

export function PostCard({ post, viewerUserId, detail = false, initialComments, publicProfile = false, publicParentCommentId }: { post: SocialPostDto; viewerUserId?: string | null; detail?: boolean; initialComments?: SocialPage<SocialCommentDto>; publicProfile?: boolean; publicParentCommentId?: string }) {
  const router = useRouter(); const [comments, setComments] = useState(detail); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [remove, setRemove] = useState(false); const [share, setShare] = useState(false); const [reactions, setReactions] = useState<SocialPage<SocialIdentity & { type: ReactionType }> | null>(null); const [reactionsOpen, setReactionsOpen] = useState(false);
  const VisibilityIcon = post.visibility === "PUBLIC" ? Globe2 : post.visibility === "CONNECTIONS" ? Users : LockKeyhole;
  async function act(path: string, method = "POST", input?: unknown) { setPending(true); setError(null); setNotice(null); try { await personalRequest(`/api/personal/social/posts/${post.id}${path}`, method, input); setRemove(false); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível concluir a ação."); } finally { setPending(false); } }
  async function loadReactions(page = 1) { setPending(true); setError(null); setReactionsOpen(true); try { setReactions(await personalRequest(`/api/personal/social/posts/${post.id}/reactions?page=${page}`, "GET")); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível carregar reações."); } finally { setPending(false); } }
  async function copy() { const url = `${window.location.origin}/posts/${post.id}`; try { await navigator.clipboard.writeText(url); setNotice("Link da publicação copiado."); } catch { setShare(true); } }
  const authorHref = post.author.handle ? viewerUserId ? post.author.userId === viewerUserId ? "/app/personal/profile" : `/app/personal/network/people/${post.author.handle}` : `/people/${post.author.handle}` : null;
  return <article className="social-post" aria-label={`Publicação de ${post.author.fullName}`}>
    {post.activityComment ? <div className="social-activity-context"><p className="text-xs font-medium text-slate">Comentou em uma publicação</p><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-6">{post.activityComment.body}</p></div> : null}
    <header className="flex items-start gap-3"><span className="social-avatar shrink-0" aria-hidden="true">{profileMonogram(post.author.fullName)}</span><div className="min-w-0 flex-1"><p className="break-words text-sm font-semibold">{authorHref ? <Link href={authorHref} className="hover:underline">{post.author.fullName}</Link> : post.author.fullName}</p>{post.author.headline ? <p className="mt-0.5 break-words text-xs leading-5 text-slate">{post.author.headline}</p> : null}<div className="mt-1 flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-slate"><Link href={`/posts/${post.id}`} className="hover:underline"><time dateTime={post.createdAt}>{socialDate(post.createdAt)}</time></Link><span className="inline-flex items-center gap-1"><VisibilityIcon size={12} aria-hidden="true" />{postVisibilityLabels[post.visibility]}</span>{post.editedAt ? <span>Editado</span> : null}</div></div><details className="social-overflow"><summary className="social-action cursor-pointer px-2" aria-label={`Mais ações na publicação de ${post.author.fullName}`}><MoreHorizontal size={20} aria-hidden="true" /></summary><div className="social-overflow-panel"><button className="button-tertiary" type="button" onClick={() => void copy()}>Copiar link da publicação</button>{viewerUserId ? <><button className="button-tertiary" disabled={pending} type="button" onClick={() => void act("/save", "POST", { saved: !post.saved })}>{post.saved ? "Remover dos salvos" : "Salvar publicação"}</button>{post.canEdit ? <><PostComposer fullName={post.author.fullName} post={post} /><button className="button-tertiary" type="button" disabled={pending} onClick={() => void act("/feature", "POST", { featured: !post.featured })}>{post.featured ? "Retirar do destaque" : "Destacar no perfil"}</button><button className="button-tertiary" type="button" onClick={() => setRemove(true)}>Remover publicação</button></> : <SocialReport postId={post.id} />}</> : null}</div></details></header>
    <div className="mt-4 space-y-4"><PostContent post={post} />{post.repostOfPostId ? post.original ? <div className="social-repost"><p className="mb-3 text-xs text-slate">Repostagem de <Link className="font-medium hover:underline" href={`/posts/${post.original.id}`}>{post.original.author.fullName}</Link></p><PostContent post={post.original} /></div> : <div className="social-repost text-sm text-slate">Publicação original indisponível.</div> : null}</div>
    {post.reactionCount || post.commentCount || post.repostCount ? <div className="mt-4 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate">{post.reactionCount ? viewerUserId ? <button type="button" className="min-h-11 hover:underline" onClick={() => void loadReactions()}>{post.reactionCount} {post.reactionCount === 1 ? "reação" : "reações"}</button> : <span className="inline-flex min-h-11 items-center">{post.reactionCount} {post.reactionCount === 1 ? "reação" : "reações"}</span> : null}{post.commentCount ? <button type="button" className="min-h-11 hover:underline" onClick={() => setComments(!comments)}>{post.commentCount} {post.commentCount === 1 ? "comentário" : "comentários"}</button> : null}{post.repostCount ? <span className="inline-flex min-h-11 items-center">{post.repostCount} {post.repostCount === 1 ? "repostagem" : "repostagens"}</span> : null}</div> : null}
    {viewerUserId ? <div className="social-post-actions"><ReactionPicker value={post.viewerReaction} disabled={pending} onChange={(type) => void act("/reaction", "POST", { type })} /><button className="social-action" type="button" onClick={() => setComments(!comments)} aria-expanded={comments}><MessageCircle size={16} aria-hidden="true" /><span>Comentar</span></button>{post.canRepost ? <PostComposer fullName="Você" repost={post} publicProfile={publicProfile} /> : null}<button className="social-action" type="button" onClick={() => void copy()}><Share2 size={16} aria-hidden="true" /><span>Compartilhar</span></button></div> : <div className="mt-4 border-t border-line pt-3"><Link className="button-secondary" href="/login">Entrar para interagir</Link><button type="button" className="button-tertiary" onClick={() => void copy()}>Copiar link da publicação</button></div>}
    {notice ? <p className="mt-2 text-xs text-success" role="status">{notice}</p> : null}{error && !remove && !reactionsOpen ? <p className="mt-2 text-sm text-danger" role="alert">{error}</p> : null}{comments ? <Comments postId={post.id} viewerUserId={viewerUserId} canComment={post.canComment} initial={initialComments} publicParentCommentId={publicParentCommentId} /> : null}
    <Dialog open={remove} title="Remover publicação" description="A publicação deixará de aparecer. O histórico será preservado e repostagens não mostrarão seu conteúdo." onClose={() => { if (!pending) setRemove(false); }}><div className="flex flex-wrap gap-2"><button type="button" className="button-secondary" disabled={pending} data-autofocus onClick={() => setRemove(false)}>Cancelar</button><button type="button" className="button-danger" disabled={pending} onClick={() => void act("", "DELETE")}>Remover publicação</button></div>{error ? <p role="alert" className="mt-3 text-sm text-danger">{error}</p> : null}</Dialog>
    <Dialog open={share} title="Copiar link da publicação" description="Selecione e copie o endereço. A visibilidade da publicação continua sendo respeitada." onClose={() => setShare(false)}><label className="block space-y-2 text-sm"><span>Link da publicação</span><input readOnly className="field-control" value={typeof window === "undefined" ? `/posts/${post.id}` : `${window.location.origin}/posts/${post.id}`} onFocus={(event) => event.target.select()} /></label></Dialog>
    <Dialog open={reactionsOpen} title="Reações" onClose={() => setReactionsOpen(false)}>{pending ? <p role="status" className="text-sm text-slate">Carregando reações…</p> : null}{error ? <p role="alert" className="text-sm text-danger">{error}</p> : null}<ul className="divide-y divide-line">{reactions?.items.map((person) => <li className="flex items-center justify-between gap-3 py-3" key={person.userId}><span className="min-w-0 break-words text-sm">{person.handle ? <Link href={`/app/personal/network/people/${person.handle}`}>{person.fullName}</Link> : person.fullName}</span><span className="text-xs text-slate">{reactionLabels[person.type]}</span></li>)}</ul><div className="mt-3 flex gap-2">{reactions && reactions.page > 1 ? <button className="button-secondary" disabled={pending} onClick={() => void loadReactions(reactions.page - 1)}>Anterior</button> : null}{reactions?.hasNext ? <button className="button-secondary" disabled={pending} onClick={() => void loadReactions(reactions.page + 1)}>Próxima</button> : null}</div></Dialog>
  </article>;
}
