import Link from "next/link";
import { ArrowRight, ClipboardCheck } from "lucide-react";
import { Panel, PanelHeader, StatusBadge } from "@/components/ui";
import { awardStatusLabels, executionTone, moneyLabel } from "@/components/execution/presentation";
import { formatMonitoringDate } from "@/lib/monitoring/format";
import type { AwardSummaryDto } from "@/lib/awards/read-model";

export function institutionalAwardHref(award: AwardSummaryDto) { return `/app/programs/${award.fundingCall.fundingProgram.id}/calls/${award.fundingCall.id}/execution/${award.id}`; }
export function AwardSummaryList({ awards, personal = false, title = "Apoios e execução", description }: { awards: AwardSummaryDto[]; personal?: boolean; title?: string; description?: string }) { return <Panel><PanelHeader title={title} description={description} />{awards.length ? <ul className="divide-y divide-line">{awards.map((award) => { const due = award.obligations.filter((entry) => entry.dueAt && !["APPROVED", "WAIVED"].includes(entry.state)).sort((a, b) => a.dueAt!.localeCompare(b.dueAt!))[0]; return <li key={award.id}><Link href={personal ? `/app/personal/awards/${award.id}` : institutionalAwardHref(award)} className="grid min-h-11 gap-4 px-4 py-5 hover:bg-surface-subtle sm:px-6 lg:grid-cols-[minmax(0,1.3fr)_minmax(9rem,.8fr)_minmax(0,1fr)_auto] lg:items-center"><div className="min-w-0"><h3 className="break-words font-semibold">{award.application.projectNameSnapshot}</h3><p className="mt-1 break-words text-xs leading-5 text-slate">{award.fundingCall.fundingProgram.name} · {award.fundingCall.title}</p>{personal ? <p className="mt-1 text-xs text-slate">{award.organization.name}</p> : null}{award.agreementNumber ? <p className="mt-1 break-words text-xs text-slate">Termo {award.agreementNumber}</p> : null}</div><div className="space-y-2"><StatusBadge label={awardStatusLabels[award.status]} tone={executionTone(award.status)} /><p className="text-xs leading-5 text-slate">{award.startsAt ? formatMonitoringDate(award.startsAt) : "Início a definir"}{award.endsAt ? ` a ${formatMonitoringDate(award.endsAt)}` : ""}</p></div><div className="space-y-2 text-sm"><p>{award.counts.approved} de {award.counts.obligations} obrigação(ões) aprovada(s){award.counts.waived ? ` · ${award.counts.waived} dispensada(s)` : ""}</p>{award.counts.pendingReviews ? <p className="text-accent-hover">{award.counts.pendingReviews} aguardando análise</p> : null}{award.counts.overdue ? <p className="text-danger">{award.counts.overdue} em atraso</p> : null}{award.counts.changesRequested ? <p className="text-warning">{award.counts.changesRequested} com ajustes solicitados</p> : null}{due ? <p className="break-words text-xs leading-5 text-slate">Próximo prazo: {formatMonitoringDate(due.dueAt)} · {due.title}</p> : null}{award.approvedAmount !== null ? <p className="text-xs text-slate">Aprovado: {moneyLabel(award.approvedAmount)} · Pago: {moneyLabel(award.financial.paid)}</p> : null}</div><span className="inline-flex items-center gap-2 text-sm font-medium text-accent-hover">Abrir<ArrowRight size={16} aria-hidden="true" /></span></Link></li>; })}</ul> : <div className="px-4 py-9 sm:px-6"><ClipboardCheck size={24} className="mb-3 text-slate" aria-hidden="true" /><h3 className="font-medium">Nenhum apoio neste recorte</h3><p className="mt-2 max-w-xl text-sm leading-6 text-slate">Os apoios preparados a partir dos resultados publicados aparecerão aqui, com entregas, análise institucional e execução.</p></div>}</Panel>; }

export function ExecutionPagination({ page, pageSize, total, href }: { page: number; pageSize: number; total: number; href: (page: number) => string }) { if (total <= pageSize) return null; const pages = Math.ceil(total / pageSize); return <nav aria-label="Paginação da execução" className="flex flex-wrap items-center justify-between gap-3 text-sm"><p className="text-slate">Página {page} de {pages} · {total} registro(s)</p><div className="flex gap-3">{page > 1 ? <Link className="button-secondary" href={href(page - 1)}>Anterior</Link> : null}{page < pages ? <Link className="button-secondary" href={href(page + 1)}>Próxima</Link> : null}</div></nav>; }
