"use client";

import { useState, type FormEvent, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { Dialog } from "@/components/dialog";
import { selectionRequest } from "@/components/selection/request";
import { awardStatusLabels } from "@/components/execution/presentation";

type AwardTerms = { id: string; revision: number; status: string; agreementNumber: string | null; approvedAmount: string | null; counterpartAmount: string | null; signedAt: string | null; startsAt: string | null; endsAt: string | null };

export function ExecutionAction({ label, title, description, apiUrl, method = "POST", children, input, onSuccess, primary = false, disabled = false }: { label: string; title: string; description?: string; apiUrl: string; method?: string; children: ReactNode; input: (data: FormData) => unknown; onSuccess?: (payload: unknown) => void; primary?: boolean; disabled?: boolean }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setPending(true); setError(null); try { const payload = await selectionRequest(apiUrl, method, input(data)); setOpen(false); onSuccess?.(payload); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível salvar. Revise os dados e tente novamente."); } finally { setPending(false); } }
  return <><button type="button" className={primary ? "button-primary" : "button-secondary"} disabled={disabled} onClick={() => { setError(null); setOpen(true); }}>{label}</button><Dialog open={open} onClose={() => { if (!pending) setOpen(false); }} title={title} description={description}><form onSubmit={submit} className="space-y-5"><fieldset disabled={pending} className="min-w-0 space-y-4">{children}</fieldset>{error ? <p role="alert" className="break-words text-sm leading-6 text-danger">{error}</p> : null}<div className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" className="button-secondary" disabled={pending} onClick={() => setOpen(false)}>Voltar</button><button type="submit" className="button-primary" disabled={pending}>{pending ? "Salvando…" : label}</button></div></form></Dialog></>;
}

export function FormField({ label, name, value, type = "text", required = false, maxLength = 240, hint }: { label: string; name: string; value?: string | number | null; type?: string; required?: boolean; maxLength?: number; hint?: string }) { return <label className="block space-y-2 text-sm font-medium"><span>{label}{required ? " *" : ""}</span><input className="field-control" name={name} type={type} defaultValue={value ?? ""} required={required} maxLength={maxLength} {...(type === "number" ? { min: "0", step: "0.01", inputMode: "decimal" as const } : {})} />{hint ? <span className="block text-xs font-normal leading-5 text-slate">{hint}</span> : null}</label>; }
export function TextField({ label, name, value, required = false, maxLength = 4000 }: { label: string; name: string; value?: string | null; required?: boolean; maxLength?: number }) { return <label className="block space-y-2 text-sm font-medium"><span>{label}{required ? " *" : ""}</span><textarea className="field-control min-h-28" name={name} defaultValue={value ?? ""} required={required} maxLength={maxLength} rows={4} /></label>; }
export function optionalValue(data: FormData, name: string) { return String(data.get(name) ?? "").trim() || null; }
function termsInput(data: FormData) { return { agreementNumber: optionalValue(data, "agreementNumber"), approvedAmount: optionalValue(data, "approvedAmount"), counterpartAmount: optionalValue(data, "counterpartAmount"), startsAt: optionalValue(data, "startsAt"), endsAt: optionalValue(data, "endsAt"), signedAt: optionalValue(data, "signedAt") }; }
function TermsFields({ award, compact = false }: { award?: AwardTerms; compact?: boolean }) { return <><FormField label="Número do termo" name="agreementNumber" value={award?.agreementNumber} maxLength={120} hint="Opcional. O apoio também pode ser não financeiro." /><div className="grid gap-4 sm:grid-cols-2"><FormField label="Valor aprovado (R$)" name="approvedAmount" type="number" value={award?.approvedAmount} />{!compact ? <FormField label="Contrapartida (R$)" name="counterpartAmount" type="number" value={award?.counterpartAmount} /> : null}<FormField label="Início da execução" name="startsAt" type="date" value={award?.startsAt} /><FormField label="Fim da execução" name="endsAt" type="date" value={award?.endsAt} />{!compact ? <FormField label="Assinatura" name="signedAt" type="date" value={award?.signedAt} /> : null}</div></>; }

export function PrepareAward({ apiBase, applicationId, projectName, executionBaseHref }: { apiBase: string; applicationId: string; projectName: string; executionBaseHref: string }) { const router = useRouter(); return <ExecutionAction primary label="Preparar apoio" title={`Preparar apoio · ${projectName}`} description="A seleção inicia a preparação dos termos. A execução começa após a ativação do apoio." apiUrl={`${apiBase}/execution`} input={(data) => ({ applicationId, ...termsInput(data) })} onSuccess={(payload) => { const award = (payload as { award?: { id: string } }).award; if (award) router.push(`${executionBaseHref}/${award.id}`); }}><TermsFields compact /></ExecutionAction>; }

export function AwardTermsAction({ award, apiBase }: { award: AwardTerms; apiBase: string }) { return <ExecutionAction label="Editar termos" title="Editar termo de apoio" apiUrl={apiBase} method="PATCH" input={(data) => ({ revision: award.revision, ...termsInput(data) })}><TermsFields award={award} /></ExecutionAction>; }

export function AwardLifecycleActions({ award, apiBase, unresolvedRequired }: { award: AwardTerms; apiBase: string; unresolvedRequired: number }) { const targets: Record<string, string[]> = { PREPARING: ["ACTIVE", "CANCELLED"], ACTIVE: ["SUSPENDED", "COMPLETED", "TERMINATED"], SUSPENDED: ["ACTIVE", "COMPLETED", "TERMINATED"] }; const actionLabels: Record<string, string> = { ACTIVE: award.status === "SUSPENDED" ? "Retomar execução" : "Ativar apoio", SUSPENDED: "Suspender execução", COMPLETED: "Concluir execução", TERMINATED: "Encerrar antecipadamente", CANCELLED: "Cancelar apoio" }; return <div className="flex flex-wrap gap-3">{(targets[award.status] ?? []).map((status) => <ExecutionAction key={status} label={actionLabels[status]} title={actionLabels[status]} apiUrl={`${apiBase}/status`} disabled={status === "ACTIVE" && !award.startsAt || status === "COMPLETED" && unresolvedRequired > 0} input={(data) => ({ revision: award.revision, status, reason: optionalValue(data, "reason"), confirmed: data.get("confirmed") === "on" })}><p className="text-sm leading-6 text-slate">O apoio passará para “{awardStatusLabels[status]}”.{status === "SUSPENDED" ? " Os prazos ficam preservados e novos envios ficam suspensos." : status === "COMPLETED" ? " As entregas obrigatórias estão aprovadas ou dispensadas. O histórico e o acompanhamento serão preservados." : status === "ACTIVE" ? " Confirme que os termos estão prontos e que a execução pode começar." : " Os registros e as versões enviadas serão preservados."}</p><TextField label="Motivo" name="reason" required={["SUSPENDED", "TERMINATED", "CANCELLED"].includes(status)} maxLength={2000} /><label className="flex min-h-11 items-start gap-3 text-sm leading-6"><input type="checkbox" className="mt-1 h-5 w-5 shrink-0 accent-accent" name="confirmed" required /><span>Confirmo esta mudança no apoio.</span></label></ExecutionAction>)}{award.status === "PREPARING" && !award.startsAt ? <p className="basis-full text-sm text-slate">Informe o início da execução nos termos antes de ativar o apoio.</p> : null}{["ACTIVE", "SUSPENDED"].includes(award.status) && unresolvedRequired > 0 ? <p className="basis-full text-sm text-slate">Há {unresolvedRequired} obrigação(ões) obrigatória(s) ainda sem aprovação ou dispensa.</p> : null}</div>; }
