"use client";

import { ExecutionAction, FormField, TextField, optionalValue } from "@/components/execution/award-actions";
import { documentTypeLabels } from "@/components/execution/presentation";

type Disbursement = { id: string; revision: number; label: string; amount: string; plannedFor: string | null; status: string; paidAt: string | null; externalReference: string | null; note: string | null };
type AwardDocument = { id: string; type: string; title: string; url: string; visibleToParticipant: boolean };
function DisbursementFields({ item }: { item?: Disbursement }) { return <><FormField label="Identificação da parcela" name="label" value={item?.label} required maxLength={200} /><div className="grid gap-4 sm:grid-cols-2"><FormField label="Valor (R$)" name="amount" type="number" value={item?.amount} required /><FormField label="Data prevista" name="plannedFor" type="date" value={item?.plannedFor} /></div><TextField label="Observação compartilhada com o projeto" name="note" value={item?.note} maxLength={2000} /></>; }
function disbursementInput(data: FormData) { return { label: String(data.get("label") ?? "").trim(), amount: String(data.get("amount") ?? ""), plannedFor: optionalValue(data, "plannedFor"), externalReference: optionalValue(data, "externalReference"), note: optionalValue(data, "note") }; }
export function CreateDisbursement({ apiBase }: { apiBase: string }) { return <ExecutionAction label="Prever desembolso" title="Registrar desembolso previsto" description="Este registro acompanha uma parcela do apoio." apiUrl={`${apiBase}/disbursements`} input={disbursementInput}><DisbursementFields /></ExecutionAction>; }
export function DisbursementActions({ item, apiBase }: { item: Disbursement; apiBase: string }) { if (item.status !== "PLANNED") return null; const url = `${apiBase}/disbursements/${item.id}`; const preserved = { revision: item.revision, label: item.label, amount: item.amount, plannedFor: item.plannedFor, externalReference: item.externalReference, note: item.note }; return <div className="flex flex-wrap gap-2"><ExecutionAction label="Editar previsão" title="Editar desembolso previsto" apiUrl={url} method="PATCH" input={(data) => ({ revision: item.revision, status: "PLANNED", ...disbursementInput(data) })}><DisbursementFields item={item} /><FormField label="Referência externa" name="externalReference" value={item.externalReference} maxLength={200} /></ExecutionAction><ExecutionAction label="Registrar pagamento" title="Registrar parcela paga" description="Confirme a ocorrência do desembolso. O valor e a referência serão preservados." apiUrl={url} method="PATCH" input={(data) => ({ ...preserved, status: "PAID", paidAt: String(data.get("paidAt") ?? ""), externalReference: optionalValue(data, "externalReference") })}><p className="text-sm leading-6 text-slate">{item.label}</p><FormField label="Data do pagamento" name="paidAt" type="date" required /><FormField label="Referência externa" name="externalReference" value={item.externalReference} maxLength={200} /><label className="flex min-h-11 items-start gap-3 text-sm leading-6"><input type="checkbox" className="mt-1 h-5 w-5 shrink-0 accent-accent" required /><span>Confirmo que a parcela foi paga.</span></label></ExecutionAction><ExecutionAction label="Cancelar previsão" title="Cancelar desembolso previsto" apiUrl={url} method="PATCH" input={(data) => ({ ...preserved, status: "CANCELLED", note: String(data.get("note") ?? "").trim() })}><TextField label="Motivo do cancelamento" name="note" required maxLength={2000} /></ExecutionAction></div>; }
function DocumentFields({ document }: { document?: AwardDocument }) { return <><label className="block space-y-2 text-sm font-medium"><span>Tipo</span><select className="field-control" name="type" defaultValue={document?.type ?? "AGREEMENT"}>{Object.entries(documentTypeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><FormField label="Título" name="title" required value={document?.title} maxLength={200} /><FormField label="Link HTTPS" name="url" type="url" required value={document?.url} maxLength={2000} hint="Confira as permissões do documento no serviço de origem." /><label className="flex min-h-11 items-start gap-3 text-sm leading-6"><input className="mt-1 h-5 w-5 shrink-0 accent-accent" type="checkbox" name="visibleToParticipant" defaultChecked={document?.visibleToParticipant ?? true} /><span>Disponível aos participantes do projeto</span></label></>; }
function documentInput(data: FormData) { return { type: String(data.get("type")), title: String(data.get("title") ?? "").trim(), url: String(data.get("url") ?? "").trim(), visibleToParticipant: data.get("visibleToParticipant") === "on" }; }
export function CreateAwardDocument({ apiBase }: { apiBase: string }) { return <ExecutionAction label="Adicionar documento" title="Adicionar documento do apoio" apiUrl={`${apiBase}/documents`} input={documentInput}><DocumentFields /></ExecutionAction>; }
