"use client";

import { ExecutionAction, FormField, TextField, optionalValue } from "@/components/execution/award-actions";
import { obligationTypeLabels } from "@/components/execution/presentation";

type ObligationInput = { id: string; revision: number; type: string; title: string; description: string | null; periodStartsAt: string | null; periodEndsAt: string | null; dueAt: string | null; required: boolean; position: number; waivedAt: string | null; submissions: Array<{ status: string; reviewStatus: string | null }> };

function ObligationFields({ obligation }: { obligation?: ObligationInput }) { return <><label className="block space-y-2 text-sm font-medium"><span>Tipo *</span><select className="field-control" name="type" defaultValue={obligation?.type ?? "DELIVERABLE"}>{Object.entries(obligationTypeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><FormField label="Título" name="title" value={obligation?.title} required maxLength={200} /><TextField label="Orientações para a entrega" name="description" value={obligation?.description} maxLength={6000} /><div className="grid gap-4 sm:grid-cols-2"><FormField label="Prazo de entrega" name="dueAt" value={obligation?.dueAt} type="date" /><label className="block space-y-2 text-sm font-medium"><span>Ordem no plano</span><input className="field-control" type="number" name="position" min={0} max={199} step={1} defaultValue={obligation?.position ?? 0} /></label><FormField label="Período coberto · início" name="periodStartsAt" value={obligation?.periodStartsAt} type="date" /><FormField label="Período coberto · fim" name="periodEndsAt" value={obligation?.periodEndsAt} type="date" /></div><label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" name="required" className="h-5 w-5 accent-accent" defaultChecked={obligation?.required ?? true} /><span>Obrigatória para concluir a execução</span></label></>; }
function obligationInput(data: FormData) { return { type: String(data.get("type")), title: String(data.get("title") ?? "").trim(), description: optionalValue(data, "description"), dueAt: optionalValue(data, "dueAt"), periodStartsAt: optionalValue(data, "periodStartsAt"), periodEndsAt: optionalValue(data, "periodEndsAt"), position: Number(data.get("position") ?? 0), required: data.get("required") === "on" }; }

export function CreateObligation({ apiBase }: { apiBase: string }) { return <ExecutionAction label="Programar entrega" title="Programar entrega ou relatório" description="O plano de trabalho reúne as obrigações formais do apoio." apiUrl={`${apiBase}/obligations`} input={obligationInput}><ObligationFields /></ExecutionAction>; }

export function ObligationActions({ obligation, apiBase }: { obligation: ObligationInput; apiBase: string }) { const submitted = obligation.submissions.some((submission) => submission.status === "SUBMITTED"); const resolved = Boolean(obligation.waivedAt) || obligation.submissions.some((submission) => submission.reviewStatus === "APPROVED"); if (resolved) return null; const url = `${apiBase}/obligations/${obligation.id}`; return <div className="flex flex-wrap gap-2">{!submitted ? <ExecutionAction label="Editar entrega" title="Editar entrega" apiUrl={url} method="PATCH" input={(data) => ({ revision: obligation.revision, ...obligationInput(data) })}><ObligationFields obligation={obligation} /></ExecutionAction> : null}<ExecutionAction label="Reprogramar prazo" title="Reprogramar prazo da entrega" description="O prazo anterior e o motivo da mudança ficam no histórico." apiUrl={`${url}/reschedule`} input={(data) => ({ revision: obligation.revision, dueAt: optionalValue(data, "dueAt"), reason: String(data.get("reason") ?? "").trim() })}><p className="text-sm leading-6 text-slate">{obligation.title}</p><FormField label="Novo prazo" name="dueAt" type="date" value={obligation.dueAt} /><TextField label="Motivo da reprogramação" name="reason" required maxLength={2000} /></ExecutionAction><ExecutionAction label="Dispensar" title="Dispensar obrigação" description="A dispensa encerra esta obrigação e preserva as versões enviadas." apiUrl={`${url}/waive`} input={(data) => ({ revision: obligation.revision, reason: String(data.get("reason") ?? "").trim() })}><p className="text-sm leading-6 text-slate">{obligation.title}</p><TextField label="Motivo da dispensa" name="reason" required maxLength={2000} /></ExecutionAction></div>; }
