export const awardStatusLabels: Record<string, string> = { PREPARING: "Apoio em preparação", ACTIVE: "Em execução", SUSPENDED: "Execução suspensa", COMPLETED: "Execução concluída", TERMINATED: "Execução encerrada antecipadamente", CANCELLED: "Apoio cancelado" };
export const obligationTypeLabels: Record<string, string> = { DELIVERABLE: "Entrega", PROGRESS_REPORT: "Relatório de acompanhamento", FINAL_REPORT: "Relatório final", FINANCIAL_REPORT: "Prestação financeira", OTHER: "Outro" };
export const obligationStateLabels: Record<string, string> = { PENDING: "Pendente", DRAFT: "Em elaboração", SUBMITTED: "Aguardando análise", CHANGES_REQUESTED: "Ajustes solicitados", APPROVED: "Aprovado", REJECTED: "Rejeitado", WAIVED: "Dispensado", OVERDUE: "Em atraso" };
export const reviewStatusLabels: Record<string, string> = { PENDING: "Aguardando análise", APPROVED: "Aprovado", CHANGES_REQUESTED: "Ajustes solicitados", REJECTED: "Rejeitado" };
export const disbursementStatusLabels: Record<string, string> = { PLANNED: "Previsto", PAID: "Pago", CANCELLED: "Cancelado" };
export const documentTypeLabels: Record<string, string> = { AGREEMENT: "Termo de apoio", AMENDMENT: "Aditivo", TECHNICAL: "Documento técnico", FINANCIAL: "Documento financeiro", OTHER: "Outro" };
export function executionTone(status: string): "neutral" | "accent" | "success" | "warning" | "danger" { return ["ACTIVE", "APPROVED", "PAID", "COMPLETED"].includes(status) ? "success" : ["OVERDUE", "REJECTED", "TERMINATED"].includes(status) ? "danger" : ["SUSPENDED", "CHANGES_REQUESTED"].includes(status) ? "warning" : ["SUBMITTED", "PREPARING"].includes(status) ? "accent" : "neutral"; }
export function moneyLabel(amount: string | null) { return amount === null ? "Apoio sem valor financeiro informado" : new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(amount)); }
export function documentHost(url: string) { try { return new URL(url).hostname; } catch { return "Link externo"; } }
