import { IMPORT_TEMPLATES, type ImportEntityType } from "@/lib/imports/templates";

export const IMPORT_STATUS_LABELS: Record<string, string> = {
  UPLOADED: "Aguardando conferência", VALIDATING: "Em validação", READY: "Pronto para aplicar", APPLYING: "Em aplicação", APPLIED: "Aplicado", FAILED: "Requer revisão", ROLLED_BACK: "Revertido",
  PENDING: "Ainda não validada", VALID: "Válida", INVALID: "Com erro", SKIPPED: "Ignorada",
};
const messages: Record<string, string> = {
  IMPORT_ORIGIN_REJECTED: "Este envio não veio da página do Atlas. Abra a importação no endereço da plataforma.",
  CSV_EMPTY: "O arquivo está vazio. Inclua o cabeçalho e pelo menos uma linha de dados.",
  CSV_NO_ROWS: "Inclua pelo menos uma linha de dados abaixo do cabeçalho.",
  CSV_INVALID_UTF8: "Salve o arquivo CSV com codificação UTF-8 e tente novamente.",
  CSV_EXTENSION_INVALID: "Selecione um arquivo com extensão .csv.",
  CSV_FILE_TOO_LARGE: "O arquivo excede 2 MiB. Divida os dados em lotes menores.",
  CSV_TOO_MANY_ROWS: "Use no máximo 1.000 linhas por lote.",
  CSV_TOO_MANY_COLUMNS: "Use no máximo 64 colunas.",
  CSV_CELL_TOO_LONG: "Uma célula excede 4.000 caracteres. Reduza seu conteúdo.",
  CSV_HEADER_TOO_LONG: "Use cabeçalhos com até 120 caracteres.",
  CSV_EMPTY_HEADER: "Toda coluna precisa de um cabeçalho.",
  CSV_DUPLICATE_HEADER: "Existem cabeçalhos repetidos. Dê um nome único a cada coluna.",
  CSV_RESERVED_HEADER: "Um cabeçalho usa um nome reservado. Renomeie a coluna.",
  CSV_CONTROL_CHARACTER: "O arquivo contém caracteres de controle incompatíveis. Exporte novamente como CSV UTF-8.",
  CSV_COLUMN_COUNT: "A quantidade de células não corresponde ao cabeçalho. Confira separadores e aspas.",
  CSV_DELIMITER_AMBIGUOUS: "O separador está ambíguo. Escolha vírgula ou ponto e vírgula.",
  CSV_DELIMITER_INVALID: "Escolha um dos separadores disponíveis.",
  CSV_UNCLOSED_QUOTE: "Há um campo entre aspas sem fechamento.",
  CSV_UNEXPECTED_QUOTE: "Há aspas em posição inválida. Exporte novamente o CSV.",
  CSV_AFTER_QUOTE: "Há conteúdo após o fechamento das aspas de uma célula.",
  IMPORT_BODY_TOO_LARGE: "O envio excede o limite. Reduza o arquivo ou os dados informados.",
  IMPORT_BODY_EMPTY: "O envio está vazio. Selecione o arquivo novamente.",
  IMPORT_CONTENT_TYPE: "O formato do envio não é compatível. Recarregue a página e tente novamente.",
  IMPORT_JSON_INVALID: "Não foi possível ler os dados enviados. Recarregue a página.",
  IMPORT_FORM_INVALID: "O envio contém campos inválidos ou repetidos. Revise o formulário.",
  IMPORT_FILE_REQUIRED: "Selecione um arquivo CSV.",
  IMPORT_BATCH_NOT_FOUND: "A importação não foi encontrada nesta instituição.",
  IMPORT_BATCH_IMMUTABLE: "Este lote já foi aplicado ou revertido. Seu conteúdo está preservado.",
  IMPORT_MAPPING_REQUIRED: "Confira e confirme o mapeamento antes de validar.",
  IMPORT_MAPPING_FIELD: "Um campo do mapeamento não pertence ao tipo selecionado.",
  IMPORT_MAPPING_HEADER: "Uma coluna selecionada não existe no arquivo.",
  IMPORT_MAPPING_DUPLICATE: "Uma coluna foi atribuída a mais de um campo. Revise as seleções.",
  IMPORT_MAPPING_REFERENCE: "Mapeie os identificadores necessários para localizar os registros relacionados.",
  IMPORT_MAPPING_AMBIGUOUS_REFERENCE: "Escolha uma única forma de identificar cada registro relacionado.",
  IMPORT_FIELD_INVALID: "O valor não atende ao formato ou ao limite deste campo. Consulte a orientação do modelo.",
  IMPORT_FIELD_REQUIRED: "Preencha este campo obrigatório com o valor real da origem.",
  IMPORT_INTEGER_INVALID: "Informe um inteiro não negativo, sem decimais ou separadores de milhar.",
  IMPORT_BOOLEAN_INVALID: "Use true ou false para indicar a ausência de valor.",
  IMPORT_DATE_INVALID: "Informe uma data existente no formato AAAA-MM-DD, a partir de 1900.",
  IMPORT_TIMESTAMP_INVALID: "Informe data e hora ISO com fuso, como 2024-01-01T09:00:00-03:00.",
  IMPORT_DATE_ORDER: "As datas estão fora de ordem. Confira ingresso, início, encerramento e envio.",
  IMPORT_WITHDRAWAL_REQUIRED: "Uma participação encerrada precisa da data real de saída.",
  IMPORT_WITHDRAWAL_CONFLICT: "Uma participação ativa não pode ter data de saída.",
  IMPORT_RESULTS_DATE_REQUIRED: "Informe a data histórica de publicação do resultado.",
  IMPORT_MISSING_CONFLICT: "Quando a ausência for true, deixe o valor vazio. Zero é um valor informado.",
  IMPORT_SUBMISSION_CONFLICT: "A data de envio exige a situação SUBMITTED.",
  IMPORT_STATUS_VALUE_CONFLICT: "Observações pendentes ou não respondidas não podem conter valores.",
  IMPORT_REFERENCE_REQUIRED: "Informe o identificador do registro relacionado.",
  IMPORT_REFERENCE_NOT_FOUND: "O identificador não foi localizado nesta instituição e origem. Confira o vínculo e a ordem dos lotes.",
  IMPORT_REFERENCE_AMBIGUOUS: "As referências apontam para registros diferentes. Use uma única identificação coerente.",
  IMPORT_REFERENCE_CHANGED: "As referências mudaram desde a prévia. Valide novamente antes de aplicar.",
  IMPORT_EXTERNAL_REFERENCE_STALE: "O vínculo da origem aponta para um registro indisponível. Revise o histórico antes de continuar.",
  IMPORT_ALREADY_IMPORTED: "Este identificador já foi importado nesta origem e tipo.",
  IMPORT_DUPLICATE_ROW: "Há outra linha com a mesma identidade. Remova a duplicidade no arquivo.",
  IMPORT_IDENTITY_CONFLICT: "Já existe um registro com essa identidade no Atlas. Use o vínculo de origem correto.",
  IMPORT_UPSERT_UNAVAILABLE: "A atualização de metadados está disponível apenas para programas e empreendimentos.",
  IMPORT_UPSERT_IDENTITY: "A atualização preserva o identificador de URL e o tipo do registro existente.",
  IMPORT_UPSERT_LIFECYCLE: "A atualização de metadados preserva a situação e o arquivamento existentes.",
  IMPORT_OFFSET_AMBIGUOUS: "Mais de uma onda corresponde a esse período. Identifique a onda diretamente ou corrija a ambiguidade.",
  IMPORT_INDICATOR_NOT_FOUND: "A chave não existe na versão do protocolo desta coorte.",
  IMPORT_OBSERVATION_GROUP_CONFLICT: "As linhas da mesma observação precisam ter participação, onda, situação e datas iguais.",
  IMPORT_OBSERVATION_MULTIPLE_IDENTITIES: "Uma participação e onda devem usar um único identificador de observação.",
  IMPORT_OBSERVATION_HISTORY_EXISTS: "Já existe preenchimento ou histórico nesta observação. A importação não o substitui.",
  IMPORT_ENTITY_LIMIT: "O lote afetaria mais de 5.000 registros, incluindo observações geradas. Divida o lote ou reduza o recorte.",
  IMPORT_NOT_READY: "Valide o lote inteiro e corrija todos os erros antes de aplicar.",
  IMPORT_REVALIDATION_FAILED: "Os registros mudaram ou surgiram conflitos. Nenhuma linha foi aplicada. Valide novamente.",
  IMPORT_REVISION_CONFLICT: "Este lote mudou em outra janela. Consulte o estado atual; suas escolhas permanecem no formulário.",
  IMPORT_VALIDATION_FAILED: "Corrija as linhas indicadas e carregue um novo arquivo, ou ajuste o mapeamento deste lote.",
  IMPORT_APPLY_FAILED: "A aplicação falhou e foi desfeita integralmente. Confira o estado do lote antes de tentar novamente.",
  IMPORT_NOT_APPLIED: "A reversão está disponível apenas para lotes aplicados.",
  IMPORT_ROLLBACK_BLOCKED: "A reversão foi bloqueada para preservar alterações ou dependências. Confira os motivos na prévia.",
  IMPORT_RECORD_CHANGED: "O registro ou seus valores mudaram após a importação.",
  IMPORT_RECORD_MISSING: "Um registro aplicado não está mais disponível para conferência.",
  IMPORT_DEPENDENT_RECORDS: "Existem registros dependentes que não pertencem a este lote.",
  IMPORT_LATER_BATCH_DEPENDENCY: "Uma importação posterior utiliza ou alterou este registro. Confira primeiro esse histórico.",
  IMPORT_EXTERNAL_REFERENCE_DEPENDENCY: "Outra origem ou lote possui um vínculo ativo com este registro.",
  IMPORT_FROZEN_ANALYSIS_DEPENDENCY: "Um relatório ou exportação preservou dados deste recorte após a importação.",
  IMPORT_AUDIT_INCOMPLETE: "A evidência de auditoria está incompleta. A operação foi bloqueada.",
  IMPORT_SOURCE_INCOMPLETE: "A evidência original do lote está incompleta. A operação foi bloqueada.",
  IMPORT_RESTORE_UNAVAILABLE: "Este registro não pode ser restaurado automaticamente com a evidência disponível.",
  IMPORT_ROLLBACK_CHANGED: "Os registros mudaram durante a reversão. Nenhuma alteração da reversão foi mantida.",
  IMPORT_CALL_PRIVATE: "O edital será criado sem divulgação pública e sem receber candidaturas pelo Atlas.",
  IMPORT_COHORT_WITHOUT_PROTOCOL: "A coorte ficará sem protocolo. Configure uma versão antes de importar ondas.",
  IMPORT_WAVE_WITHOUT_OFFSET: "Sem meses desde a referência, esta onda não entra em comparações por período.",
  IMPORT_VALUE_MISSING: "O valor continuará ausente e não será convertido em zero.",
  IMPORT_PENDING_PLACEHOLDER: "A observação vazia já prevista será preenchida; seu estado anterior ficará registrado para eventual reversão.",
  OBSERVATION_INTEGER_INVALID: "Informe um inteiro não negativo de até 2.147.483.647.",
  OBSERVATION_CURRENCY_INVALID: "Informe decimal não negativo com ponto, até 12 dígitos inteiros e duas casas decimais.",
  OBSERVATION_ENUM_INVALID: "Use uma das opções exatas previstas pelo indicador no protocolo.",
  OBSERVATION_INDICATOR_DUPLICATE: "O mesmo indicador aparece mais de uma vez nesta observação.",
  OBSERVATION_SUBMISSION_EMPTY: "Uma observação enviada precisa de pelo menos um valor real. Ausências continuam sem valor.",
  OBSERVATION_ENROLLMENT_NOT_ELIGIBLE: "A participação não estava vigente na data de referência da onda.",
  OBSERVATION_PROTOCOL_MISSING: "A coorte precisa de uma versão de protocolo com indicadores.",
  COHORT_SCOPE_MISMATCH: "A participação e a onda precisam pertencer à mesma coorte.",
  COHORT_PROTOCOL_REQUIRED: "Defina o protocolo da coorte antes de importar ondas.",
  PROTOCOL_HAS_NO_INDICATORS: "A versão de protocolo selecionada precisa conter indicadores.",
  FUNDING_CALL_PROGRAM_MISMATCH: "O edital precisa pertencer ao programa informado para a coorte.",
  BASELINE_SEQUENCE_INVALID: "Use sequência 0 para a baseline.",
  FOLLOW_UP_SEQUENCE_INVALID: "Use sequência positiva para uma onda de acompanhamento.",
};

export function importMessage(code: string) {
  return messages[code] ?? "Não foi possível concluir esta etapa. Revise os dados e consulte o estado atual do lote.";
}
export function importFieldLabel(type: ImportEntityType, field: string) {
  return IMPORT_TEMPLATES[type].fields.find((item) => item.key === field || item.key === `${field}_external_id`)?.label ?? "Campo informado";
}
