import Link from "next/link";
import { PageHeader } from "@/components/ui";
import { getAnalyticsAccess, queryValue, queryValues, type AnalyticsSearchParams } from "@/components/analytics/access";
import { AnalyticsNavigation } from "@/components/analytics/navigation";
import { AnalyticsEmpty, AnalyticsSection, AnalyticsTable, ScopeNote, primaryValue, aggregationLabels } from "@/components/analytics/presentation";
import { getAnalyticsChoices, compareCohortAnalytics } from "@/lib/analytics/read-model";
import { evidenceHref } from "@/components/analytics/views";

const comparisonMessages = { MISSING_OFFSET: "Esta coorte não possui uma onda no mês de referência escolhido.", AMBIGUOUS_OFFSET: "Há mais de uma onda neste mês de referência. Resolva a ambiguidade antes de comparar.", UNMAPPED_METRIC: "O protocolo desta coorte não está associado à métrica escolhida.", INCOMPATIBLE_METRIC: "O indicador desta coorte possui semântica incompatível com a métrica." } as const;

export default async function AnalyticsComparePage({ searchParams }: { searchParams: Promise<AnalyticsSearchParams> }) {
  const { access, canAnalyze } = await getAnalyticsAccess();
  const parameters = await searchParams;
  const programId = queryValue(parameters, "programId");
  const cohortIds = queryValues(parameters, "cohortId");
  const metricId = queryValue(parameters, "metricId");
  const rawOffsets = queryValues(parameters, "offsetMonths");
  const offsets = rawOffsets.map(Number);
  const requested = Boolean(cohortIds.length || metricId || rawOffsets.length);
  const valid = cohortIds.length >= 2 && cohortIds.length <= 6 && new Set(cohortIds).size === cohortIds.length && metricId && offsets.length >= 1 && offsets.length <= 6 && offsets.every((offset) => Number.isSafeInteger(offset) && offset >= 0) && new Set(offsets).size === offsets.length;
  const choices = await getAnalyticsChoices(access);
  const eligibleCohorts = choices.cohorts.filter((cohort) => !programId || cohort.programId === programId);
  const validChoices = cohortIds.every((id) => eligibleCohorts.some((cohort) => cohort.id === id)) && choices.metrics.some((metric) => metric.id === metricId) && offsets.every((offset) => choices.offsetMonths.includes(offset));
  const comparison = valid && validChoices ? await compareCohortAnalytics(access, { programId: programId || undefined, cohortIds, metricId, offsetMonths: offsets }) : null;
  return <div className="min-w-0 space-y-6"><PageHeader title="Comparar coortes" description="Uma métrica canônica, de duas a seis coortes e meses de referência explícitos." /><AnalyticsNavigation current="/app/analytics/compare" canConfigure={canAnalyze} /><ScopeNote>A comparação usa o vínculo explícito com a mesma métrica e o mês de referência da onda. Nomes e números de sequência não determinam comparabilidade; os respondentes podem variar entre coortes e ondas.</ScopeNote>
    <form method="get" action="/app/analytics/compare" className="flex flex-wrap items-end gap-3"><label className="min-w-0 flex-1 text-sm font-medium">Filtrar coortes por programa<select name="programId" defaultValue={programId} className="field-control mt-2"><option value="">Todos os programas</option>{choices.programs.map((program) => <option key={program.id} value={program.id}>{program.name}</option>)}</select></label><button type="submit" className="button-secondary">Filtrar coortes</button></form>
    <AnalyticsSection title="Preparar comparação" description="Aplique o filtro de programa acima, se necessário, e escolha os grupos e os momentos."><form method="get" action="/app/analytics/compare" className="space-y-5 p-4 sm:p-6">{programId ? <input type="hidden" name="programId" value={programId} /> : null}<fieldset><legend className="text-sm font-semibold">Coortes · escolha de 2 a 6</legend>{eligibleCohorts.length ? <div className="analytics-choices mt-3">{eligibleCohorts.map((cohort) => <label key={cohort.id}><input type="checkbox" name="cohortId" value={cohort.id} defaultChecked={cohortIds.includes(cohort.id)} /><span>{cohort.name}</span></label>)}</div> : <p className="mt-2 text-sm text-slate">Nenhuma coorte disponível neste programa.</p>}</fieldset><label className="block text-sm font-semibold">Métrica canônica<select className="field-control mt-2" name="metricId" defaultValue={metricId} required><option value="">Selecione uma métrica</option>{choices.metrics.map((metric) => <option key={metric.id} value={metric.id}>{metric.label}</option>)}</select></label><fieldset><legend className="text-sm font-semibold">Meses de referência · escolha de 1 a 6</legend><div className="analytics-choices mt-3">{choices.offsetMonths.map((offset) => <label key={offset}><input type="checkbox" name="offsetMonths" value={offset} defaultChecked={offsets.includes(offset)} /><span>{offset === 0 ? "0 meses · baseline" : `${offset} meses`}</span></label>)}</div>{!choices.offsetMonths.length ? <p className="mt-2 text-sm text-slate">As ondas ainda não possuem meses de referência definidos.</p> : null}</fieldset><div className="flex flex-wrap gap-2"><button type="submit" className="button-primary" disabled={eligibleCohorts.length < 2 || !choices.metrics.length || !choices.offsetMonths.length}>Comparar evidências</button><Link href="/app/analytics/compare" className="button-secondary">Limpar seleção</Link></div></form></AnalyticsSection>
    {requested && (!valid || !validChoices) ? <p role="alert" className="analytics-note text-warning">Escolha de duas a seis coortes do recorte atual, uma métrica disponível e de um a seis meses distintos. Nenhum resultado foi calculado para a seleção inválida.</p> : null}
    {comparison ? <AnalyticsSection title={comparison.metric.label} description={`${aggregationLabels[comparison.metric.primaryAggregation]} · ${comparison.cohorts.length} coortes · ${offsets.join(", ")} meses`}><AnalyticsTable caption="Comparação transversal: universo esperado, observações enviadas e valores válidos por coorte e mês de referência." headings={["Coorte", "Mês / onda", "Esperadas", "Enviadas", "n válido", "Resultado", "Condição / origem"]} rows={comparison.cells.map((cell) => [<Link key="cohort" className="analytics-link" href={`/app/analytics/cohorts/${cell.cohortId}`}>{cell.cohortName}</Link>, <>{cell.offsetMonths} meses<span className="mt-1 block text-xs text-slate">{cell.waveName ?? "Sem onda inequívoca"}</span></>, cell.coverage?.expected ?? "—", cell.coverage?.submitted ?? "—", cell.aggregate?.validCount ?? "—", cell.aggregate ? primaryValue(cell.aggregate) : "Não comparável", cell.status === "READY" ? <><span className="text-xs text-slate">{cell.aggregate?.missingCount ?? 0} valores ausentes</span>{canAnalyze && cell.waveId ? <Link className="analytics-link mt-1 block" href={evidenceHref(cell.cohortId, cell.waveId, comparison.metric.id)}>Ver composição</Link> : null}</> : comparisonMessages[cell.status]])} /></AnalyticsSection> : <AnalyticsEmpty title="Escolha o recorte para comparar" description="Os resultados serão apresentados com os valores válidos e as limitações de cada célula, sem transformar dados ausentes em zero." />}
  </div>;
}
