import Link from "next/link";

import { AnalyticsEmpty, AnalyticsSection, AnalyticsTable, CoverageSummary, MetricResult, ScopeNote, SummaryStrip, Timepoint, formatIndicatorValue, formatMonitoringDate, primaryValue, aggregationLabels } from "@/components/analytics/presentation";
import type { CohortAnalytics, DataQualityAnalytics, ExecutionAnalytics, PortfolioAnalytics } from "@/lib/analytics/types";
import { milestoneLabels } from "@/lib/milestones/labels";

const awardStatusLabels: Record<string, string> = { DRAFT: "Rascunho", PREPARING: "Em preparação", ACTIVE: "Ativo", COMPLETED: "Concluído", SUSPENDED: "Suspenso", TERMINATED: "Encerrado", CANCELLED: "Cancelado", ARCHIVED: "Arquivado" };

export function ExecutionView({ execution }: { execution: ExecutionAnalytics }) {
  const financial = execution.financial;
  return <AnalyticsSection title="Execução dos apoios" description="Entregas e repasses registrados. Estes dados representam a execução, com universo próprio."><SummaryStrip items={[{ label: "Apoios", value: execution.awards }, { label: "Obrigações aprovadas", value: execution.approvedObligations, detail: `${execution.requiredObligations} obrigações obrigatórias no recorte` }, { label: "Obrigações em atraso", value: execution.overdueObligations }, { label: "Análises pendentes", value: execution.pendingReviews }]} /><AnalyticsTable caption="Apoios por situação registrada" headings={["Situação", "Apoios"]} rows={execution.byStatus.map((row) => [awardStatusLabels[row.status] ?? "Situação não disponível", row.count])} /><AnalyticsTable caption="Valores financeiros observados; n identifica projetos distintos com valor. Apoios sem valor financeiro não entram no denominador." headings={["Registro financeiro", "Valor", "Projetos com valor"]} rows={[["Aprovado", formatIndicatorValue(financial.approved, "CURRENCY", "R$"), financial.approvedCount], ["Desembolsos previstos", formatIndicatorValue(financial.planned, "CURRENCY", "R$"), financial.plannedCount], ["Desembolsos realizados", formatIndicatorValue(financial.paid, "CURRENCY", "R$"), financial.paidCount]]} /></AnalyticsSection>;
}

export function ApplicationsView({ calls }: { calls: PortfolioAnalytics["calls"] }) {
  return <AnalyticsSection title="Editais e seleção" description={`${calls.total} editais no recorte · ${calls.applicationsObserved} com candidaturas observadas na plataforma.`}><AnalyticsTable caption="Contagens registradas na plataforma; ausência de candidaturas na plataforma não comprova ausência de interessados." headings={["Registro", "Candidaturas"]} rows={[["Enviadas", calls.submitted ?? "Não observado"], ["Retiradas", calls.withdrawn ?? "Não observado"], ["Com avaliação enviada", calls.evaluated ?? "Não observado"], ["Selecionadas", calls.selected ?? "Não observado"]]} /></AnalyticsSection>;
}

export function PortfolioView({ data, canAnalyze = false, report = false }: { data: PortfolioAnalytics; canAnalyze?: boolean; report?: boolean }) {
  return <div className="space-y-6"><SummaryStrip items={[{ label: "Programas no recorte", value: data.programs.length }, { label: "Apoios", value: data.execution.awards }, { label: "Empreendimentos acompanhados", value: data.trackedVentures, detail: "Identidades distintas" }, { label: "Observações enviadas", value: `${data.monitoring.submitted}/${data.monitoring.expected}`, detail: "Observações esperadas no recorte" }]} />
    <AnalyticsSection title="Programas" description="Acesse o contexto do programa para interpretar as evidências.">{data.programs.length ? <AnalyticsTable caption="Programas incluídos neste recorte institucional" headings={["Programa", "Editais", "Coortes", "Empreendimentos", "Apoios ativos"]} rows={data.programs.map((program) => [report ? program.name : <Link className="analytics-link" href={`/app/analytics/programs/${program.id}`}>{program.name}</Link>, program.calls, program.cohorts, program.trackedVentures, program.activeAwards])} /> : <AnalyticsEmpty title="Nenhum programa neste recorte" description="Cadastre um programa ou amplie os filtros para consultar a evidência institucional." />}</AnalyticsSection>
    <div className="grid items-start gap-6 xl:grid-cols-2"><ApplicationsView calls={data.calls} /><ExecutionView execution={data.execution} /></div>
    <AnalyticsSection title="Cobertura do acompanhamento" description="Envios e elegibilidade por coorte e onda. Cobertura é diferente da presença de valor válido para cada métrica.">{data.cohorts.some((cohort) => cohort.waves.length) ? <AnalyticsTable caption="Observações enviadas em relação ao universo elegível de cada onda" headings={["Coorte", "Onda / referência", "Esperadas", "Enviadas", "Não respondidas"]} rows={data.cohorts.flatMap((cohort) => cohort.waves.map((wave) => [report ? cohort.name : <Link href={`/app/analytics/cohorts/${cohort.id}`} className="analytics-link">{cohort.name}</Link>, <Timepoint key="wave" name={wave.name} offsetMonths={wave.offsetMonths} />, wave.coverage.expected, wave.coverage.submitted, wave.coverage.missed]))} /> : <AnalyticsEmpty title="O acompanhamento ainda não possui ondas" description="Crie uma onda e envie observações para iniciar a leitura da cobertura." />}</AnalyticsSection>
    <AnalyticsSection title="Resultados observados" description="Cada valor preserva a coorte, a métrica canônica e o momento observado. Coortes não são somadas automaticamente.">{data.cohorts.some((cohort) => cohort.waves.some((wave) => wave.metrics.length)) ? <AnalyticsTable caption="Agregação principal por métrica e onda; n conta valores válidos entre as observações enviadas." headings={["Coorte / onda", "Métrica", "Resultado", "n válido", "Valores ausentes", "Origem"]} rows={data.cohorts.flatMap((cohort) => cohort.waves.flatMap((wave) => wave.metrics.map((metric) => [<><span className="font-medium">{cohort.name}</span><span className="mt-1 block text-xs text-slate"><Timepoint name={wave.name} offsetMonths={wave.offsetMonths} /></span></>, metric.label, <div key="aggregate"><span>{primaryValue(metric)}</span><span className="mt-1 block text-xs text-slate">{aggregationLabels[metric.primaryAggregation]} dos valores válidos</span></div>, metric.validCount, metric.missingCount, canAnalyze && !report ? <Link className="analytics-link" href={evidenceHref(cohort.id, wave.id, metric.metricId)}>Ver composição</Link> : "Observações enviadas"]))) } /> : <AnalyticsEmpty title="Ainda não há métricas comparáveis neste recorte" description="Associe os indicadores a métricas canônicas e envie observações para iniciar a análise." />}</AnalyticsSection>
    {data.milestones.length ? <AnalyticsSection title="Marcos registrados" description="Contagens de registros. O registro de marcos pode não ser exaustivo e não define uma taxa de sucesso."><AnalyticsTable caption="Marcos declarados no acompanhamento" headings={["Tipo de marco", "Registros"]} rows={data.milestones.map((milestone) => [milestoneLabels[milestone.type as keyof typeof milestoneLabels] ?? "Outro marco", milestone.count])} /></AnalyticsSection> : null}
    <ScopeNote />
  </div>;
}

export function CohortView({ data, canAnalyze = false, canManage = false, report = false }: { data: CohortAnalytics; canAnalyze?: boolean; canManage?: boolean; report?: boolean }) {
  return <div className="space-y-6"><SummaryStrip items={[{ label: "Participações na coorte", value: data.enrollmentCount }, { label: "Ondas", value: data.waves.length }, { label: "Protocolo", value: data.protocol ? `${data.protocol.name} · v${data.protocol.version}` : "A configurar" }, { label: "Indicadores sem métrica", value: data.quality.unmappedIndicators }]} />
    <ScopeNote>As leituras entre ondas podem incluir respondentes diferentes. A comparação pareada utiliza somente a mesma participação com valor válido nos dois momentos.</ScopeNote>
    <AnalyticsSection title="Cobertura" description="O universo esperado respeita a elegibilidade histórica na data de referência de cada onda.">{data.waves.length ? <div className="divide-y divide-line">{data.waves.map((wave) => <section className="analytics-wave" key={wave.id}><div><h3 className="font-medium"><Timepoint name={wave.name} offsetMonths={wave.offsetMonths} /></h3><p className="mt-2 text-xs text-slate">Referência: {formatMonitoringDate(wave.referenceAt)}</p></div><CoverageSummary coverage={wave.coverage} /></section>)}</div> : <AnalyticsEmpty title="Nenhuma onda disponível" description="Crie uma onda no espaço da coorte para organizar as observações esperadas." />}</AnalyticsSection>
    <AnalyticsSection title="Evolução dos indicadores" description="Resultados transversais de cada onda. Valores ausentes permanecem identificados; zero é um valor válido.">{data.waves.some((wave) => wave.metrics.length) ? <div className="divide-y divide-line">{data.waves.map((wave) => <section key={wave.id} className="analytics-wave-metrics"><header className="bg-surface-subtle px-5 py-4"><h3 className="font-semibold"><Timepoint name={wave.name} offsetMonths={wave.offsetMonths} /></h3><p className="mt-1 text-xs text-slate">{wave.coverage.submitted} observações enviadas de {wave.coverage.expected} esperadas</p></header>{wave.metrics.map((metric) => <MetricResult key={metric.metricId} aggregate={metric} evidenceHref={canAnalyze && !report ? evidenceHref(data.id, wave.id, metric.metricId) : undefined} missingHref={canAnalyze && !report ? `${evidenceHref(data.id, wave.id, metric.metricId)}&missing=1` : undefined} />)}</section>)}</div> : <AnalyticsEmpty title="Associe os indicadores às métricas" description="O vínculo com uma métrica canônica identifica o conceito observado e permite acompanhar versões compatíveis do protocolo." action={canManage && !report ? <Link className="button-secondary" href="/app/analytics/metrics">Configurar métricas</Link> : undefined} />}</AnalyticsSection>
    <AnalyticsSection title="Comparação pareada" description="Amostra comum de participações com valores válidos nos dois momentos. Variações são absolutas.">{data.paired.length ? <AnalyticsTable caption="Resultados calculados exclusivamente com os pares válidos; não representam efeito causal." headings={["Métrica / momentos", "n pareado", "Primeiro momento", "Segundo momento", "Variação média", "Variação mediana"]} rows={data.paired.map((pair) => [<><span className="font-medium">{pair.label}</span><span className="mt-1 block text-xs text-slate">{data.waves.find((wave) => wave.id === pair.baselineWaveId)?.name} → {data.waves.find((wave) => wave.id === pair.followUpWaveId)?.name}</span></>, pair.pairedCount, primaryValue(pair.baselineAggregate), primaryValue(pair.followUpAggregate), formatIndicatorValue(pair.meanAbsoluteChange, pair.valueType, pair.unit), formatIndicatorValue(pair.medianAbsoluteChange, pair.valueType, pair.unit)])} /> : <AnalyticsEmpty title="Ainda não há pares numéricos comparáveis" description="São necessários dois momentos com a mesma métrica numérica e valores válidos nas mesmas participações. Métricas categóricas mantêm suas distribuições por onda." />}</AnalyticsSection>
    <AnalyticsSection title="Qualidade e comparabilidade"><dl className="analytics-facts"><div><dt>Indicadores sem métrica canônica</dt><dd>{data.quality.unmappedIndicators}</dd></div><div><dt>Ondas sem mês de referência</dt><dd>{data.quality.missingOffsets}</dd></div><div><dt>Meses com mais de uma onda</dt><dd>{data.quality.ambiguousOffsets.length ? data.quality.ambiguousOffsets.map((offset) => `${offset} meses`).join(" · ") : "Nenhum"}</dd></div></dl><p className="analytics-footer-note">Ondas sem mês de referência podem ser lidas nesta coorte. Comparações entre coortes exigem uma métrica canônica e um mês de referência inequívoco.</p></AnalyticsSection>
  </div>;
}

export function QualityView({ data }: { data: DataQualityAnalytics }) {
  return <div className="space-y-6"><SummaryStrip items={[{ label: "Elegíveis sem envio", value: data.eligibleWithoutSubmission, detail: "Ausência de observação enviada" }, { label: "Valores ausentes", value: data.submittedWithoutMetricValue, detail: "Nas observações enviadas" }, { label: "Indicadores sem métrica", value: data.unmappedIndicators }, { label: "Meses ambíguos", value: data.ambiguousTimepoints }]} /><ScopeNote>Não resposta, ausência de valor e desligamento são situações distintas. O universo esperado utiliza a elegibilidade histórica de cada participação na data da onda.</ScopeNote>
    <AnalyticsSection title="Qualidade por coorte" description={`${data.missingOffsets} ondas sem mês de referência · ${data.withdrawn} registros de desligamento no recorte.`}>{data.cohorts.length ? <AnalyticsTable caption="Lacunas de comparabilidade das coortes incluídas no recorte" headings={["Programa / coorte", "Indicadores sem métrica", "Ondas sem mês", "Meses ambíguos"]} rows={data.cohorts.map((cohort) => [<><Link href={`/app/analytics/cohorts/${cohort.id}`} className="analytics-link">{cohort.name}</Link><span className="mt-1 block text-xs text-slate">{cohort.programName}</span></>, cohort.quality.unmappedIndicators, cohort.quality.missingOffsets, cohort.quality.ambiguousOffsets.length ? cohort.quality.ambiguousOffsets.map((offset) => `${offset} meses`).join(" · ") : "Nenhum"])} /> : <AnalyticsEmpty title="Nenhuma coorte neste recorte" description="Selecione outro programa ou cadastre uma coorte para organizar o acompanhamento." />}</AnalyticsSection>
    <AnalyticsSection title="Envios por onda"><AnalyticsTable caption="Não elegibilidade é separada da ausência de envio e do desligamento registrado." headings={["Coorte / onda", "Esperadas", "Enviadas", "Sem envio", "Não elegíveis", "Desligamentos"]} rows={data.cohorts.flatMap((cohort) => cohort.waves.map((wave) => [<><span className="font-medium">{cohort.name}</span><span className="mt-1 block text-xs text-slate"><Timepoint name={wave.name} offsetMonths={wave.offsetMonths} /></span></>, wave.coverage.expected, wave.coverage.submitted, wave.coverage.expected - wave.coverage.submitted, wave.coverage.notEligible, wave.coverage.withdrawn]))} /></AnalyticsSection>
    <AnalyticsSection title="Completude dos valores"><AnalyticsTable caption="Valores válidos e ausentes dentro das observações enviadas para cada métrica." headings={["Coorte / onda", "Métrica", "Enviadas", "n válido", "Ausentes"]} rows={data.cohorts.flatMap((cohort) => cohort.waves.flatMap((wave) => wave.metrics.map((metric) => [<><span className="font-medium">{cohort.name}</span><span className="mt-1 block text-xs text-slate">{wave.name}</span></>, metric.label, wave.coverage.submitted, metric.validCount, metric.missingCount])))} /></AnalyticsSection>
  </div>;
}

export function evidenceHref(cohortId: string, waveId: string, metricId: string) {
  return `/app/analytics/evidence?${new URLSearchParams({ cohortId, waveId, metricId }).toString()}`;
}
