"use client";

import Link from "next/link";
import { CalendarClock } from "lucide-react";
import { useMemo, useState } from "react";

import { StatusBadge } from "@/components/ui";
import type { FollowUpQueueItemDto } from "@/lib/dashboard/service";

export function FollowUpsManager({ queue, coverage }: { queue: FollowUpQueueItemDto[]; coverage: number | null }) {
  const [filter, setFilter] = useState<"ALL" | "TODAY" | "OVERDUE" | "REVIEW">("ALL");
  const openItems = queue.filter((item) => item.bucket !== "COMPLETED");
  const todayItems = openItems.filter((item) => item.bucket === "TODAY");
  const overdueItems = openItems.filter((item) => item.bucket === "OVERDUE");
  const reviewItems = openItems.filter((item) => item.bucket === "REVIEW");
  const filteredItems = useMemo(() => filter === "ALL" ? openItems : openItems.filter((item) => item.bucket === filter), [filter, openItems]);

  return <div>
    <section className="metric-strip" aria-label="Indicadores de acompanhamento"><FollowUpMetric label="Em aberto" value={openItems.length} tone="orange" /><FollowUpMetric label="Vencem hoje" value={todayItems.length} tone="warning" /><FollowUpMetric label="Em atraso" value={overdueItems.length} tone="danger" /><div className="metric-card metric-card-green"><dt>Cobertura média registrada</dt><dd>{coverage === null ? "—" : `${coverage}%`}</dd><small>{coverage === null ? "Sem observações enviadas" : "Observações enviadas"}</small></div></section>
    <div className="workspace-toolbar mt-4"><div className="filter-pills" aria-label="Filtrar acompanhamentos">{(["ALL", "TODAY", "OVERDUE", "REVIEW"] as const).map((value) => <button key={value} type="button" className={`filter-pill ${filter === value ? "is-active" : ""}`} onClick={() => setFilter(value)}>{filterLabel(value)} · {value === "ALL" ? openItems.length : value === "TODAY" ? todayItems.length : value === "OVERDUE" ? overdueItems.length : reviewItems.length}</button>)}</div><span className="text-[0.625rem] text-slate">{filteredItems.length} {filteredItems.length === 1 ? "registro" : "registros"}</span></div>
    <div className="workspace-grid-with-rail"><div className="min-w-0 space-y-5"><FollowUpSection title="Vencem hoje" tone="success" items={filter === "ALL" ? todayItems : filteredItems.filter((item) => item.bucket === "TODAY")} /><FollowUpSection title="Em atraso" tone="danger" items={filter === "ALL" ? overdueItems : filteredItems.filter((item) => item.bucket === "OVERDUE")} /><FollowUpSection title="Outros acompanhamentos abertos" tone="warning" items={filter === "ALL" ? openItems.filter((item) => item.bucket !== "TODAY" && item.bucket !== "OVERDUE") : filteredItems.filter((item) => item.bucket !== "TODAY" && item.bucket !== "OVERDUE")} /></div><TodayAgenda items={todayItems.length ? todayItems : reviewItems} /></div>
  </div>;
}

function FollowUpMetric({ label, value, tone }: { label: string; value: number; tone: "orange" | "warning" | "danger" }) { const bars = [14, 27, 19, 31, 23]; return <dl className={`metric-card ${tone === "warning" ? "metric-card-warning" : tone === "danger" ? "metric-card-danger" : ""}`}><dt>{label}</dt><div className="flex items-end justify-between gap-3"><dd>{value}</dd><div className={`mini-bars ${tone === "warning" ? "mini-bars-warning" : tone === "danger" ? "mini-bars-danger" : ""}`} aria-hidden="true">{bars.map((height, index) => <span key={index} style={{ height: `${height}px` }} />)}</div></div></dl>; }

function FollowUpSection({ title, tone, items }: { title: string; tone: "success" | "warning" | "danger"; items: FollowUpQueueItemDto[] }) { return <section aria-labelledby={title}><div className={`section-heading ${tone === "warning" ? "warning" : tone === "danger" ? "danger" : ""}`}><h2 id={title}>{title}<span className="section-count">{items.length}</span></h2><span className="text-[0.625rem] text-slate">{items.length ? "Fila operacional" : "Sem registros"}</span></div>{items.length ? <div className="workspace-card overflow-hidden"><table className="data-table"><caption className="sr-only">{title}</caption><thead><tr><th>Empreendimento</th><th>Onda</th><th>Prazo</th><th>Cobertura</th><th>Status</th><th><span className="sr-only">Ação</span></th></tr></thead><tbody>{items.map((item) => <FollowUpRow item={item} key={item.id} />)}</tbody></table><div className="mobile-records">{items.map((item) => <FollowUpMobileRow item={item} key={item.id} />)}</div></div> : <div className="workspace-empty"><p className="font-semibold text-ink">Nada nesta fila</p><p className="mt-1 text-xs text-slate">Os registros aparecem aqui quando houver dados reais para este estado.</p></div>}</section>; }

function FollowUpRow({ item }: { item: FollowUpQueueItemDto }) { return <tr id={item.id}><td><div className="flex items-center gap-2.5"><span className="profile-monogram h-7 w-7 rounded-lg text-[0.5625rem]">{initials(item.ventureName)}</span><span><strong className="font-semibold">{item.ventureName}</strong><small>{item.programName} · {item.cohortName}</small></span></div></td><td>{item.waveName}<small>Onda {item.waveSequence}</small></td><td>{formatDate(item.dueAt)}<small>{dueLabel(item)}</small></td><td><span className="text-[0.625rem] text-slate">{item.status === "SUBMITTED" ? "Enviada" : item.status === "IN_PROGRESS" ? "Em andamento" : "Pendente"}</span></td><td><QueueStatus item={item} /></td><td><Link href={`/app/follow-ups#${item.id}`} className="button-secondary min-h-8 px-2.5 text-[0.5625rem]">Abrir</Link></td></tr>; }
function FollowUpMobileRow({ item }: { item: FollowUpQueueItemDto }) { return <article id={item.id} className="mobile-record"><div className="min-w-0"><p>{item.ventureName}</p><small>{item.programName} · {item.cohortName}</small></div><QueueStatus item={item} /><div className="mobile-record-meta"><span>{item.waveName}</span><span>{formatDate(item.dueAt)}</span><Link href={`/app/follow-ups#${item.id}`} className="font-semibold text-accent-hover">Abrir</Link></div></article>; }

function TodayAgenda({ items }: { items: FollowUpQueueItemDto[] }) { return <aside className="right-rail h-fit" aria-label="Agenda de hoje"><div className="right-rail-header"><h2>Agenda de hoje</h2><span className="section-count">{items.length}</span></div>{items.slice(0, 6).map((item) => <div className="right-rail-item" key={item.id}><div className="flex items-start gap-2"><CalendarClock size={14} className="mt-0.5 shrink-0 text-accent" aria-hidden="true" /><div><p>{item.ventureName}</p><small>{item.waveName} · {formatDate(item.dueAt)}</small><div className="mt-2"><QueueStatus item={item} /></div></div></div></div>)}{!items.length ? <p className="px-3.5 py-4 text-xs text-slate">Nenhum item na agenda.</p> : null}</aside>; }

function QueueStatus({ item }: { item: FollowUpQueueItemDto }) { const config = item.bucket === "OVERDUE" ? { label: "Em atraso", tone: "danger" as const } : item.bucket === "REVIEW" ? { label: "Em revisão", tone: "warning" as const } : item.bucket === "TODAY" ? { label: "Vence hoje", tone: "accent" as const } : { label: "Agendada", tone: "neutral" as const }; return <StatusBadge label={config.label} tone={config.tone} />; }
function filterLabel(value: "ALL" | "TODAY" | "OVERDUE" | "REVIEW"): string { return ({ ALL: "Todos", TODAY: "Hoje", OVERDUE: "Atrasados", REVIEW: "Revisão" } as Record<typeof value, string>)[value]; }
function initials(name: string): string { return name.split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase(); }
function formatDate(value: string | null): string { return value ? new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", timeZone: "America/Fortaleza" }).format(new Date(value)) : "Sem prazo"; }
function dueLabel(item: FollowUpQueueItemDto): string { if (!item.dueAt) return "Sem prazo"; if (item.bucket === "OVERDUE") return "Em atraso"; if (item.bucket === "TODAY") return "Hoje"; if (item.bucket === "REVIEW") return "Em revisão"; if (item.bucket === "COMPLETED") return "Enviada"; return "Agendada"; }
