import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs, PageHeader, StatusBadge } from "@/components/ui";
import { AwardDetailSections } from "@/components/execution/award-detail";
import { awardStatusLabels, executionTone } from "@/components/execution/presentation";
import { requireAuthenticatedSession } from "@/lib/auth/session";
import { getPersonalAward } from "@/lib/awards/service";
import { ResourceNotFoundError } from "@/lib/errors";

export default async function PersonalAwardPage({ params }: { params: Promise<{ awardId: string }> }) { const { user } = await requireAuthenticatedSession(); const { awardId } = await params; const award = await getPersonalAward(user.id, awardId).catch((error: unknown) => { if (error instanceof ResourceNotFoundError) notFound(); throw error; }); const detailHref = `/app/personal/awards/${awardId}`; return <div className="min-w-0 space-y-6"><PageHeader title="Execução do apoio" description={`${award.application.projectNameSnapshot} · ${award.fundingCall.fundingProgram.name}`} breadcrumbs={<Breadcrumbs items={[{ label: "Meus programas", href: "/app/personal/programs" }, { label: "Execução do apoio" }]} />} action={<StatusBadge label={awardStatusLabels[award.status]} tone={executionTone(award.status)} />} /><div className="flex flex-col gap-2 text-sm leading-6 text-slate sm:flex-row sm:items-center sm:justify-between"><p className="break-words">{award.organization.name} · {award.fundingCall.title}</p><Link className="inline-flex min-h-11 items-center font-medium text-accent-hover" href={`/app/personal/applications/${award.applicationId}`}>Consultar candidatura</Link></div>{award.status === "SUSPENDED" ? <p className="border-l-2 border-warning pl-4 text-sm leading-7 text-slate">A execução está suspensa. Os registros e os prazos foram preservados; novos envios estarão disponíveis após a retomada pela instituição.</p> : award.status === "PREPARING" ? <p className="border-l-2 border-accent pl-4 text-sm leading-7 text-slate">A instituição está preparando os termos do apoio. As entregas podem ser elaboradas após a ativação da execução.</p> : null}{!award.canManage ? <p className="text-sm leading-6 text-slate">Você pode consultar esta execução. Os responsáveis atuais pelo projeto podem preparar e enviar as entregas.</p> : null}<AwardDetailSections award={award} detailHref={detailHref} /></div>; }
