import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs, PageHeader } from "@/components/ui";
import { getAnalyticsAccess, queryValue, type AnalyticsSearchParams } from "@/components/analytics/access";
import { AnalyticsEmpty, AnalyticsSection, AnalyticsTable, ScopeNote, formatIndicatorValue, formatMonitoringDate } from "@/components/analytics/presentation";
import { getMetricEvidence } from "@/lib/analytics/read-model";
import { observationStatusLabel } from "@/lib/monitoring/format";
import { ResourceNotFoundError } from "@/lib/errors";

export default async function AnalyticsEvidencePage({ searchParams }: { searchParams: Promise<AnalyticsSearchParams> }) {
  const { access } = await getAnalyticsAccess("ANALYST");
  const parameters = await searchParams;
  const cohortId = queryValue(parameters, "cohortId");
  const waveId = queryValue(parameters, "waveId");
  const metricId = queryValue(parameters, "metricId");
  const missing = queryValue(parameters, "missing") === "1";
  const page = Number(queryValue(parameters, "page") || "1");
  if (!cohortId || !waveId || !metricId || !Number.isSafeInteger(page) || page < 1) return <AnalyticsSection title="Origem dos dados"><AnalyticsEmpty title="Escolha uma métrica e uma onda" description="Abra Ver composição a partir de um resultado para consultar seus registros de origem." action={<Link href="/app/analytics" className="button-secondary">Abrir análises</Link>} /></AnalyticsSection>;
  const evidence = await getMetricEvidence(access, { cohortId, waveId, metricId, missing, page }).catch((error: unknown) => { if (error instanceof ResourceNotFoundError) notFound(); throw error; });
  const link = (options: { page?: number; missing?: boolean }) => `/app/analytics/evidence?${new URLSearchParams({ cohortId, waveId, metricId, missing: (options.missing ?? missing) ? "1" : "0", page: String(options.page ?? 1) })}`;
  return <div className="min-w-0 space-y-6"><PageHeader title="Origem dos dados" description={`${evidence.metric.label} · ${missing ? "Valores ausentes no universo elegível" : "Valores que contribuem para o resultado"}`} breadcrumbs={<Breadcrumbs items={[{ label: "Análises", href: "/app/analytics" }, { label: "Coorte", href: `/app/analytics/cohorts/${cohortId}` }, { label: "Composição" }]} />} /><ScopeNote>Este recorte detalhado é de acesso institucional. Os agregados consideram apenas observações enviadas com valor válido. A consulta de ausências ajuda a distinguir não resposta e ausência de valor.</ScopeNote><nav className="flex flex-wrap gap-2" aria-label="Tipo de evidência"><Link href={link({ missing: false })} className={missing ? "button-secondary" : "button-primary"} aria-current={!missing ? "page" : undefined}>Valores contribuintes</Link><Link href={link({ missing: true })} className={missing ? "button-primary" : "button-secondary"} aria-current={missing ? "page" : undefined}>Valores ausentes</Link></nav><AnalyticsSection title={missing ? "Registros sem valor válido" : "Observações contribuintes"} description={`${evidence.total} registros · página ${evidence.page}`}>{evidence.rows.length ? <AnalyticsTable caption="Cada registro preserva empreendimento, coorte, onda e acesso à observação original." headings={["Empreendimento", "Coorte / onda", "Valor", "Situação", "Elegibilidade", "Envio", "Observação"]} rows={evidence.rows.map((row) => [<Link key="venture" href={`/app/ventures/${row.ventureId}`} className="analytics-link">{row.ventureName}</Link>, <>{row.cohortName}<span className="mt-1 block text-xs text-slate">{row.waveName}</span></>, formatIndicatorValue(row.value, evidence.metric.valueType, evidence.metric.unit), observationStatusLabel(row.status), row.eligible ? "Elegível na referência" : "Fora do universo elegível", formatMonitoringDate(row.submittedAt), row.observationId ? <Link href={`/app/observations/${row.observationId}`} className="analytics-link">Abrir observação</Link> : "Sem observação"])} /> : <AnalyticsEmpty title="Nenhum registro neste recorte" description={missing ? "Não há ausências neste recorte de evidência." : "Não há observações enviadas com valor válido para esta métrica e onda."} />}</AnalyticsSection><nav className="flex flex-wrap items-center justify-between gap-3" aria-label="Paginação das evidências"><p className="text-xs text-slate">Até {evidence.pageSize} registros por página · {evidence.total} no recorte</p><div className="flex gap-2">{evidence.page > 1 ? <Link href={link({ page: evidence.page - 1 })} className="button-secondary">Anterior</Link> : null}{evidence.page * evidence.pageSize < evidence.total ? <Link href={link({ page: evidence.page + 1 })} className="button-secondary">Próxima</Link> : null}</div></nav></div>;
}
