import { ExternalLink } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { PageHeader, StatusBadge } from "@/components/ui";
import { ExternalOpportunityEditor } from "@/components/opportunities/external-editor";
import { getActiveOrganizationContext } from "@/lib/auth/session";
import { hasAtLeastRole } from "@/lib/auth/authorization";
import { listInstitutionOpportunities } from "@/lib/opportunities/service";
import { deadlineLabel, supportTypeLabels } from "@/lib/opportunities/presentation";
import { formatMonitoringDate } from "@/lib/monitoring/format";
export default async function OpportunitiesPage() {
  const context = await getActiveOrganizationContext(); if (!context) redirect("/app/organizations");
  const opportunities = await listInstitutionOpportunities(context.organization.id); const canManage = hasAtLeastRole(context.membership.role, "MANAGER");
  return <div className="min-w-0 space-y-6"><PageHeader title="Oportunidades externas" description="Curadoria institucional de chamadas com referência à fonte oficial e publicação explícita." action={canManage ? <ExternalOpportunityEditor organizationId={context.organization.id} /> : undefined} /><p className="text-sm leading-6 text-slate">Os editais da instituição são publicados nos respectivos <Link href="/app/programs" className="font-medium text-accent-hover underline underline-offset-4">programas</Link>.</p>{opportunities.length ? <div className="divide-y divide-line border-y border-line">{opportunities.map((record) => <article key={record.id} className="py-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><p className="text-xs text-slate">{record.institution} · {record.callNumber}</p><h2 className="mt-1 break-words text-lg font-semibold">{record.title}</h2></div><div className="flex flex-wrap gap-2"><StatusBadge label={record.publicListingEnabled ? "Listada publicamente" : "Somente na instituição"} tone={record.publicListingEnabled ? "accent" : "neutral"} /><StatusBadge label={deadlineLabel(record.status, null, record.applicationEndsAt?.toISOString() ?? null)} /></div></div><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-6 text-slate">{record.objective}</p><p className="mt-3 text-xs leading-5 text-slate">{supportTypeLabels[record.supportType]} · {record.territory}{record.audience ? ` · ${record.audience}` : ""}</p>{record.thematicAreas.length ? <p className="mt-2 text-xs text-slate">Áreas: {record.thematicAreas.join(" · ")}</p> : null}<div className="mt-4 flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2">{/^https?:\/\//i.test(record.sourceUrl) ? <a className="button-secondary" href={record.sourceUrl} target="_blank" rel="noopener noreferrer">Fonte oficial<ExternalLink size={16} aria-hidden="true" /></a> : <span className="text-xs text-slate">Fonte indisponível</span>}{canManage ? <ExternalOpportunityEditor organizationId={context.organization.id} record={{ ...record, publishedAt: record.publishedAt?.toISOString() ?? null, applicationEndsAt: record.applicationEndsAt?.toISOString() ?? null, sourceCheckedAt: record.sourceCheckedAt.toISOString() }} /> : null}</div><p className="text-xs text-slate">Fonte consultada em {formatMonitoringDate(record.sourceCheckedAt.toISOString())}</p></div></article>)}</div> : <div className="border-y border-line py-10"><h2 className="font-semibold">Nenhuma oportunidade externa registrada</h2><p className="mt-2 max-w-xl text-sm leading-6 text-slate">Registre chamadas de outras instituições, preserve a fonte e escolha quais aparecerão na descoberta pública.</p></div>}</div>;
}
