import Link from "next/link";
import { PageHeader, Panel, PanelHeader } from "@/components/ui";
import { NetworkRequestActions } from "@/components/network/request-actions";
import { ReportContact } from "@/components/communication/safety-report";
import { requireAuthenticatedSession } from "@/lib/auth/session";
import { listConnectionRequests } from "@/lib/network/connections";
import { listProjectRequests } from "@/lib/network/requests";
import { listTargetedInvites } from "@/lib/network/invites";

const roleLabels = { OWNER: "Proprietário", LEAD: "Líder", MEMBER: "Membro" };
export default async function RequestsPage() {
  const { user } = await requireAuthenticatedSession();
  const [connections, projects, invites] = await Promise.all([listConnectionRequests(user.id), listProjectRequests(user.id), listTargetedInvites(user.id)]);
  const empty = !connections.length && !projects.length && !invites.teams.length && !invites.projects.length;
  return <div className="space-y-6"><PageHeader title="Solicitações e convites" description="Analise contatos e colaborações recebidas ou acompanhe o que você enviou." />{empty ? <Panel className="p-6"><h2 className="font-semibold">Nenhuma pendência</h2><p className="mt-2 text-sm text-slate">Novas solicitações e convites aparecem aqui.</p><Link className="button-secondary mt-4" href="/app/personal/network">Explorar rede</Link></Panel> : null}
    {connections.length ? <Panel><PanelHeader title="Conexões" /><ul className="divide-y divide-line">{connections.map((request) => <li key={request.id} className="space-y-3 p-5"><p className="text-xs text-slate">{request.incoming ? "Recebida" : "Enviada"}</p><h2 className="break-words font-semibold">{request.person.fullName}</h2>{request.person.headline ? <p className="break-words text-sm text-slate">{request.person.headline}</p> : null}{request.message ? <p className="whitespace-pre-wrap break-words text-sm">{request.message}</p> : null}<NetworkRequestActions url={`/api/personal/network/connections/${request.id}`} incoming={request.incoming} />{request.incoming ? <ReportContact reportedUserId={request.person.userId} /> : null}</li>)}</ul></Panel> : null}
    {projects.length ? <Panel><PanelHeader title="Interesse em projetos" /><ul className="divide-y divide-line">{projects.map((request) => <li key={request.id} className="space-y-3 p-5"><p className="text-xs text-slate">{request.incoming ? "Recebida para o projeto" : "Enviada para o projeto"}</p><h2 className="break-words font-semibold">{request.projectName}</h2>{request.incoming ? <><p className="break-words text-sm font-medium">{request.person.fullName}</p><p className="break-words text-sm text-slate">{request.person.headline}</p>{request.person.skills.length ? <p className="break-words text-xs text-slate">{request.person.skills.join(" · ")}</p> : null}</> : null}{request.message ? <p className="whitespace-pre-wrap break-words text-sm">{request.message}</p> : null}{request.actionable || !request.incoming ? <NetworkRequestActions url={`/api/personal/network/projects/${request.projectId}/requests/${request.id}`} incoming={request.incoming} /> : <p className="text-sm text-slate">Projeto arquivado. A solicitação permanece no histórico.</p>}</li>)}</ul></Panel> : null}
    {invites.projects.length ? <Panel><PanelHeader title="Convites para projetos" description="Aceitar cria acesso direto ao projeto. Você não entra automaticamente na equipe." /><ul className="divide-y divide-line">{invites.projects.map((invite) => <li key={invite.id} className="space-y-3 p-5"><p className="text-xs text-slate">{invite.incoming ? "Recebido" : "Enviado"}</p><h2 className="break-words font-semibold">{invite.name}</h2><p className="break-words text-sm text-slate">{invite.summary}</p><p className="break-words text-sm">{invite.incoming ? "Convidado por" : "Enviado para"} {invite.person.fullName} · {roleLabels[invite.role]}</p>{invite.actionable ? <NetworkRequestActions url={`/api/personal/network/invites/${invite.id}`} incoming={invite.incoming} invitation acceptedHref={`/app/personal/projects/${invite.projectId}`} /> : <p className="text-sm text-slate">Projeto arquivado.</p>}</li>)}</ul></Panel> : null}
    {invites.teams.length ? <Panel><PanelHeader title="Convites para equipes" description="Ao aceitar, você entra na equipe e recebe o acesso derivado aos seus projetos." /><ul className="divide-y divide-line">{invites.teams.map((invite) => <li key={invite.id} className="space-y-3 p-5"><p className="text-xs text-slate">{invite.incoming ? "Recebido" : "Enviado"}</p><h2 className="break-words font-semibold">{invite.name}</h2>{invite.summary ? <p className="break-words text-sm text-slate">{invite.summary}</p> : null}<p className="break-words text-sm">{invite.incoming ? "Convidado por" : "Enviado para"} {invite.person.fullName} · {roleLabels[invite.role]}</p>{invite.actionable ? <NetworkRequestActions url={`/api/personal/network/team-invites/${invite.id}`} incoming={invite.incoming} invitation acceptedHref={`/app/personal/teams/${invite.teamId}`} /> : <p className="text-sm text-slate">Equipe arquivada.</p>}</li>)}</ul></Panel> : null}
  </div>;
}
