import Link from "next/link";
import { ArrowUpRight, Compass } from "lucide-react";
import { PageHeader, Panel, StatusBadge } from "@/components/ui";
import { ParticipantEmpty } from "@/components/personal/record-list";
import { requireAuthenticatedSession } from "@/lib/auth/session";
import { listPersonalOpportunities } from "@/lib/selection/service";
import { formatMonitoringDate } from "@/lib/monitoring/format";

export default async function PersonalOpportunities({ searchParams }: { searchParams: Promise<{ q?: string; source?: string }> }) {
  const { user } = await requireAuthenticatedSession(); const params = await searchParams; const query = typeof params.q === "string" ? params.q.slice(0, 200) : ""; const records = await listPersonalOpportunities(user.id, query); const opportunities = records.filter((record) => !["INTERNAL", "EXTERNAL"].includes(params.source ?? "") || record.kind === params.source);
  return <div className="space-y-6"><PageHeader title="Oportunidades" description="Editais das instituições no Innove e oportunidades externas com fonte oficial." /><form className="flex flex-col items-stretch gap-3 sm:flex-row sm:items-end" method="get"><label className="block flex-1 space-y-2 text-sm font-medium"><span>Buscar edital ou instituição</span><input className="field-control" type="search" name="q" defaultValue={query} maxLength={200} /></label><label className="block space-y-2 text-sm font-medium"><span>Fonte</span><select className="field-control" name="source" defaultValue={params.source ?? ""}><option value="">Todas</option><option value="INTERNAL">Instituições no Innove</option><option value="EXTERNAL">Oportunidades externas</option></select></label><button className="button-secondary">Buscar</button></form><Panel>{opportunities.length ? <ul className="divide-y divide-line">{opportunities.map((opportunity) => <li key={`${opportunity.kind}-${opportunity.id}`} className="space-y-3 px-5 py-5"><div className="flex items-start gap-3"><Compass size={19} className="mt-1 shrink-0 text-accent-hover" aria-hidden="true" /><div className="min-w-0"><p className="text-xs text-slate">{opportunity.institution} · {opportunity.callNumber}</p><h2 className="mt-1 break-words text-base font-semibold">{opportunity.title}</h2></div></div><p className="max-w-4xl whitespace-pre-wrap break-words text-sm leading-6 text-slate">{opportunity.objective}</p><div className="flex flex-wrap items-center justify-between gap-3"><div className="space-y-2"><StatusBadge label={opportunity.canApply ? "Candidatura pelo Innove" : opportunity.kind === "EXTERNAL" ? "Candidatura no site oficial" : "Edital institucional"} tone={opportunity.canApply ? "success" : "neutral"} /><p className="text-xs text-slate">Inscrições até: {formatMonitoringDate(opportunity.applicationEndsAt)}</p></div>{opportunity.kind === "INTERNAL" ? <Link className={opportunity.canApply ? "button-primary" : "button-secondary"} href={`/app/personal/opportunities/${opportunity.fundingCallId}`}>Ver edital<ArrowUpRight size={16} aria-hidden="true" /></Link> : opportunity.sourceUrl ? <a className="button-secondary" href={opportunity.sourceUrl} target="_blank" rel="noopener noreferrer">Abrir fonte oficial<ArrowUpRight size={16} aria-hidden="true" /></a> : null}</div></li>)}</ul> : <ParticipantEmpty title={query ? "Nenhum edital encontrado" : "Nenhuma oportunidade disponível"} description={query ? "Altere os termos da busca ou a fonte para explorar outras oportunidades." : "As oportunidades aparecerão aqui quando instituições publicarem editais ou registros com fonte oficial."} />}</Panel><p className="text-xs leading-5 text-slate">A elegibilidade depende das regras de cada edital. Consulte a publicação oficial antes de preparar sua candidatura.</p></div>;
}
