"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Link2, Copy } from "lucide-react";
import { Dialog } from "@/components/dialog";
import { personalRequest } from "@/components/personal/record-form";
import type { TeamDetailsDto, ProjectDetailsDto } from "@/lib/participants/service";

const roles: Record<string, string> = { OWNER: "Proprietário", LEAD: "Líder", MEMBER: "Membro" };

export function ParticipantMembers({ kind, record, userId }: { kind: "teams" | "projects"; record: TeamDetailsDto | ProjectDetailsDto; userId: string }) {
  const router = useRouter(); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false);
  const [confirmation, setConfirmation] = useState<{ id: string; input: unknown; title: string; description: string } | null>(null);
  const canManageMembers = kind === "teams" ? record.callerRole === "OWNER" : (record as ProjectDetailsDto).canManageMembers;
  async function change(id: string, input: unknown) { setPending(true); setError(null); try { await personalRequest(`/api/personal/${kind}/${record.id}/members/${id}`, "PATCH", input); setConfirmation(null); if (typeof input === "object" && input !== null && "action" in input && input.action === "leave") router.push(`/app/personal/${kind}`); else router.refresh(); } catch (error) { setError(error instanceof Error ? error.message : "Não foi possível alterar o acesso."); } finally { setPending(false); } }
  return <div className="space-y-4">{error && !confirmation ? <p className="px-5 text-sm text-danger" role="alert">{error}</p> : null}<ul className="divide-y divide-line">{record.members.map((member) => <li className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between" key={member.id}><div className="min-w-0"><p className="break-words font-medium text-ink">{member.fullName}</p><p className="break-all text-xs text-slate">{member.email}</p><p className="mt-1 text-xs text-slate">{roles[member.role]}{member.leftAt ? " · Participação encerrada" : ""}</p></div>{!record.archivedAt && !member.leftAt ? <div className="flex flex-wrap items-center gap-2">{canManageMembers ? <label className="text-xs text-slate"><span className="sr-only">Perfil de {member.fullName}</span><select className="field-control min-h-11 text-xs" value={member.role} disabled={pending} onChange={(event) => { const role = event.target.value; if (role === "OWNER") setConfirmation({ id: member.id, input: { role }, title: "Compartilhar propriedade", description: `${member.fullName} também terá controle administrativo. Seu perfil permanece o mesmo. Para sair, deve permanecer pelo menos um proprietário ativo.` }); else void change(member.id, { role }); }}><option value="MEMBER">Membro</option><option value="LEAD">Líder</option><option value="OWNER">Proprietário</option></select></label> : null}{(canManageMembers || member.userId === userId) ? <button className="button-secondary text-xs" disabled={pending} onClick={() => setConfirmation({ id: member.id, input: { action: member.userId === userId ? "leave" : "remove" }, title: member.userId === userId ? "Encerrar minha participação" : "Remover acesso", description: kind === "teams" ? "O vínculo histórico será preservado. O acesso aos projetos derivados desta equipe será encerrado; vínculos explícitos em projetos continuam vigentes." : "O vínculo histórico será preservado. O acesso derivado da equipe principal poderá continuar vigente." })}>{member.userId === userId ? "Sair" : "Remover"}</button> : null}</div> : null}</li>)}</ul><Dialog open={Boolean(confirmation)} title={confirmation?.title ?? "Alterar acesso"} description={confirmation?.description} onClose={() => { if (!pending) setConfirmation(null); }}>{error ? <p role="alert" className="mb-4 text-sm text-danger">{error}</p> : null}<div className="flex gap-3"><button className="button-secondary" disabled={pending} onClick={() => setConfirmation(null)}>Cancelar</button><button className="button-primary" disabled={pending} onClick={() => confirmation && void change(confirmation.id, confirmation.input)}>Confirmar</button></div></Dialog></div>;
}

export function TeamInvitation({ teamId, canInviteLead }: { teamId: string; canInviteLead: boolean }) {
  const [open, setOpen] = useState(false); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const [invite, setInvite] = useState<{ inviteUrl: string; expiresAt: string } | null>(null); const [copied, setCopied] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setPending(true); setError(null); try { const created = await personalRequest(`/api/personal/teams/${teamId}/invites`, "POST", { role: data.get("role"), email: data.get("email") || null }); setInvite({ ...created, inviteUrl: new URL(created.inviteUrl, window.location.origin).toString() }); } catch (error) { setError(error instanceof Error ? error.message : "Não foi possível gerar o convite."); } finally { setPending(false); } }
  return <><button className="button-secondary" onClick={() => { setInvite(null); setError(null); setCopied(false); setOpen(true); }}><Link2 size={16} aria-hidden="true" />Convidar membro</button><Dialog open={open} onClose={() => { if (!pending) setOpen(false); }} title="Convidar para a equipe" description="Gere um link de uso único e compartilhe com a pessoa. Nenhum e-mail será enviado pela plataforma.">{invite ? <div className="space-y-4"><p className="text-sm text-slate">Guarde o link agora. Ele não poderá ser recuperado depois de fechar esta janela.</p><label className="block space-y-2 text-sm font-medium"><span>Link do convite</span><input className="field-control" readOnly value={invite.inviteUrl} onFocus={(event) => event.target.select()} /></label><button className="button-secondary" onClick={async () => { try { await navigator.clipboard.writeText(invite.inviteUrl); setCopied(true); } catch { setError("Selecione e copie o link acima."); } }}><Copy size={16} aria-hidden="true" />{copied ? "Link copiado" : "Copiar link"}</button><p className="text-xs text-slate">Válido até {new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Fortaleza" }).format(new Date(invite.expiresAt))}.</p></div> : <form className="space-y-4" onSubmit={submit}><label className="block space-y-2 text-sm font-medium"><span>E-mail (opcional)</span><input className="field-control" name="email" type="email" maxLength={254} /><span className="block text-xs font-normal text-slate">Se informado, somente a conta com esse e-mail poderá aceitar.</span></label><label className="block space-y-2 text-sm font-medium"><span>Perfil</span><select className="field-control" name="role"><option value="MEMBER">Membro</option>{canInviteLead ? <option value="LEAD">Líder</option> : null}</select></label><button className="button-primary w-full" disabled={pending}>{pending ? "Gerando…" : "Gerar link"}</button></form>}{error ? <p className="mt-4 text-sm text-danger" role="alert">{error}</p> : null}</Dialog></>;
}
