import Link from "next/link";
import { ArrowUpRight, Layers3, UsersRound } from "lucide-react";
import { StatusBadge, statusTone } from "@/components/ui";
import type { TeamDto, ProjectDto } from "@/lib/participants/service";
import { projectStatusLabels } from "@/lib/participants/presentation";

export function ParticipantRecordList({ kind, records }: { kind: "teams" | "projects"; records: Array<TeamDto | ProjectDto> }) {
  const Icon = kind === "teams" ? UsersRound : Layers3;
  return <ul className="divide-y divide-line">{records.map((record) => <li key={record.id}><Link href={`/app/personal/${kind}/${record.id}`} className="flex min-h-24 items-start gap-3 px-5 py-5 hover:bg-surface-subtle sm:items-center"><span className="mt-1 grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-accent-soft text-accent-hover"><Icon size={19} aria-hidden="true" /></span><span className="min-w-0 flex-1"><span className="block break-words font-semibold text-ink">{record.name}</span><span className="mt-1 block text-sm text-slate">{kind === "teams" ? `${record.memberCount} ${record.memberCount === 1 ? "membro" : "membros"} · ${(record as TeamDto).projectCount} ${(record as TeamDto).projectCount === 1 ? "projeto" : "projetos"}` : (record as ProjectDto).teamName ?? "Projeto independente"}</span>{kind === "projects" ? <span className="mt-2 block line-clamp-2 text-sm text-slate">{(record as ProjectDto).summary}</span> : null}<span className="mt-2 inline-flex"><StatusBadge label={record.archivedAt ? "Arquivado" : kind === "teams" ? "Equipe ativa" : projectStatusLabels[(record as ProjectDto).status]} tone={statusTone(record.archivedAt ? "ARCHIVED" : kind === "teams" ? "ACTIVE" : (record as ProjectDto).status)} /></span></span>{kind === "projects" ? <span className="self-start text-xs text-slate sm:self-center">{({ PUBLIC: "Público", PLATFORM: "Plataforma", TEAM: "Colaboradores", PRIVATE: "Privado" } as Record<string, string>)[(record as ProjectDto).visibility]}</span> : null}<ArrowUpRight size={16} className="mt-1 shrink-0 text-slate" aria-hidden="true" /></Link></li>)}</ul>;
}

export function ParticipantEmpty({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="px-5 py-10"><h2 className="text-lg font-semibold tracking-tight">{title}</h2><p className="mt-2 max-w-xl text-sm leading-6 text-slate">{description}</p>{action ? <div className="mt-5 flex flex-wrap gap-3">{action}</div> : null}</div>; }
