import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs, PageHeader, StatusBadge } from "@/components/ui";
import { getAnalyticsAccess, queryValue, type AnalyticsSearchParams } from "@/components/analytics/access";
import { AnalyticsFeedback, AnalyticsSection, ScopeNote, reportTypeLabels, reportScopeLabel, formatAnalyticsDateTime } from "@/components/analytics/presentation";
import { ReportContent, PublicReportContent } from "@/components/analytics/report-content";
import { getAnalyticsReport, getAnalyticsReportSourceStatus } from "@/lib/analytics/reports";
import { listInstitutionPublicResults, previewPublicResult } from "@/lib/analytics/public-results";
import { ResourceNotFoundError } from "@/lib/errors";
import { archiveReportAction, publishResultAction, unpublishResultAction } from "@/app/app/analytics/reports/actions";

export default async function AnalyticsReportPage({ params, searchParams }: { params: Promise<{ reportId: string }>; searchParams: Promise<AnalyticsSearchParams> }) {
  const { access, canAnalyze, canManage } = await getAnalyticsAccess();
  const { reportId } = await params;
  const parameters = await searchParams;
  const report = await getAnalyticsReport(access, reportId).catch((error: unknown) => { if (error instanceof ResourceNotFoundError) notFound(); throw error; });
  const [source, publications] = await Promise.all([getAnalyticsReportSourceStatus(access, reportId), listInstitutionPublicResults(access)]);
  const ownPublications = publications.filter((publication) => publication.reportSnapshotId === reportId);
  const publicPreview = canManage && !report.archivedAt && queryValue(parameters, "publish") === "preview" ? await previewPublicResult(access, reportId) : null;
  const regenerateQuery = new URLSearchParams({ type: report.type, title: report.title, supersedesId: report.id, ...(report.parameters.programId ? { programId: report.parameters.programId } : {}), ...(report.parameters.callId ? { callId: report.parameters.callId } : {}), ...(report.parameters.year ? { year: String(report.parameters.year) } : {}), ...(report.parameters.cohortId ? { cohortId: report.parameters.cohortId } : {}), ...(report.parameters.metricId ? { metricId: report.parameters.metricId } : {}) });
  return <div className="min-w-0 space-y-6"><PageHeader title={report.title} description={`${reportTypeLabels[report.type]} · ${reportScopeLabel(report.payload.scope)}`} breadcrumbs={<Breadcrumbs items={[{ label: "Análises", href: "/app/analytics" }, { label: "Relatórios", href: "/app/analytics/reports" }, { label: report.title }]} />} action={<Link href={`/app/analytics/reports/${reportId}/print`} className="button-secondary">Versão para impressão</Link>} /><AnalyticsFeedback error={queryValue(parameters, "error")} success={queryValue(parameters, "success")} /><dl className="analytics-facts"><div><dt>Relatório gerado em</dt><dd>{formatAnalyticsDateTime(report.generatedAt)}</dd></div><div><dt>Gerado por</dt><dd>{report.generatedBy.name}</dd></div><div><dt>Dados disponíveis em</dt><dd>{formatAnalyticsDateTime(report.dataAsOf)}</dd></div><div><dt>Situação</dt><dd><StatusBadge label={report.archivedAt ? "Arquivado" : "Recorte preservado"} /></dd></div></dl>{!source.available ? <ScopeNote>Não foi possível conferir a atualização das fontes porque o recorte atual excede o limite de consulta. O relatório abaixo permanece preservado com a evidência da data de geração.</ScopeNote> : source.stale ? <ScopeNote>Há dados posteriores a este relatório. O conteúdo abaixo permanece preservado; gere um novo relatório para registrar a evidência atual.</ScopeNote> : <ScopeNote>Este relatório representa um recorte preservado. As fontes consultadas mantêm a mesma referência de origem desde a geração.</ScopeNote>}<ReportContent payload={report.payload} /><details className="analytics-filters"><summary>Referência de origem do relatório</summary><p className="mt-3 break-all font-mono text-xs text-slate">{report.sourceDigest}</p><p className="mt-2 text-xs text-slate">Versão da estrutura analítica: {report.analyticsSchemaVersion}. A referência identifica as fontes do recorte e não altera seu conteúdo.</p>{report.supersedesId ? <Link href={`/app/analytics/reports/${report.supersedesId}`} className="analytics-link mt-2 inline-flex">Abrir recorte anterior</Link> : null}</details>
    <div className="flex flex-wrap gap-2">{canAnalyze ? <Link href={`/app/analytics/reports?${regenerateQuery}`} className="button-secondary">Preparar novo relatório</Link> : null}{canManage && !report.archivedAt ? <><Link href={`/app/analytics/reports/${reportId}?publish=preview#public-preview`} className="button-primary">Conferir publicação pública</Link><form action={archiveReportAction}><input type="hidden" name="reportId" value={reportId} /><button className="button-secondary" type="submit">Arquivar relatório</button></form></> : null}</div>
    {publicPreview ? <section id="public-preview" className="space-y-6 border-t border-line pt-6" aria-labelledby="public-preview-title"><header><h2 id="public-preview-title" className="text-xl font-semibold">Prévia exata dos resultados públicos</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate">O conteúdo abaixo já aplica a proteção de grupos com menos de {publicPreview.minimumCellSize} registros. Confirme somente após revisar todas as seções. O público acessará este conteúdo agregado preservado.</p></header><PublicReportContent payload={publicPreview.payload} /><AnalyticsSection title="Confirmar publicação"><form action={publishResultAction} className="space-y-4 p-4 sm:p-6"><input type="hidden" name="reportId" value={reportId} /><input type="hidden" name="previewDigest" value={publicPreview.digest} /><label className="block text-sm font-medium">Título público<input name="title" className="field-control mt-2" defaultValue={report.title} minLength={3} maxLength={160} required /></label><label className="block text-sm font-medium">Endereço público<input name="slug" className="field-control mt-2" minLength={3} maxLength={64} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="resultados-do-programa-2026" required /><span className="mt-1 block text-xs text-slate">Letras minúsculas, números e hífens. Este endereço será estável.</span></label><label className="block text-sm font-medium">Resumo público<textarea name="summary" className="field-control mt-2" rows={3} maxLength={1200} /></label><label className="flex items-start gap-3 rounded-lg border border-line p-4 text-sm leading-6"><input type="checkbox" name="confirm" className="mt-1 h-4 w-4 shrink-0" required /><span>Revisei a prévia protegida e autorizo a divulgação pública deste recorte agregado.</span></label><button type="submit" className="button-primary">Publicar resultados revisados</button></form></AnalyticsSection></section> : null}
    {ownPublications.length ? <AnalyticsSection title="Publicações deste relatório"><ul className="divide-y divide-line">{ownPublications.map((publication) => <li key={publication.id} className="flex flex-wrap items-start justify-between gap-4 p-4 sm:p-6"><div><p className="font-medium">{publication.title}</p><p className="mt-1 text-xs text-slate">{publication.unpublishedAt ? `Retirada em ${formatAnalyticsDateTime(publication.unpublishedAt)}` : `Publicada em ${formatAnalyticsDateTime(publication.publishedAt)}`}</p>{!publication.unpublishedAt ? <Link href={`/results/${publication.slug}`} className="analytics-link mt-2 inline-flex">Abrir resultado público</Link> : null}</div>{canManage && !publication.unpublishedAt ? <form action={unpublishResultAction}><input type="hidden" name="publicationId" value={publication.id} /><button type="submit" className="button-secondary">Retirar do público</button></form> : null}</li>)}</ul></AnalyticsSection> : null}
  </div>;
}
