import Link from "next/link";
import { ArrowUpRight, BadgeCheck } from "lucide-react";
import type { ReactNode } from "react";
import { PageHeader, Panel, StatusBadge } from "@/components/ui";
import { ProfileSectionEditor, type ProfileSectionValues } from "@/components/profiles/section-editor";
import { ProfileRecordEditor, RemoveProfileRecord } from "@/components/profiles/record-editor";
import { ProfilePublicationControl } from "@/components/profiles/publication-control";
import { formatProfileDate, profileMonogram } from "@/components/profiles/profile-renderer";
import { requireAuthenticatedSession } from "@/lib/auth/session";
import { getOwnProfile } from "@/lib/profiles/service";
import { privacyFields, visibilityLabels } from "@/lib/profiles/visibility";
import { collaborationStatusLabels } from "@/lib/network/presentation";

function EditorSection({ title, description, action, children }: { title: string; description?: string; action?: ReactNode; children: ReactNode }) {
  return <section className="border-t border-line px-5 py-6 first:border-t-0 sm:px-7"><header className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h2 className="font-semibold">{title}</h2>{description ? <p className="mt-1 max-w-2xl text-sm leading-6 text-slate">{description}</p> : null}</div>{action}</header><div className="mt-4">{children}</div></section>;
}
function EmptySection({ children }: { children: ReactNode }) { return <p className="text-sm leading-6 text-slate">{children}</p>; }

export default async function PersonalProfilePage() {
  const { user } = await requireAuthenticatedSession(); const profile = await getOwnProfile(user.id);
  const values: ProfileSectionValues = { handle: profile.handle, headline: profile.headline, bio: profile.bio, city: profile.city, state: profile.state, country: profile.country, skills: profile.skills, interests: profile.interests, profileVisibility: profile.profileVisibility, skillsVisibility: profile.skillsVisibility, experienceVisibility: profile.experienceVisibility, educationVisibility: profile.educationVisibility, linksVisibility: profile.linksVisibility, verifiedParticipationVisibility: profile.verifiedParticipationVisibility, projectsVisibility: profile.projectsVisibility, directoryEnabled: profile.directoryEnabled, collaborationStatus: profile.collaborationStatus, collaborationNote: profile.collaborationNote };
  const published = profile.profileVisibility === "PUBLIC" && Boolean(profile.publishedAt);
  const ready = Boolean(profile.handle && profile.headline && profile.fullName.trim());
  return <div className="space-y-6"><PageHeader title="Perfil de inovação" description="Uma identidade para sua atuação em diferentes equipes, projetos e instituições." action={<ProfilePublicationControl published={published} ready={ready} handle={profile.handle} />} />
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-line bg-surface px-5 py-4"><div className="min-w-0"><StatusBadge label={published ? "Perfil publicado" : "Perfil sem publicação pública"} tone={published ? "success" : "neutral"} /><p className="mt-2 text-sm leading-6 text-slate">{ready ? "Confira o que uma pessoa sem login pode visualizar." : "Escolha um endereço e uma apresentação na seção Identidade para habilitar a publicação e a prévia."}</p></div><div className="flex flex-wrap gap-2">{ready ? <Link className="button-secondary" href="/app/personal/profile/preview">Visualizar perfil público</Link> : null}{published && profile.handle ? <Link className="button-tertiary" href={`/people/${profile.handle}`} target="_blank">Abrir página pública<ArrowUpRight size={15} aria-hidden="true" /></Link> : null}</div></div>
    <Panel>
      <EditorSection title="Descoberta e colaboração" description="Permita que outras pessoas na plataforma encontrem seu perfil para oportunidades de colaboração." action={<ProfileSectionEditor section="discovery" values={values} />}><p className="text-sm leading-6">{profile.directoryEnabled ? "Seu perfil participa da descoberta na Rede." : "Seu perfil não aparece na descoberta da Rede."}</p><p className="mt-2 text-sm text-slate">{collaborationStatusLabels[profile.collaborationStatus]}</p>{profile.collaborationNote ? <p className="mt-2 max-w-3xl whitespace-pre-line break-words text-sm leading-6 text-slate">{profile.collaborationNote}</p> : null}<Link className="button-tertiary mt-3" href="/app/personal/network">Explorar a Rede</Link></EditorSection>
      <EditorSection title="Identidade" action={<ProfileSectionEditor section="identity" values={values} />}>
        <div className="flex items-start gap-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-accent-soft font-semibold text-accent-hover" aria-hidden="true">{profileMonogram(profile.fullName)}</span><div className="min-w-0"><h3 className="break-words text-xl font-semibold tracking-[-0.025em]">{profile.fullName || "Complete seu nome na conta"}</h3><p className="mt-1 break-words text-sm leading-6 text-slate">{profile.headline || "Apresente sua atuação em uma frase."}</p>{[profile.city, profile.state, profile.country].some(Boolean) ? <p className="mt-2 text-xs text-slate">{[profile.city, profile.state, profile.country].filter(Boolean).join(" · ")}</p> : null}{profile.handle ? <p className="mt-2 break-all text-xs text-slate">/people/{profile.handle}</p> : null}</div></div>
      </EditorSection>
      <EditorSection title="Sobre" action={<ProfileSectionEditor section="about" values={values} />}>{profile.bio ? <p className="max-w-3xl whitespace-pre-line break-words text-sm leading-7 text-slate">{profile.bio}</p> : <EmptySection>Conte o que você desenvolve, sua experiência e seus objetivos na inovação.</EmptySection>}</EditorSection>
      <EditorSection title="Competências e interesses" action={<ProfileSectionEditor section="topics" values={values} />}><div className="grid gap-5 sm:grid-cols-2">{[["Competências", profile.skills], ["Áreas de interesse", profile.interests]].map(([label, topics]) => <div key={String(label)}><h3 className="text-sm font-medium">{String(label)}</h3>{(topics as string[]).length ? <ul className="mt-2 flex flex-wrap gap-2">{(topics as string[]).map((topic) => <li className="max-w-full break-words rounded-md bg-surface-subtle px-2.5 py-1 text-xs" key={topic}>{topic}</li>)}</ul> : <p className="mt-2 text-sm text-slate">Nenhuma informação adicionada.</p>}</div>)}</div></EditorSection>
      <EditorSection title="Experiência" description="Informações declaradas por você." action={<ProfileRecordEditor kind="experience" />}>{profile.experience.length ? <ol className="space-y-5">{profile.experience.map((record) => <li key={record.id} className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1 basis-48"><h3 className="break-words font-medium">{record.title}</h3><p className="mt-1 break-words text-sm text-slate">{record.organizationName}</p><p className="mt-1 text-xs text-slate">{formatProfileDate(record.startsAt)}{record.current ? " → atual" : record.endsAt ? ` → ${formatProfileDate(record.endsAt)}` : ""} · {visibilityLabels[record.visibility]}</p>{record.description ? <p className="mt-2 whitespace-pre-line break-words text-sm text-slate">{record.description}</p> : null}</div><div className="flex gap-2"><ProfileRecordEditor kind="experience" record={record} /><RemoveProfileRecord kind="experience" recordId={record.id} /></div></li>)}</ol> : <EmptySection>Adicione experiências profissionais, de pesquisa ou de participação em projetos.</EmptySection>}</EditorSection>
      <EditorSection title="Formação" description="Informações declaradas por você." action={<ProfileRecordEditor kind="education" />}>{profile.education.length ? <ol className="space-y-5">{profile.education.map((record) => <li key={record.id} className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1 basis-48"><h3 className="break-words font-medium">{record.course}</h3><p className="mt-1 break-words text-sm text-slate">{record.institution}{record.degree ? ` · ${record.degree}` : ""}</p><p className="mt-1 text-xs text-slate">{[formatProfileDate(record.startsAt), formatProfileDate(record.endsAt)].filter(Boolean).join(" → ")}{record.startsAt || record.endsAt ? " · " : ""}{visibilityLabels[record.visibility]}</p>{record.description ? <p className="mt-2 whitespace-pre-line break-words text-sm text-slate">{record.description}</p> : null}</div><div className="flex gap-2"><ProfileRecordEditor kind="education" record={record} /><RemoveProfileRecord kind="education" recordId={record.id} /></div></li>)}</ol> : <EmptySection>Registre sua formação e cursos relevantes para sua atuação.</EmptySection>}</EditorSection>
      <EditorSection title="Links" action={<ProfileRecordEditor kind="links" />}>{profile.links.length ? <ul className="space-y-4">{profile.links.map((record) => <li key={record.id} className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1 basis-48"><a className="inline-flex min-h-11 items-center gap-1 break-words text-sm font-medium text-accent-hover hover:underline" href={record.url} target="_blank" rel="noopener noreferrer">{record.label}<ArrowUpRight size={14} aria-hidden="true" /></a><p className="break-all text-xs text-slate">{record.url}</p><p className="mt-1 text-xs text-slate">{visibilityLabels[record.visibility]}</p></div><div className="flex gap-2"><ProfileRecordEditor kind="links" record={record} /><RemoveProfileRecord kind="links" recordId={record.id} /></div></li>)}</ul> : <EmptySection>Adicione seu site, portfólio ou perfis profissionais.</EmptySection>}</EditorSection>
      <EditorSection title="Privacidade" description="Seu e-mail e telefone de conta permanecem privados. A publicação exige sua confirmação." action={<ProfileSectionEditor section="privacy" values={values} />}><dl className="grid gap-x-8 gap-y-3 text-sm sm:grid-cols-2">{privacyFields.map(([name, label]) => <div key={name} className="flex flex-wrap justify-between gap-2"><dt className="text-slate">{label}</dt><dd className="font-medium">{visibilityLabels[profile[name]]}</dd></div>)}</dl></EditorSection>
      <EditorSection title="Participações verificadas" description="Derivadas de seleções publicadas e dos vínculos que você tinha no momento da candidatura.">{profile.verifiedParticipations.length ? <ul className="space-y-4">{profile.verifiedParticipations.map((participation) => <li key={participation.id} className="flex items-start gap-3"><BadgeCheck size={19} className="mt-0.5 shrink-0 text-success" aria-hidden="true" /><div><h3 className="font-medium">{participation.program}</h3><p className="mt-1 text-sm text-slate">{participation.institution} · {participation.call}</p><p className="mt-1 text-xs text-slate">{formatProfileDate(participation.date)}{participation.projectName ? ` · ${participation.projectName}` : ""}</p></div></li>)}</ul> : <EmptySection>Suas participações aparecerão quando uma candidatura elegível tiver seleção publicada. Esses registros não são editados manualmente.</EmptySection>}</EditorSection>
      <EditorSection title="Projetos públicos" description="Apenas projetos com publicação própria podem aparecer no perfil. A privacidade do perfil também se aplica." action={<Link className="button-secondary" href="/app/personal/projects">Gerenciar projetos</Link>}>{profile.publicProjects.length ? <ul className="space-y-3">{profile.publicProjects.map((project) => <li key={project.url}><Link className="inline-flex min-h-11 items-center gap-1 font-medium text-accent-hover hover:underline" href={project.url}>{project.name}<ArrowUpRight size={15} aria-hidden="true" /></Link><p className="max-w-3xl text-sm leading-6 text-slate">{project.summary}</p></li>)}</ul> : <EmptySection>Nenhum projeto público vinculado ao seu perfil. Configure a publicação de um projeto para apresentá-lo aqui.</EmptySection>}</EditorSection>
    </Panel>
  </div>;
}
